### ISSUE TITLE
hierarchical way to address model components

### ISSUE THREAD

**Issue by volodymyrss** [threeML/threeML#208]
what is the easiest way to address the composite models components and their parameters?

**Comment by giacomov** [comment]
You probably figured out by now... sorry, I missed this issue.

Anyway this is an example:

```python
# A composite model
composite_model = Powerlaw() + Gaussian()

# Now all parameters of the first component
# have a _1 appended, all the parameters of 
# the 2nd component have _2 appended

# Normalization of powerlaw
composite_model.K_1 = 2.1

# Normalization of Gaussian
composite_model.F_2 = 2.5
```

**Comment by volodymyrss** [comment]
Yes, thanks, that's what I use.
But I mean really hierarchical way, something like:

```python
composite_model.Powerlaw.K=1
```
otherwise the numbers change often when I change model even a bit, and I have to reassign them manually. That's quite annoying.

if there are many powerlaws, maybe then:

```python
composite_model = Powerlaw() + Powerlaw()
composite_model.Powerlaw_1.K=1
```

or maybe even, if I imagine:

```python
composite_model = Powerlaw(name="soft_pl") + Powerlaw(name="hard_pl")
composite_model.soft_pl.K=1
```
