### ISSUE TITLE
properties of the spectra and choosing sources for SpectrumLike

### ISSUE THREAD

**Issue by volodymyrss** [threeML/threeML#229]
would it make sense to assign some properties in the SpectrumLike plugin. it is quite useful when one wants to associate only some sources to a given spectrum, instead of summing all, as it is done now.

**Comment by grburgess** [comment]
@volodymyrss we have a system for this called 'tags'. This might be the way to address this. For now, tags were to associate plugins with a time interval:

https://github.com/giacomov/3ML/blob/master/threeML/plugin_prototype.py#L11

This is rather old:

https://github.com/giacomov/3ML/blob/master/examples/time_dependent_demo.ipynb

But it may be better to have some other way to do what you are wanting to achieve. Perhaps @giacomov has already a solution coded or in mind.

**Comment by volodymyrss** [comment]
it seems to be called "external_properties"? Ok, it's similar to what I want. I did setters/getters differently though.

**Comment by giacomov** [comment]
@volodymyrss can you describe a bit more the use case for this?

Right now the mindset with which 3ML was designed was to have in the model all sources that are in the sky within a certain region of interest. For non-imaging instruments you had to sum over all the sources, for imaging instruments you treat them one at the time.

However, already for the XYLike plugin, we implemented a solution where you can assign an SED to one specific source in the model. This makes sense for example when you are doing a joint analysis between a large-field instrument and SED data coming from narrow-field instruments.

We can implement something like this for all the OGIP-like plugins as well, if needed.

**Comment by volodymyrss** [comment]
The situation is that I have a number of sources fitted simultaneously, but each source has it's own OGIP. 
Sources share some parameters. If they did not, I would just run the joint fit multiple times, and not have this problem.

But yeah, like XYLike is an options.

Except, more generally, could be not just a source, but also some arbitrary set of properties.
E.g. I have some properties related to detector subsets,  they belong to the data too, and can be used if necessary (e.g. they affect response choice).

Time could be a property too. It seems like it is essentially a property of the data anyway. It can be assigned to IndependentVariable if needed, as it is done in the time-dependent example (by the way, it's broken - several minor inconsistencies following some improvements).

**Comment by grburgess** [comment]
@volodymyrss yes, that example is broken as I am waiting to see what @giacomov does for this case in astromodels. But, we can extend the properties as needed. Also, you can link parameters with astromodels:

http://astromodels.readthedocs.io/en/latest/Model_tutorial.html?highlight=link#linking-parameters

**Comment by volodymyrss** [comment]
I saw that @grburgess but to link the parameters, they have to be parameters of sources in one model, right?
In this case they are all summed for each OGIP, so it really does not help.

**Comment by grburgess** [comment]
I am not sure, I'll look at XYLike and extend its functionality to SpectrumLike

**Comment by volodymyrss** [comment]
That's what I did for myself and it's very easy, but I think it's not good enough, and relates to #228: you can not actually specify source model.

**Comment by grburgess** [comment]
@giacomov @volodymyrss I will take care of source assignment while on the place today as well as implementing @giacomov 's idea for #227 They are related, but I will break into two branches. 

On another note (and we shouldn't go back now!) it seems it would have been easier to have XYLike be the base of Spectrum... but Spectrum is really a different animal.

**Comment by giacomov** [comment]
@grburgess can you lay down what you want to do in pseudo-code (what the user would need to do to achieve what he wants to achieve)?

@volodymyrss what are the properties of a source that the plugin might need to decide the appropriate response of the instrument?

**Comment by volodymyrss** [comment]
@giacomov not properties of a source, but properties of data (in this thread we are taking about plugin properties, not model node properties :) ). many things: on a low level - event selection (which can be subset of detectors, GTI, etc)

**Comment by grburgess** [comment]
@giacomov in which issue?

**Comment by giacomov** [comment]
@grburgess you said:

> I will take care of source assignment

what do you mean by that?

@volodymyrss I see (I am confused with all these conversations happening at the same time :-) ). But then, a plugin can be extended with all the properties that you need, it does not share the same limitations of a source (a plugin is not a Node). For general things such as energy range and time range I would use tags. For other things, like subset of detectors, you can either use tags or your custom property.

**Comment by grburgess** [comment]
@giacomov I pushed https://github.com/giacomov/3ML/pull/231 which followed you implementation in XYLike to allow for assiging a plugin to a source.

**Comment by volodymyrss** [comment]
@giacomov ok. Just to be clear, the tags are in the code as external properties? Naively I can not really find anything relevant literally called "tag" in the code.

**Comment by grburgess** [comment]
But more specifically:


```python

spec_like = SpectrumLike() # or child

ps1 = PointSource('ps1', 0, 0, spectral_shape=Blackbody())
ps2 = PointSource('ps2', 0, 0, spectral_shape=Powerlaw())

model = Model(ps1, ps2)

model.ps2.spectrum.main.Powerlaw.K.fix = True
model.ps2.spectrum.main.Powerlaw.index.fix = True

spec_like.assign_to_source('ps1')

dl = DataList(spectrum_generator)

 jl = JointLikelihood(model, dl)


```

**Comment by giacomov** [comment]
@grburgess looks great.

@volodymyrss let me find an example for you. This feature is still a prototype so we can iterate over it and fix it if needed.
