### ISSUE TITLE
nuisance parameters as instrumental model

### ISSUE THREAD

**Issue by volodymyrss** [threeML/threeML#234]
There is a limitation with nuisance parameters:
```
"This is a bug of the plugin for %s: nuisance parameters must contain the instance name"
```
This is understandable.

But the instrument model would be shared between many instances.
In principle it is possible to define model in each through the nuisance parameters, and link them all, but it seems to make sense, to me, to have shared instrument model defined a single set of parameters. The model can be evaluated at different moments of time, different instrumental detector settings.

**Comment by grburgess** [comment]
Hi! Is this issue still relevant? Otherwise, we should close it
