### ISSUE TITLE
Plot XYLike data points on fit result

### ISSUE THREAD

**Issue by colasri** [threeML/threeML#305]
It would be nice to have the possibility to plot the XY data points of the XYLike class on the same plot as the `threeML.plot_point_source_spectra()`.
The `XYLike.plot()` method does not provide this since it's a very simple method not dealing with units, nor multiply by an E^2 factor for the Y scale. Any idea on how to best achieve this @grburgess ?

**Comment by grburgess** [comment]
Hi sorry for the delay! I can have a look at how to solve this. Ideally, this is *not* a good idea as the x-axis between the plugins is not guaranteed to be the same. SpectrumLike could have _reconstructed_ energy that is highly instrument dependent, and XYLike could have _true_ energy. Thus, it would convey an imprecise understanding of these two data spaces. That being said, I know how to fix it and will address it now :)
