### ISSUE TITLE
FermiLATSourceCatalog fails 

### ISSUE THREAD

**Issue by omodei** [threeML/threeML#317]
Due to the new release of the 4FGL, the schema in the FermiLATSourceCatalog (catalogs/Fermi.py) is no longer valid.
lat_catalog = FermiLATSourceCatalog()
ra, dec, table = lat_catalog.search_around_source("Crab", radius=20.0)
crashes

**Comment by grburgess** [comment]
Thanks for catching this! Too bad our tests keep failing for other reasons as this might have been flagged in the cron builds. I'll review when you have a fix.

**Comment by omodei** [comment]
This issue is fixed.
