### ISSUE TITLE
FermiGBMBurstCatalog() stopped working

### ISSUE THREAD

**Issue by hfdavidyu** [threeML/threeML#320]
Hi,

This morning when I do 

`%matplotlib inline
import os
import seaborn as sns
from matplotlib import cm
from matplotlib import pylab
import matplotlib.pyplot as plt
import numpy as np

import warnings
os.environ["MKL_NUM_THREADS"] = '1'
os.environ["OMP_NUM_THREADS"] = '1'
os.environ["NUMEXPR_NUM_THREADS"] = '1'
warnings.simplefilter('ignore')

from threeML import *
from threeML.io.package_data import get_path_of_data_file

gbmCatalog = FermiGBMBurstCatalog()`

I got

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-1f3b08248880> in <module>()
----> 1 gbmCatalog = FermiGBMBurstCatalog()

/usr/local/lib/python2.7/site-packages/threeML/catalogs/Fermi.pyc in __init__(self, update)
     55         super(FermiGBMBurstCatalog, self).__init__('fermigbrst',
     56                                                    threeML_config['catalogs']['Fermi']['GBM burst catalog'],
---> 57                                                    'Fermi-LAT/GBM burst catalog')
     58 
     59         self._gbm_detector_lookup = np.array(['n0', 'n1', 'n2', 'n3', 'n4', 'n5', 'n6',

/usr/local/lib/python2.7/site-packages/threeML/catalogs/VirtualObservatoryCatalog.pyc in __init__(self, name, url, description)
     24         self.catalog = VOSCatalog.create(name, url, description=description)
     25 
---> 26         self._get_vo_table_from_source()
     27 
     28         self._last_query_results = None

/usr/local/lib/python2.7/site-packages/threeML/catalogs/Fermi.pyc in _get_vo_table_from_source(self)
     66         self._vo_dataframe = get_heasarc_table_as_pandas('fermigbrst',
     67                                                          update=self._update,
---> 68                                                          cache_time_days=1.)
     69 
     70     def apply_format(self, table):

/usr/local/lib/python2.7/site-packages/threeML/io/get_heasarc_table_as_pandas.pyc in get_heasarc_table_as_pandas(heasarc_table_name, update, cache_time_days)
    136     with warnings.catch_warnings():
    137         warnings.simplefilter("ignore")
--> 138         vo_table = votable.parse(file_name_sanatized)
    139 
    140     table = vo_table.get_first_table().to_table(use_names_over_ids=True)

/usr/local/lib/python2.7/site-packages/astropy/io/votable/table.pyc in parse(source, columns, invalid, pedantic, chunk_size, table_number, table_id, filename, unit_format, datatype_mapping, _debug_python_based_parser)
    140         _debug_python_based_parser=_debug_python_based_parser) as iterator:
    141         return tree.VOTableFile(
--> 142             config=config, pos=(1, 1)).parse(iterator, config)
    143 
    144 

/usr/local/lib/python2.7/site-packages/astropy/io/votable/tree.pyc in parse(self, iterator, config)
   3403             if start:
   3404                 tag_mapping.get(tag, self._add_unknown_tag)(
-> 3405                     iterator, tag, data, config, pos)
   3406             elif tag == 'DESCRIPTION':
   3407                 if self.description is not None:

/usr/local/lib/python2.7/site-packages/astropy/io/votable/tree.pyc in _add_resource(self, iterator, tag, data, config, pos)
   3332         resource = Resource(config=config, pos=pos, **data)
   3333         self.resources.append(resource)
-> 3334         resource.parse(self, iterator, config)
   3335 
   3336     def _add_coosys(self, iterator, tag, data, config, pos):

/usr/local/lib/python2.7/site-packages/astropy/io/votable/tree.pyc in parse(self, votable, iterator, config)
   3154             if start:
   3155                 tag_mapping.get(tag, self._add_unknown_tag)(
-> 3156                     iterator, tag, data, config, pos)
   3157             elif tag == 'DESCRIPTION':
   3158                 if self.description is not None:

/usr/local/lib/python2.7/site-packages/astropy/io/votable/tree.pyc in _add_table(self, iterator, tag, data, config, pos)
   3111         table = Table(self._votable, config=config, pos=pos, **data)
   3112         self.tables.append(table)
-> 3113         table.parse(iterator, config)
   3114 
   3115     def _add_info(self, iterator, tag, data, config, pos):

/usr/local/lib/python2.7/site-packages/astropy/io/votable/tree.pyc in parse(self, iterator, config)
   2403                             'TABLEDATA', six.iterkeys(data), config, pos)
   2404                         self.array = self._parse_tabledata(
-> 2405                             iterator, colnumbers, fields, config)
   2406                         break
   2407                     elif tag == 'BINARY':

/usr/local/lib/python2.7/site-packages/astropy/io/votable/tree.pyc in _parse_tabledata(self, iterator, colnumbers, fields, config)
   2480                 row_mask = mask_default[:]
   2481                 i = 0
-> 2482                 for start, tag, data, pos in iterator:
   2483                     if start:
   2484                         binary = (data.get('encoding', None) == 'base64')

ValueError: 2677:5876: not well-formed (invalid token)`

I am wondering whether this is an issue for my laptop or on the NASA server side?

Thanks,
David

**Comment by grburgess** [comment]
Hi David. I just checked on my computer and cannot reproduce the result. Are you using the latest version? Is it possible you just have a slow connection?

**Comment by hfdavidyu** [comment]
Hi Michael, I just uninstalled 3ML and then re-installed. I checked that the internet speed is fast enough too, but the problem still persist.

**Comment by grburgess** [comment]
Hi,

So the latest build of threeml on the test server worked and passed the test. There must be something else going on. 

/J. Michael

**Comment by hfdavidyu** [comment]
Hi Michael, I did nothing but it is suddenly working again this afternoon. Strange. 

David

**Comment by grburgess** [comment]
Great! It’s likely some local internet configuration gone awry. 

/J. Michael
