### ISSUE TITLE
Too many samples in fit are thrown

### ISSUE THREAD

**Issue by eliadse** [threeML/threeML#323]
![Screenshot_2019-03-28 JupyterLab](https://user-images.githubusercontent.com/49037661/55177714-26343780-5184-11e9-8aee-d3f935815b2c.png)

I'm following the example 090217206.ipynb but most of my data are rejected when I do the fit. I tried enlarging the boundaries as suggested. Doing that sometimes I got less data rejected, but other times I got more.

Right now the boundaries of the model's parameters are set to None, so I don't know what else to do.

![Screenshot_2019-03-28 JupyterLab(1)](https://user-images.githubusercontent.com/49037661/55179357-8a0c2f80-5187-11e9-9244-558944b99748.png)

@grburgess , Giacomo recommended me to address you in this issue

Thank you

**Comment by grburgess** [comment]
Hi! So, at first, I thought that this was just the example not working. It should not as it is outdated and I am working to update this to a more modern build. That being said, if this is with a different data set, it is hard for me to understand the issue without a small working example or some code snippets. Can you please provide them here and we can work through this together? Thanks!

**Comment by eliadse** [comment]
I'm using a different data set, yes. I'm also using OGIPLike instead of FermiGBMLike.
These are the data sets I'm using, from LAT and GBM. I hope this helps

[https://drive.google.com/file/d/1MfN3k4tKbpDk-fRmoKISF51VQp-V6lo3/view?usp=sharing](url)
[https://drive.google.com/file/d/1674LlJeuedSlcNUsHmwxyu-X0eT9GqID/view?usp=sharing](url)
[https://drive.google.com/file/d/10sO3s-1kJaUen2OlCOO2tIVDbOmR__sG/view?usp=sharing](url)
[https://drive.google.com/file/d/18d9t6Ihietq-ErVGzkH8bWWdMjmSBuZM/view?usp=sharing](url)
[https://drive.google.com/file/d/1PrFergHLV8giMSzFNUFYqHfY01MqnTJq/view?usp=sharing](url)
[https://drive.google.com/file/d/1PAp1qtPV9Nw_mBSxujAxvUUEt9xFB21H/view?usp=sharing](url)
[https://drive.google.com/file/d/1jjC1HwPHvH8Tzf_KfP2fTdhVfQGh6oxb/view?usp=sharing](url)

**Comment by grburgess** [comment]
These links do not give me anything. Could you provide the script you are using?

**Comment by eliadse** [comment]
In point 14 is where the problem is
[combinedLHtutorial.pdf](https://github.com/threeML/threeML/files/3038927/combinedLHtutorial.pdf)

**Comment by grburgess** [comment]
From the first look, I would say that there is nothing wrong with the code. It appears that the fit is bad. It is not that the data are rejected, but rather that when 3ML samples the covariance matrix, it rejects samples too often because of the error distribution. Try fitting the GBM data alone or try different models.
