### ISSUE TITLE
Builds failing (master not compatible with numpy 1.12 anymore)

### ISSUE THREAD

**Issue by henrikef** [threeML/threeML#329]
See my recent comments on https://github.com/threeML/threeML/pull/289 (not sure if people will get notified since I commented on a closed pull request).

**Comment by henrikef** [comment]
That pull request uses `np.quantile`, which was introduced in numpy 1.15. We are running numpy 1.12.1, so a bunch of stuff broke.

Is this: https://github.com/threeML/threeML-meta/blob/master/recipe/meta.yaml the place we'd have to change the numpy version? Any reason *not* to upgrade?

**Comment by grburgess** [comment]
Is this issue still active? It might have gone away with the newest version.
