### ISSUE TITLE
'pytest -vv -rs --pyargs threeML' Fails 

### ISSUE THREAD

**Issue by Aishwarya113** [threeML/threeML#335]
'pytest -vv -rs --pyargs threeML' test fails with the error message saying:
dlopen(libmultinest.dylib, 6): image not found

<img width="1280" alt="Screen Shot 2019-06-19 at 11 33 40 PM" src="https://user-images.githubusercontent.com/51973893/59816724-32dfac00-92eb-11e9-96f7-cead94a2604a.png">

**Comment by grburgess** [comment]
It appears you do not have multinest installed.

**Comment by henrikef** [comment]
closed after discussion offline.
