### ISSUE TITLE
Problem with installation and testing

### ISSUE THREAD

**Issue by asattools** [threeML/threeML#336]
I am trying to install threeML, however, I am getting many problems to make it work. 

I am trying to run the cell [1] given here https://threeml.readthedocs.io/en/latest/notebooks/Quickstart.html
I am facing a few problems at the beginning itself.  I am listing them here

1) Warning when called for the first time (please see attached Figure1.png)
 
2) The yerr cannot be negative (Please see Figure2_1.png)

I tried to fix it my explicitly changing the sign in yerr to a minus sign and it seems to fix the problem. Will that be fine?
(please see Figure2_2.png)

3) Minimizer related problem (see Figure3.png).

I can only advance if I can sort out these problems. Please help with this.
![Figure1](https://user-images.githubusercontent.com/43138219/64329738-5ca49700-cfed-11e9-806e-f92297dd3ffa.png)
![Figure2_1](https://user-images.githubusercontent.com/43138219/64329740-5ca49700-cfed-11e9-873a-387901c088a4.png)
![Figure2_2](https://user-images.githubusercontent.com/43138219/64329741-5ca49700-cfed-11e9-8fa2-c05437f9efa4.png)
![Figure3](https://user-images.githubusercontent.com/43138219/64329742-5d3d2d80-cfed-11e9-898f-991d19207165.png)

**Comment by asattools** [comment]
I am unable to load images about this issue. I have sent the images via mail. Please load them here if needed.

**Comment by grburgess** [comment]
Hello, this is likely due to installing from pip which is slightly out of date with GitHub due to some testing issues. The GitHub version corrects issues due to an interface change with Minuit and YAML. 


To solve this problem, it is recommended to install via GitHub at the moment.

**Comment by henrikef** [comment]
Resolved.
