### ISSUE TITLE
Version for astroquery

### ISSUE THREAD

**Issue by hayalaso** [threeML/threeML#343]
Hello, 
I noticed that verision 0.4 of astroquery gives an error due to a syntax (see below). I downgraded my version to 0.3.6.post2 and was able to run again my application.

```
File` "/home/hza53/Software/miniconda2/lib/python2.7/site-packages/astroquery/vo_conesearch/core.py", line 62
    def query_region(self, coordinates, radius, *, verb=1,
                                                 ^
SyntaxError: invalid syntax
```

**Comment by grburgess** [comment]
Is the issue still existing? There is a new version of 3ML (py3 compatible) and it could solve a lot of issues such as this
