### ISSUE TITLE
Error installing threeML

### ISSUE THREAD

**Issue by migaraya** [threeML/threeML#344]
Hello,
after trying to install threeML with 
pip install git+https://github.com/threeML/threeML.git

I get the following error. Has anybody seen that?

`DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting git+https://github.com/threeML/threeML.git
  Cloning https://github.com/threeML/threeML.git to /private/var/folders/9r/ghm9k7tn5tv8pw240bcszwbw0000gn/T/pip-req-build-5tZ3Us
  Running command git clone -q https://github.com/threeML/threeML.git /private/var/folders/9r/ghm9k7tn5tv8pw240bcszwbw0000gn/T/pip-req-build-5tZ3Us
Requirement already satisfied: numpy<1.16,>=1.6 in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (1.15.3)
Requirement already satisfied: scipy>=0.18 in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (0.19.1)
Requirement already satisfied: emcee>=3 in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (3.0.2)
Requirement already satisfied: astropy>=1.3.3 in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (2.0.8)
Requirement already satisfied: matplotlib in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (2.1.1)
Requirement already satisfied: uncertainties in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (3.1.2)
Requirement already satisfied: pyyaml==3.13 in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (3.13)
Requirement already satisfied: dill in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (0.3.1.1)
Requirement already satisfied: iminuit>=1.2 in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (1.3.6)
Requirement already satisfied: astromodels in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (1.1.0)
Requirement already satisfied: astroquery<0.4 in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (0.3.8)
Requirement already satisfied: corner>=1.0.2 in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (2.0.1)
Requirement already satisfied: pandas in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (0.24.2)
Requirement already satisfied: requests in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (2.23.0)
Requirement already satisfied: speclite in ./hawc_software/miniconda3/envs/hal_analysis/lib/python2.7/site-packages (from threeML==0.4.1965) (0.7)
ERROR: Could not find a version that satisfies the requirement pygmo<=2.11.4,>=2.4 (from threeML==0.4.1965) (from versions: none)
ERROR: No matching distribution found for pygmo<=2.11.4,>=2.4 (from threeML==0.4.1965)
`

**Comment by grburgess** [comment]
Did this result in an error or a warning? We are currently in the process of migrating 3ML to py3, so hopefully this is gone soon

**Comment by henrikef** [comment]
I think the problem is at the very bottom:

```
ERROR: Could not find a version that satisfies the requirement pygmo<=2.11.4,>=2.4 (from threeML==0.4.1965) (from versions: none) ERROR: No matching distribution found for pygmo<=2.11.4,>=2.4 (from threeML==0.4.1965) 
```

**Comment by grburgess** [comment]
Ah... I did not see that. Hmm, we should not make pagmo a requirement for pip. I will fix that.

**Comment by migaraya** [comment]
Yeah, the problem it's the error at the end.

**Comment by grburgess** [comment]
Ok, I could get around this issue by removing the req in the setup file. However, a ton of other issues popped up because python2 is basically dead. I'm going to try version pinning even more, but this might break other things.

**Comment by grburgess** [comment]
Hi! Just wanted to let you know that we have made a new release and it should install on either python2 OR python3 now. please try via pip and let us know if you have trouble.

**Comment by migaraya** [comment]
Thank you. I was actually able to install the software using a ''clean'' new user a while ago. Perhaps some paths were set that messed with my installation.

**Comment by grburgess** [comment]
I think there is still pygmo in the setup. I will remove it now.
