### ISSUE TITLE
Not able to do hypothesis probability test using models from Xspec. Gets error specified function is not a known function. 

### ISSUE THREAD

**Issue by ShabnamIyyani** [threeML/threeML#345]
Starting ipyparallel cluster with this command line:
/Users/shabnam/miniconda/envs/threeML/bin/ipcluster start  --profile=default
Waiting for connection file: ~/.ipython/profile_default/security/ipcontroller-client.json
12 engines are active
0 / 800 in 0.1 s (--:-- remaining)

Shutting down ipcluster...
[8:apply]: 
---------------------------------------------------------------------------ModelSyntaxError                          Traceback (most recent call last)/Users/shabnam/miniconda/envs/threeML/lib/python2.7/site-packages/ipyparallel/serialize/serialize.pyc in unpack_apply_message(bufs, g, copy)
    203     args = []
    204     for i in range(info['nargs']):
--> 205         arg, arg_bufs = deserialize_object(arg_bufs, g)
    206         args.append(arg)
    207     args = tuple(args)
/Users/shabnam/miniconda/envs/threeML/lib/python2.7/site-packages/ipyparallel/serialize/serialize.pyc in deserialize_object(buffers, g)
    143     bufs = list(buffers)
    144     pobj = buffer_to_bytes_py2(bufs.pop(0))
--> 145     canned = pickle.loads(pobj)
    146     if istype(canned, sequence_types) and len(canned) < MAX_ITEMS:
    147         for c in canned:
/Users/shabnam/miniconda/envs/threeML/lib/python2.7/site-packages/dill/_dill.pyc in loads(str, ignore)
    314     """unpickle an object from a string"""
    315     file = StringIO(str)
--> 316     return load(file, ignore)
    317 
    318 # def dumpzs(obj, protocol=None):
/Users/shabnam/miniconda/envs/threeML/lib/python2.7/site-packages/dill/_dill.pyc in load(file, ignore)
    302     # apply kwd settings
    303     pik._ignore = bool(ignore)
--> 304     obj = pik.load()
    305     if type(obj).__module__ == getattr(_main_module, '__name__', '__main__'):
    306         if not ignore:
/Users/shabnam/miniconda/envs/threeML/lib/python2.7/pickle.pyc in load(self)
    862             while 1:
    863                 key = read(1)
--> 864                 dispatch[key](self)
    865         except _Stop, stopinst:
    866             return stopinst.value
/Users/shabnam/miniconda/envs/threeML/lib/python2.7/pickle.pyc in load_reduce(self)
   1137         args = stack.pop()
   1138         func = stack[-1]
-> 1139         value = func(*args)
   1140         stack[-1] = value
   1141     dispatch[REDUCE] = load_reduce
/Users/shabnam/miniconda/envs/threeML/lib/python2.7/site-packages/astromodels/core/serialization.pyc in unserialize_model(dict_with_types)
     27 def unserialize_model(dict_with_types):
     28 
---> 29     return ModelParser(model_dict=dict_with_types).get_model()
     30 
     31 # Register serialization/unserialization for Model
/Users/shabnam/miniconda/envs/threeML/lib/python2.7/site-packages/astromodels/core/model_parser.pyc in __init__(self, model_file, model_dict)
     90             self._model_dict = model_dict
     91 
---> 92         self._parse()
     93 
     94     def _parse(self):
/Users/shabnam/miniconda/envs/threeML/lib/python2.7/site-packages/astromodels/core/model_parser.pyc in _parse(self)
    136             else:
    137 
--> 138                 this_parser = SourceParser(source_or_var_name, source_or_var_definition)
    139 
    140                 res = this_parser.get_source()
/Users/shabnam/miniconda/envs/threeML/lib/python2.7/site-packages/astromodels/core/model_parser.pyc in __init__(self, source_name, source_definition)
    331         if source_type == POINT_SOURCE:
    332 
--> 333             self._parsed_source = self._parse_point_source(source_definition)
    334 
    335         elif source_type == EXTENDED_SOURCE:
/Users/shabnam/miniconda/envs/threeML/lib/python2.7/site-packages/astromodels/core/model_parser.pyc in _parse_point_source(self, pts_source_definition)
    409             try:
    410 
--> 411                 this_component = self._parse_spectral_component(component_name, component_definition)
    412 
    413                 components.append(this_component)
/Users/shabnam/miniconda/envs/threeML/lib/python2.7/site-packages/astromodels/core/model_parser.pyc in _parse_spectral_component(self, component_name, component_definition)
    571         shape_parser = ShapeParser(self._source_name)
    572 
--> 573         shape = shape_parser.parse(component_name, function_name, parameters_definition, is_spatial=False)
    574 
    575         # Get the links and extra setups, if any
/Users/shabnam/miniconda/envs/threeML/lib/python2.7/site-packages/astromodels/core/model_parser.pyc in parse(self, component_name, function_name, parameters_definition, is_spatial)
    655     def parse(self, component_name, function_name, parameters_definition, is_spatial = False):
    656 
--> 657         return self._parse_shape_definition(component_name, function_name, parameters_definition, is_spatial)
    658 
    659     @staticmethod
/Users/shabnam/miniconda/envs/threeML/lib/python2.7/site-packages/astromodels/core/model_parser.pyc in _parse_shape_definition(self, component_name, function_name, parameters_definition, is_spatial)
    682 
    683                 raise ModelSyntaxError("Function %s, specified as shape for %s of source %s, is not a "
--> 684                                        "known function" % (function_name, component_name, self._source_name))
    685 
    686         # Loop over the parameters of the function instance, instead of the specification,
ModelSyntaxError: Function XS_diskpbb, specified as shape for main of source test_mbb, is not a known function

**Comment by grburgess** [comment]
Thanks for the issue! We are having a look.

**Comment by grburgess** [comment]
We are currently in the middle of upgrading to python3 at the moment. My first guess is that this is an issue with serializing the XSPEC models for parallel. This should work, but only @giacomov could give a quick definite answer.

**Comment by grburgess** [comment]
there is a very new version of 3ML on pypi and Conda. Can you please retry with the new version in python3 and see if you issue persists?
