### ISSUE TITLE
download_LAT_data returns multiple files for large time interval

### ISSUE THREAD

**Issue by omodei** [threeML/threeML#356]
When the time range is large, download_LAT_data returns multiple fits files (from the FSSC) and the code fails to unpack them, because only one file is expected.
To reproduce this bug:
----
ra = 83.6331
dec = 22.0199
tstart = '2010-01-01 00:00:00'
tstop = '2011-01-01 00:00:00'
temp_dir = '_download_temp'
ft1, ft2 = download_LAT_data(ra, dec, 20.0, tstart, tstop, time_type='Gregorian',
                                 destination_directory=temp_dir)
----

**Comment by ndilalla** [comment]
Thanks Nicola for reporting this bug. What's the expected behavior in case of multiple files? Merge the FT1? Or return them as a list?

**Comment by omodei** [comment]
The download_LAT_data should return one ft1 and and ft2. I'll try to add few lines to do:
1. make a list of the downloaded files
2. Run gtselect to obtain a merged file.

**Comment by omodei** [comment]
I have created a PR #376 that should fix this.

**Comment by ndilalla** [comment]
Pull request merged on master. Closing this issue.
