### ISSUE TITLE
Reading background files produced by the extended-source tool of XMMSAS

### ISSUE THREAD

**Issue by domeckert** [threeML/threeML#357]
Hi all,

I am facing an issue when trying to read a background file outputted by the extended source analysis package (ESAS) of XMMSAS. You can find the error below

![image](https://user-images.githubusercontent.com/47885645/79682721-c6904a80-8224-11ea-8de1-b5b31169458e.png)

I come to understand that this is due to the file containing channels with Gaussian error set to 0. I understand that this is problematic for building a likelihood, but the corresponding channels should essentially always be ignored. Obviously, a workaround is to modify the file to set the Gaussian errors to some dummy value, then the file will load correctly; however users will complain that 3ML doesn't support reading the XMMSAS output out-of-the-box. 

I would suggest to let the FITS file be read normally but giving a warning, and ignoring by default the channels with 0 background error. This way the fitting wouldn't be screwed up and the users would be left responsible for their are doing.

Cheers,
Dominique

**Comment by grburgess** [comment]
Hi @domeckert. Thanks for pointing this out. Indeed, we are being very strict about standards in 3ML. The issue with ignoring is that a user and always revert this and then 3ML will produce erroneous results. At least in its current form.  I think we can build a work around... the question is how toileting make sure it keep the likelihoods fast, i.e., no checking at fit time. We should discuss this with @ndilalla and @omodei

**Comment by domeckert** [comment]
Wouldn't it be possible to set these channels as invalid when reading the file and not even allow the user to include them?

**Comment by grburgess** [comment]
It is possible... but at the moment there is no mechanism to prevent channels from being used. Only to exclude them. Changing this would require some delicate thought and programming to a lot of the low level stuff.

**Comment by domeckert** [comment]
The thing is, these channels are invalid channels and always ignored. I don't even know why they are included in the RMF in the first place, the PN always has 0 counts. How about setting a flag?
