### ISSUE TITLE
How to configure and set up the Fermi Science Tools?

### ISSUE THREAD

**Issue by Tangqingwen** [threeML/threeML#363]
I have installed the Fermi Science Tools via conda, then I install the threeML via conda. Now gtirfs is not work when in the threeML env. So how to configure and set up the Fermi Science Tools? Thank you very much.

**Comment by omodei** [comment]
Hi! 
Fermitools are not released for python 3 yet, this is probably why you run into issues.
I would recommend to use the installation script you can find here:
https://raw.githubusercontent.com/threeML/threeML/master/install_3ML.sh
and call it with :
./install_3ML.sh --with-fermi --python 2.7 -env-name YOUR_ENV_NAME
This will create a python 2.7 environment with fermitools, and threeml. (If you also need xspecmodels, you can add the --with-xspec
To see the full options: 
"./install_3ML.sh -h"
 Let us know if this fix the problem.

**Comment by Tangqingwen** [comment]
> Hi!
> Fermitools are not released for python 3 yet, this is probably why you run into issues.
> I would recommend to use the installation script you can find here:
> https://raw.githubusercontent.com/threeML/threeML/master/install_3ML.sh
> and call it with :
> ./install_3ML.sh --with-fermi --python 2.7 -env-name YOUR_ENV_NAME
> This will create a python 2.7 environment with fermitools, and threeml. (If you also need xspecmodels, you can add the --with-xspec
> To see the full options:
> "./install_3ML.sh -h"
> Let us know if this fix the problem.

Hi omodei,
It is work now, thanks for your quick reply!
