### ISSUE TITLE
Help with GTBurst GUI within Jupyter Notebook

### ISSUE THREAD

**Issue by gsrinivasaragavan** [threeML/threeML#366]
Hi, 
I am trying to fit five FERMI-LAT LCs, and am working within the threeML_test_2.7 environment. GTburst and ThreeML work correctly, however when fitting the bursts, the GUI corresponding to GTburst within the notebook does not seem to be working correctly, it shows up as a blank space, though I am able to move the cursor around within the GUI and close the GUI. I checked if this was a problem within GTburst itself, but that ran fine when running it independent of the jupyter notebook. The parameters and statistical measures of the fits all go through and are displayed correctly. Is there a problem with the particular environment I am working with (the 2.7 environment uses python2 so I thought that might be a problem).
Thank you

**Comment by omodei** [comment]
GTBurst and threeml are separate things. We have never tested opening the gtburst gui into the notebook. gtburst is a stand alone app.
