### ISSUE TITLE
ThreeML HTTP 503 SERVICE UNAVAILABLE for conda channel

### ISSUE THREAD

**Issue by ivvv** [threeML/threeML#371]
I'm trying to install threeML following the installation instructions:

`conda install -c conda-forge -c threeml astromodels threeml`

this command fails with:

```
CondaHTTPError: HTTP 503 SERVICE UNAVAILABLE: BACK-END SERVER IS AT CAPACITY for url <https://conda.anaconda.org/threeml/osx-64/current_repodata.json>
Elapsed: 00:07.691097
CF-RAY: 5c7bef8cfae3ff08-MAD

A remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.
```
I will try again later, as suggested in the error message. Meanwhile I'll try to install it via `pip`

**Comment by grburgess** [comment]
Thanks! We will have a look, @ndilalla there is still a threeml channel, correct?

**Comment by ndilalla** [comment]
Yes, of course. I've just tried to reproduce the error but it is working well on my laptop. Probably it was just one (of many) temporary glitch of conda. @ivvv could you please try again and see if it works?

**Comment by grburgess** [comment]
I think @ivvv observed  earlier that a server was down.

**Comment by ivvv** [comment]
Just tried it. It seems the server can be accessed now, but the conda installation does not look to work properly. I started with a fresh new conda environment:
1. `conda create --name threeML -c conda-forge python=3.7 numpy scipy matplotlib`
2. `conda install -c conda-forge -c threeml astromodels threeml`
``` 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done
```
this takes a long time to solve and then `libgfortran` and `scipy` need to be downgraded.

While `conda install -c xspecmodels xspec-modelsonly` fails with conflicts, here is the terminal echo:
```
(3ml) xmmm24: ~ $ conda install -c xspecmodels xspec-modelsonly
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                  

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package ncurses conflicts for:
python=3.7 -> readline[version='>=8.0,<9.0a0'] -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.2,<6.3.0a0']
python=3.7 -> ncurses[version='>=6.1,<7.0a0|>=6.2,<7.0a0']

Package readline conflicts for:
xspec-modelsonly -> readline[version='6.2|7.0']
python=3.7 -> readline[version='>=7.0,<8.0a0|>=8.0,<9.0a0']

Package libcxx conflicts for:
python=3.7 -> libffi[version='>=3.3,<3.4.0a0'] -> libcxx[version='>=10.0.0']
python=3.7 -> libcxx[version='>=10.0.1|>=4.0.1']
```

This is not a showstopper as `threeML` it installs now, but probably some requirements need updating to avoid this.

**Comment by ndilalla** [comment]
Hi @ivvv, thank you for reporting this. I am sorry, we are in the process of removing most of the version requirements causing these issues. In the meantime, did you try to use the install script provided in the documentation? It should take care of installing all the needed packages.

**Comment by ivvv** [comment]
Hi @ndilalla, no I did not use the install scripts, I went the pip way and this worked ok. I.e. I've created a clean new conda environment and then installed 3ML with pip in this new environment.

**Comment by henrikef** [comment]
Is this still a problem, or is the conda installation working now?

**Comment by ivvv** [comment]
I just checked. The `threeML` is properly installed with conda and channel `conda-forge`. 

However, the xspec models installation with conda still fails, exactly the same way as described in my first post.

`conda install -c xspecmodels xspec-modelsonly`

**Comment by grburgess** [comment]
@ivvv strange! It seems to be installing in the CI tests. 

https://github.com/threeML/astromodels/runs/1910134823?check_suite_focus=true#step:7:1

We have seen intermittent issues with this. I'll try and investigate.
