### ISSUE TITLE
Docs missing plots and notebook with errors

### ISSUE THREAD

**Issue by ivvv** [threeML/threeML#374]
The notebook in the docs on the Point Source Plotting Basics seems incomplete: it was not executed and the plots are missing. In addition, there is a unit conversion error in one of the first cells. [This page.](https://threeml.readthedocs.io/en/latest/notebooks/Point_source_plotting.html)

**Comment by grburgess** [comment]
@ivvv just to keep this updated... we are switching to live doc updating, so this should be fixed soon!

**Comment by ivvv** [comment]
Just checked and the docs look fine. Can be closed.

**Comment by grburgess** [comment]
@ivvv thanks! Please feel free to reopen if there are issues. The docs are now built with each change so they should be up to date. Please also note there are some tips for XSPEC users: 

https://threeml.readthedocs.io/en/latest/xspec_users.html
