### ISSUE TITLE
Using Spectral Fits to Calculate Fluxes

### ISSUE THREAD

**Issue by chenjiaming5821** [threeML/threeML#377]
Hi!
     How to calculate the Fluence of each bin?

**Comment by grburgess** [comment]
Can you provide a more specific question? Do you mean each spectral bin? Which type of plugin?

**Comment by chenjiaming5821** [comment]
> 您能否提供更具体的问题？你是说每个光谱箱吗？哪种类型的插件？

**Comment by chenjiaming5821** [comment]
> Can you provide a more specific question? Do you mean each spectral bin? Which type of plugin?

Thank you very much for your reply.I want to perform time-resolved analysis and calculate the fluence of each time bin.

**Comment by chenjiaming5821** [comment]
> Can you provide a more specific question? Do you mean each spectral bin? Which type of plugin?

Thank you very much for your  @grburgess .I want to perform time-resolved analysis and calculate the fluence of each time bin.

**Comment by grburgess** [comment]
Each fit provides the ability to compute the energy flux over a given energy range via the analysis results object. Once can then take that an multiply by the exposure to obtain the fluence.

**Comment by chenjiaming5821** [comment]
> Each fit provides the ability to compute the energy flux over a given energy range via the analysis results object. Once can then take that an multiply by the exposure to obtain the fluence.

thank you for your help!
