### ISSUE TITLE
perform time-resolved analysis

### ISSUE THREAD

**Issue by mingjiac** [threeML/threeML#379]
Hi,
    I am a beginner in 3ML and I want to perform time-resolved analysis; calculate_point_source_flux() can only get the total flux, how to get the flux of each bin?

**Comment by grburgess** [comment]
Can you define what you mean by bin and which plugin you are referring to? 

The point source flux is a function of the model. There is no concept of flux on the data side and they detect rates. Does this make sense?

**Comment by mingjiac** [comment]
> Can you define what you mean by bin and which plugin you are referring to?
> 
> The point source flux is a function of the model. There is no concept of flux on the data side and they detect rates. Does this make sense?

Thanks for your reply, bin is time intervals, I want to get the flux of time slices in time-resolved spectral, what plug-in do I need to use?

**Comment by grburgess** [comment]
Ah. Each time interval fit should have a model associated with it. If you can share some code, it will be easier to help.

**Comment by mingjiac** [comment]
> Ah. Each time interval fit should have a model associated with it. If you can share some code, it will be easier to help.

[spectral analysis.pdf](https://github.com/threeML/threeML/files/5276641/spectral.analysis.pdf)
This is my code.

**Comment by grburgess** [comment]
It appears, at the very end, that you have computed the results. Is there a clean example you can provide that shows the confusion?

**Comment by mingjiac** [comment]
> It appears, at the very end, that you have computed the results. Is there a clean example you can provide that shows the confusion?
I want to get F(Col. 8) in the picture .PICTURE:/home/admin/.config/tencent-qq//AppData/file//sendpix2.jpg

**Comment by grburgess** [comment]
I understand the result, but I do not see where you have an issue. Is there a specific code example that you can show using the syntax provided in GitHub issues that illuminates the part that is confusing?

**Comment by mingjiac** [comment]
> I understand the result, but I do not see where you have an issue. Is there a specific code example that you can show using the syntax provided in GitHub issues that illuminates the part that is confusing?

My question is very simple. I use the calculate_point_source_flux() plugin to only calculate the total flux. The result I want is the flux of each time slice. How do I write the code?

**Comment by grburgess** [comment]
Perhaps the structure of the model is not explained well enough. Each fit is associated to a model. That fit can be over several plugins corresponding to different time intervals, the same time interval, etc. There is a large amount of freedom to design an analysis. 

If you are performing fits on several intervals, for example, to a GRB, then each will have a model associated to it. The model can have point sources, extended sources, polarization sources, etc. There is a helper function supplied that will compute the post-fit energy flux of a model. This can be done on separate time intervals. There is not the sense of. "total" flux unless you design your model that way. Therefore, you can loop over time bins and compute the flux of each fit with the associated error propagation.
