### ISSUE TITLE
Help with Fermi GBM spectral analysis

### ISSUE THREAD

**Issue by mingjiac** [threeML/threeML#381]
HI,
    How to use the synchrotron model to fit the Fermi GBM spectrum?

**Comment by grburgess** [comment]
Hi @mingjiac which synchrotron model do you mean?

**Comment by mingjiac** [comment]
> Hi @mingjiac which synchrotron model do you mean?

Thanks for your answer @grburgess ,I mean cool synchrotron.

**Comment by grburgess** [comment]
Can you specify the package you would like to use?

**Comment by mingjiac** [comment]
> Can you specify the package you would like to use?

I want to use cool synchrotron model in 3ML.

**Comment by grburgess** [comment]
Which one? There is a synchrotron package included from naima, but these are not appropriate for GRBs. Do you have your own model you would like to include?

**Comment by mingjiac** [comment]
> Which one? There is a synchrotron package included from naima, but these are not appropriate for GRBs. Do you have your own model you would like to include?

There is no synchrotron model suitable for GRB in astromodels?

**Comment by grburgess** [comment]
There is no standard synchrotron model. There are external packages. OR one can write the model themselves.

**Comment by mingjiac** [comment]
> external packages

Do you know any external packages? I saw in your paper that you used the synchrotron model.

**Comment by grburgess** [comment]
https://pypi.org/project/pynchrotron/

**Comment by mingjiac** [comment]
> https://pypi.org/project/pynchrotron/

Thanks for your help.I ran into a problem when I defined the prior, and an error occurred when performing Bayesian fitting. Below is the prior I defined:
syn= pynchrotron.SynchrotronNumerical()
syn.gamma_min=1e5
syn.K.prior=Log_uniform_prior(lower_bound=0.01, upper_bound=1e1)
syn.B.prior= Log_uniform_prior(lower_bound=1e-2, upper_bound=1e2)
syn.gamma_cool.prior=Log_uniform_prior(lower_bound=1e3, upper_bound=1e6)
syn.gamma_max.prior=Log_uniform_prior(lower_bound=1e5, upper_bound=1e8)
syn.index.prior=Truncated_gaussian(lower_bound=2, upper_bound=6, mu=-1, sigma=0.5)
spec1 = syn
ps1 = PointSource("grb", 0, 0, spectral_shape=spec1)
model1= Model(ps1)

**Comment by grburgess** [comment]
You have set the mean of the gaussian outside the prior for the electron index.

**Comment by mingjiac** [comment]
> You have set the mean of the gaussian outside the prior for the electron index.

I still got an error after modifying, the modified code:
syn= pynchrotron.SynchrotronNumerical()
syn.gamma_min=1e5
syn.K.prior=Log_uniform_prior(lower_bound=0.01, upper_bound=1e10)
syn.B.prior= Log_uniform_prior(lower_bound=1e-2, upper_bound=1e2)
syn.gamma_cool.prior=Log_uniform_prior(lower_bound=1e3, upper_bound=1e8)
syn.gamma_max.prior=Log_uniform_prior(lower_bound=1e5, upper_bound=1e9)
syn.index.prior=Log_normal(mu=2, sigma=1)
syn.index.bounds =  (2, 6)
spec1 = syn
ps1 = PointSource("grb", 0, 0, spectral_shape=spec1)
model1= Model(ps1)

Error:
SettingOutOfBounds: Trying to set parameter index = 9.811178255545535, which is more than the maximum allowed 6.0

**Comment by grburgess** [comment]
You have not bounded the parameter properly.

**Comment by grburgess** [comment]
Is this issue resolved @mingjiac ?

**Comment by mingjiac** [comment]
> Is this issue resolved @mingjiac ?

Thanks for your help, the problem has been solved.
