### ISSUE TITLE
HD5 locking

### ISSUE THREAD

**Issue by torresramiro350** [threeML/threeML#389]
Found an issue with threeML with python 3.7 when using `template_model.py`

```
File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 444, in H5Fcreate
    unable to create file
  File "H5Fint.c", line 1567, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1640, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 957, in H5FD_sec2_lock
    file locking disabled on this file system (use HDF5_USE_FILE_LOCKING environment variable to override), errno = 38, error message = 'Function not implemented'

End of HDF5 error back trace
```

**Comment by henrikef** [comment]
Can you provide a minimal example to reproduce the problem?

**Comment by grburgess** [comment]
@torresramiro350 while we wait on your example, is it possible that you are trying things in parallel and that the model is being accessed multiple times?

**Comment by torresramiro350** [comment]
I'll look into building the example, but I think you're right the HD5 file is opened multiple times during the fitting process.

**Comment by henrikef** [comment]
@torresramiro350 you said on the HAWC slack that `export HDF5_USE_FILE_LOCKING=FALSE` fixed this, is that correct? If that is the case, we should include that in the installation instructions as an option/recommendation and close this issue.

**Comment by torresramiro350** [comment]
Yes, by setting export HDF5_USE_FILE_LOCKING=FALSE in the script to setup the environment, this issue is solved.
