### ISSUE TITLE
 Help with GBM data analysis

### ISSUE THREAD

**Issue by chenjiaming5821** [threeML/threeML#391]
Hi,
  When using 3ml to analyze GBM data, how to export the light curve data?

**Comment by grburgess** [comment]
What format would you like export the light curve? In principle all the information is contained in a time series class.

**Comment by chenjiaming5821** [comment]
> What format would you like export the light curve? In principle all the information is contained in a time series class.

Thank you for your reply. I would like to take out the light curve data of a certain period of time and save it in text format.

**Comment by grburgess** [comment]
There is no direct way to output a counts light curve. One way this can be achieved is by accessing the counts from a time series builder object.

**Comment by grburgess** [comment]
One can also save multiple bins to a PHAII file.

**Comment by grburgess** [comment]
Is the issue resolved @chenjiaming5821 ?
