### ISSUE TITLE
Alternative to root_numpy

### ISSUE THREAD

**Issue by cbrisboi** [threeML/threeML#404]
I was looking at updating `hawc_hal` to use `uproot` rather than the old ROOT interface for its `.root` file io and saw that a big part of the `root_numpy` dependency is carried over from 3ML via the dependency on `threeML/io/cern_root_utils`. I would generally prefer to stay consistent with file handling between 3ML and hawc_hal. Is there a preference for uproot vs the new ROOT interface? This is already an issue in hawc_hal, see [https://github.com/threeML/hawc_hal/issues/42](https://github.com/threeML/hawc_hal/issues/42) 

The code looks straightforward to update, but before I run off and implement something that is not preferred, I thought asking would be wise first.

**Comment by grburgess** [comment]
@cbrisboi I think the other part of ROOT that is used in in the ROOT minimizers. Is this also a simple fix?

**Comment by cbrisboi** [comment]
Since root_numpy is only for file io, this would be (to my mind) somewhat separate from the minimizers. It appears that in the threeML repo(rather than hawc_hal), the only place this code is used is in the VERITASLike plugin, although I am not taking responsibility for that plugin, as I am not a member of VERITAS.

**Comment by grburgess** [comment]
So this is not the same thing?

https://github.com/threeML/threeML/blob/master/threeML/minimizer/ROOT_minimizer.py#L3

**Comment by cbrisboi** [comment]
No, thats using `ROOT`, rather than `root_numpy`
See https://github.com/threeML/threeML/blob/master/threeML/io/cern_root_utils/tobject_to_numpy.py#L2

**Comment by grburgess** [comment]
Aha! Well, I'm all fine with it, but @ndilalla just did all the root stuff, so he should chime in.

**Comment by ndilalla** [comment]
I am all in for getting rid of `root_numpy` and using `uproot`. @cbrisboi do you know which requirements this new package has?

**Comment by cbrisboi** [comment]
On _github_, the only strict dependency is numpy, although if going through conda, which I suspect is preferred, the dependencies are ( using `conda info uproot=4.0.0` and then copying the dependencies for python 3.7):

```
dependencies:
    awkward >=1
    lz4
    python >=3.7,<3.8.0a0
    python-xxhash
    python_abi 3.7.* *_cp37m
    uproot-base
    xrootd
    zstandard
```

**Comment by grburgess** [comment]
Wow. This package is amazing.

**Comment by grburgess** [comment]
@cbrisboi will there be any progress on this? Otherwise, we need to go ahead and close or assign someone else.
