### ISSUE TITLE
Couldn't import plugin FermiLATLike

### ISSUE THREAD

**Issue by rahulc157** [threeML/threeML#405]
Is FermiLATLike plugin has been removed from latest version of threeML?

output of get_available_plugins()

Available plugins:

SwiftXRTLike for Swift XRT
FermipyLike for Fermi LAT (with fermipy)
OGIPLike for All OGIP-compliant instruments
SpectrumLike for General binned spectral data
UnresolvedExtendedXYLike for n.a.
PhotometryLike for Generic photometric data
DispersionSpectrumLike for General binned spectral data with energy dispersion

**Comment by grburgess** [comment]
Is this a fresh install of fermitools? The latest fermitools are broken and thus it may show the plugin is not there because of that.

**Comment by rahulc157** [comment]
Yes I just installed the fermitools using conda create -n fermi -c conda-forge -c fermi fermitools python=3.

Now even kernal is not working, showing some library issue /envs/fermi/lib/libRIO.so: : undefined symbol: _ZN13TStreamerBase13InitStreamingEb. 

I installed the threeML using 
bash ./install_3ML.sh --with-fermi --python 3.7 --with-xspec -env-name threeML

What to do, I need to work with LAT data within threeML?

**Comment by grburgess** [comment]
@rahulc157 open and issue here: https://github.com/fermi-lat/Fermitools-conda/issues

there are some work around for the issue, or you can downgrade fermitools manually to a version that is working.

**Comment by rahulc157** [comment]
Hi,
I have downgraded the fermitools but I still could not get the FermiLATLike plugin.  Can you please suggest further?

**Comment by henrikef** [comment]
@rahulc157 Could you try a clean install, using the newest fermitools version 2.0.8 released today: https://github.com/fermi-lat/Fermitools-conda/wiki/Release-Notes

**Comment by grburgess** [comment]
@rahulc157 there has been some progress on fermipy and it should be working soon.
