### ISSUE TITLE
Use of xspec model

### ISSUE THREAD

**Issue by mingjiac** [threeML/threeML#408]
How to use xspec model in 3ML?

**Comment by grburgess** [comment]
@mingjiac  If you have xspec installed and initialized  when you build / install astromodels, it will automatically create the link for using xspec models. You will see the messaging for this upon install. 

### Usage

To use the models, just follow the steps here: 
https://threeml.readthedocs.io/en/latest/notebooks/xspec_models.html

### Note:

The sometimes does not work, so if you run into issue let me know and we will try to solve this corner case.

**Comment by mingjiac** [comment]
> @mingjiac If you have xspec installed and initialized when you build / install astromodels, it will automatically create the link for using xspec models. You will see the messaging for this upon install.
> 
> ### Usage
> To use the models, just follow the steps here:
> https://threeml.readthedocs.io/en/latest/notebooks/xspec_models.html
> 
> ### Note:
> The sometimes does not work, so if you run into issue let me know and we will try to solve this corner case.

Thank you very much for your reply! Follow the above tutorial to run an error

from astromodels.xspec.factory import *

Loading xspec models...
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-19-859e515958d6> in <module>
----> 1 from astromodels.xspec.factory import *

~/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/xspec/__init__.py in <module>
----> 1 from .factory import *

~/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/xspec/factory.py in <module>
    663 # This will either work or issue a warning if XSpec is not available
    664 
--> 665 new_functions = setup_xspec_models()
    666 
    667 # Now import the new classes in the local namespace (if any)

~/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/xspec/factory.py in setup_xspec_models()
    631     sys.stdout.write("Loading xspec models...")
    632 
--> 633     all_models = get_models(find_model_dat())
    634 
    635     for (model_name, xspec_function, model_type) in all_models:

~/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/xspec/factory.py in find_model_dat()
     73     # Check that model.dat exists
     74 
---> 75     assert os.path.exists(final_path), "Cannot find Xspec model definition file %s" % (final_path)
     76 
     77     return os.path.abspath(final_path)

AssertionError: Cannot find Xspec model definition file /home/cjm/miniconda3/lib/Xspec/spectral/manager/model.dat

**Comment by grburgess** [comment]
when you installed XSPEC, did it give you a message that it found xspec?

**Comment by grburgess** [comment]
@mingjiac 


        print("\n Xspec is detected. Will compile the Xspec extension.\n")
        print("\n NOTICE!!!!!\n")
        print("If you have issues, manually set the ENV variable XSPEC_INC_PATH")
        print("To the location of the XSPEC headers\n\n")
        print("If you are still having issues, unset HEADAS before installing and contact the support team")

**Comment by grburgess** [comment]
You also much have heainit set when using the models.

**Comment by mingjiac** [comment]
> when you installed XSPEC, did it give you a message that it found xspec?

I used the command "conda install -c xspecmodels xspec-modelsonly" to install, and it can be found in the "conda list" after the installation is successful.

**Comment by grburgess** [comment]
I am doing some tests... this looks like a bug.

**Comment by grburgess** [comment]
@mingjiac There is an update and it should now work. could you please update your version of astromodels?

**Comment by mingjiac** [comment]
> @mingjiac There is an update and it should now work. could you please update your version of astromodels?

Thanks for your help! The problem has been solved and it can be used normally.

**Comment by grburgess** [comment]
Glad to help!
