### ISSUE TITLE
Background normalization as nuisance parameters in FermipyLike plugin

### ISSUE THREAD

**Issue by henrikef** [threeML/threeML#434]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Normalization of the isotropic and diffuse background templates in the fermipy plugin. It should be possible to allow them to vary during the fit.

**Describe the solution you'd like**

Background normalization should be implemented as nuisance parameters as it is in the FermiLATLike plugin.

**Describe alternatives you've considered**

Alternative would be to make users fit the background norm externally, but that doesn't always produce consistent results.

**Comment by grburgess** [comment]
Was this added in any of the new PRs?
