### ISSUE TITLE
emcee version incompatibility with naima

### ISSUE THREAD

**Issue by henrikef** [threeML/threeML#435]
(Not a "bug" but this was the closest template)

**Describe the issue**

The [naima](https://github.com/zblz/naima/blob/master/setup.py#L17) modeling package requires `emcee>=2.2.0,<3.0` , [threeML](https://github.com/threeML/threeML/blob/master/setup.cfg#L35) requires `emcee>=3` 😞 

(I can confirm that threeML tests fail with `emcee-2.2.1`. I'll try `naima` + `emcee-3.0.2` as a workaround as I just want to use their modeling, not the sampler. Also, the way forward here is probably to make naima compatible with more recent versions of emcee, not to make threeML backward compatible with older versions of emcee.)

**Comment by henrikef** [comment]
See https://github.com/zblz/naima/issues/194

**Comment by grburgess** [comment]
Yeah, or they could drop the unfolded model fitting in their code which is not needed...
