### ISSUE TITLE
fermipy doc failing during fit. 

### ISSUE THREAD

**Issue by grburgess** [threeML/threeML#436]
**Describe the bug**

This line is failing in the Fermipy documentation fitting:

https://github.com/threeML/threeML/runs/2092912814?check_suite_focus=true#step:9:111

**To Reproduce**

Run the fermipy_lat.md doc in the docs folder

**Expected behavior**

the fit should not fail?

**Screenshots**

See link above to actions. 

**Desktop (please complete the following information):**

github actions.

**Additional context**
hey... the fermipy seems to be working again!

**Comment by henrikef** [comment]
Hm. I've been poking around a bit. This is what I've found so far:

* It's not a problem with the fit/minimizer. ThreeML's `FermipyLike.get_log_like()` (which is essentially a wrapper for Fermipy's `gta.like.logLike.value()` ) returns a `nan` value, even before the first fit step.
* The problem goes away if we consider smaller search radii for the LAT catalog (18 degrees or smaller). **As a workaround, use `ra, dec, table = lat_catalog.search_around_source("Crab", radius=18.0)` in the second cell.**
* I suspect something goes wrong with one of the sources when translating from 4FGL to astromodels and back to fermipy. I'll try to see if I can figure out which one (or if there's a different problem).

**Comment by henrikef** [comment]
Ok. I think I tracked the issue down to one source, `PSR_J0622p3749`.

Calling `model.remove_source("PSR_J0622p3749")` before assigning the model makes the fit work.

For reference, this is how I identified the source causing issues:

```
for point_source in list(model.point_sources.values()):
    print (point_source.name )
    dnde = point_source(LAT._pts_energies)  # ph / (cm2 s keV)
    dnde_MeV = dnde * 1000.0  # ph / (cm2 s MeV)
    print(dnde_MeV)
    LAT._gta.set_source_dnde(point_source.name, dnde_MeV, update_source = True)
```
The output for the source in question was 

```
PSR_J0622p3749
[2.04284409e-010 2.00926199e-010 1.97391981e-010 1.93618004e-010
 1.89522716e-010 1.85002655e-010 1.79928089e-010 1.74139022e-010
 1.67442742e-010 1.59615071e-010 1.50408823e-010 1.39574733e-010
 1.26901823e-010 1.12284436e-010 9.58196654e-011 7.79221903e-011
 5.94330781e-011 4.16229112e-011 2.60199115e-011 1.39828147e-011
 6.14478622e-012 2.06583254e-012 4.86180599e-013 7.11971368e-014
 5.54411082e-015 1.86256865e-016 2.04303441e-018 5.05565420e-021
 1.72340330e-024 4.19485414e-029 3.04927157e-035 2.06853441e-043
 2.78076378e-054 9.48452408e-069 5.28480489e-088 1.25236934e-113
 9.75049395e-148 3.93702518e-193 1.50503452e-253 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000]

Failed to create spline:  [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan] [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan]
Failed to create spline:  [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan] [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan]
 ```
 
 `Failed to create spline` is from fermipy.utils.get_parameter_limits() which is called for example from `gtanalysis.get_src_model`. So something is wrong with this source, but I'm stumped on what exactly the problem is. @omodei any ideas?

**Comment by henrikef** [comment]
I wonder if having 0 predicted flux in some energy bins is a problem. Maybe we can try setting it to some small number, e.g. `1e-300`, instead?

**Comment by henrikef** [comment]
👊 

Docs are building now, still getting some conda errors.

**Comment by grburgess** [comment]
Thanks!
