### ISSUE TITLE
fermitools and python 3.8 in the CI tests

### ISSUE THREAD

**Issue by henrikef** [threeML/threeML#444]
**Describe the issue**

We're getting tons of conflicts in the python 3.8 tests, e.g. https://github.com/threeML/threeML/pull/442/checks

Turns out, the fermitools require python 3.7: https://github.com/fermi-lat/Fermitools-dependencies/blob/master/meta.yaml#L32 

Can we fix the tests/CI environment so that we only try to install fermitools/fermipy when testing python 3.7 ?

**To Reproduce**
Look at the logs: https://github.com/threeML/threeML/pull/442/checks

**Expected behavior**
I expected the tests not to crash all the time.

**Comment by omodei** [comment]
Yes, fermitools should only be tested on 3.7. We are changing the workflow (not sure why python was bumped up to 3.8...)

**Comment by ndilalla** [comment]
With the new fix the master is now building correctly. @henrikef could you try merging the master on your branch to see if it works?
