### ISSUE TITLE
OverflowError when positive error is inf

### ISSUE THREAD

**Issue by jasonfan1997** [threeML/threeML#451]
**Describe the bug**
I got some customized plugin and require to run some background trials(meaning no signal). Under this case the error from the MLEResults will be inf sometime. Then when it tries to display the result, the uncertainty_formatter in io will just throw a OverflowError: cannot convert float infinity to integer 
Getting the dataframe is fine but it is the display() that tries to format the result cause this error.

**To Reproduce**
I don't have a good way to reproduce it.
But I think if you get the result table and then manually set the error(or any number to inf or NaN) in the dataframe, you will see the error when displaying it.
![Capture](https://user-images.githubusercontent.com/20786734/113085750-67fe7b00-91ae-11eb-83cb-f624759d42df.PNG)
![2](https://user-images.githubusercontent.com/20786734/113085753-67fe7b00-91ae-11eb-84b0-202fe169ce7f.PNG)

**Comment by grburgess** [comment]
@jasonfan1997 this should be fixed now. If you still have issues, please reopen.
