### ISSUE TITLE
OGIPLike won't accept background model

### ISSUE THREAD

**Issue by domeckert** [threeML/threeML#460]
Hi everyone,

I attempted to model the background of an XMM spectrum and pass the background model to an OGIPLike object as described in [this tutorial](https://threeml.readthedocs.io/en/latest/notebooks/Background_modeling.html#Using-a-profile-likelihood). However, when trying load "background_plugin" instead of a background file, I get the following error:

![image](https://user-images.githubusercontent.com/47885645/117942961-ebfa6580-b30b-11eb-812b-a011b88e35d0.png)

I'm on Ubuntu 20.04 with Python 3.8 and threeML 2.2.1

I did the same thing a few months ago and it was working fine, albeit slowly. Has something changed in the meantime?

**Comment by grburgess** [comment]
@domeckert the fix is in the master branch, and will be pushed to pypi in the next release. Let me know if there is still an issue.

**Comment by domeckert** [comment]
Fixed. Thanks a lot @grburgess
