### ISSUE TITLE
Can threeML &HAL plot tsmap and do morphology ?

### ISSUE THREAD

**Issue by jlzhang001** [threeML/threeML#466]
## Data Analysis Question
I am using HAL with HAWC crab data which is supported by HAWC website. I want to plot the tsmap with ROI 3degree. How to do it? and is there routines to do morphology?

**Comment by cbrisboi** [comment]
Hi @jlzhang001! 

There is not yet a routine to plot a TS map in hal. It is a feature that came up a couple of months ago in a discussion I had with @hayalaso, although we did not implement it at that time. I do agree however that we should probably have a feature like it in hal. 

When you say "routines to do morphology" can you be a little more specific? If you mean trying to see if (for example) a particular source is extended or not, you can specify that when you define your model. I have attached below a really simple example of defining an extended source assuming a gaussian morphology. I hope that helps! If not, maybe you can rephrase your question.

```
ra_example = 83.63
dec_example = 22.02

spectrum = astromodels.Powerlaw()
shape = astromodels.Gaussian_on_sphere()
source = threeML.ExtendedSource("example", spatial_shape=shape, spectral_shape=spectrum)

spectrum.index.value  = -2.5
spectrum.index.bounds = (-5.0 , -0.5)
spectrum.index.fix    = False

spectrum.K.value      = 7.9e-24 
spectrum.K.bounds     = (1e-35 , 1e-10) 
spectrum.K.fix        = False

spectrum.piv.value    = 7.0 * astropy.u.TeV
spectrum.piv.fix      = True

shape.lon0.value     = ra_example  * astropy.u.degree
shape.lat0.value     = dec_example * astropy.u.degree
shape.lon0.fix       = True
shape.lat0.fix       = True

shape.sigma.value.   = 1.0 * astropy.u.degree
shape.sigma.bounds.  = (0.2, 20.0)
```

**Comment by jlzhang001** [comment]
I am tring to compute TS for each pixel of the ROI, then I can plot TS map. But It's not convenient and time costing.

For the morphology​, that's I need.

**Comment by cbrisboi** [comment]
Yes. Doing it manually by setting new models at each location is very time consuming. I think we need to carefully consider how to approach a "fast" version, which would specifically fit a model at each location

**Comment by henrikef** [comment]
I think Colas worked on this a while back (when HAL was still a 👶 ) and found that it was very slow. You might be able to find some (internal) presentations still @cbrisboi. Also, HAL is faster now than it was at that time.

**Comment by grburgess** [comment]
Is there any update on this @cbrisboi @henrikef @jlzhang001 ?
