### ISSUE TITLE
XSPEC models cannot be retrieved by load_analysis_results

### ISSUE THREAD

**Issue by xboluna** [threeML/threeML#473]
XSPEC models provided by xspec-modelsonly aren't initialized through FunctionMeta in function.py and thereby are not added to the _known_functions dictionary. This dictionary is used to assemble the expression of a saved analysis_results in load_analysis_results (which is done through get_function in function.py).

1. Create a model which includes XSPEC functions (composite or otherwise)
2. Run a fit
3. Save results object as .fits using analysis_results.write_to()
4. Use load_analysis_results() to recover results object -- [error occurs because XSPEC function is not found in _known_functions](https://github.com/threeML/astromodels/blob/225b0cf68b716138b418ef615aab454d31da25f5/astromodels/functions/function.py#L1790)

Example of returned error:
`in _parse_function_expression
    "probably missing the data file" % (unique_function, function_specification))
astromodels.functions.function.UnknownFunction: Function XS_diskbb in expression (TbAbs{1} * XS_diskbb{2}) is unknown. If this is a template model, you are probably missing the data file`

**Comment by grburgess** [comment]
Hi @xboluna quick question. You do have xspec initialized when you reload the model?

**Comment by grburgess** [comment]
@xboluna I just added a new test in a branch of astromodels that should cover this issue:

https://github.com/threeML/astromodels/pull/164/files

So in principle it should be ok..

**Comment by xboluna** [comment]
> Hi @xboluna quick question. You do have xspec initialized when you reload the model?

Oops! This was my mistake -- I had thought it would initialize with `from astromodels import *`. Thanks for looking into this!

**Comment by grburgess** [comment]
No worries @xboluna this was a good test to add in astromodels. You never know when something else might make this fail.
