### ISSUE TITLE
Obtain light curve

### ISSUE THREAD

**Issue by mingjiac** [threeML/threeML#474]
Hi! Can 3ML obtain the light curve of a specific energy channel?

**Comment by grburgess** [comment]
@mingjiac in principle yes, but the feature is not integrated into he code yet. it is possible that @BjoernBiltzinger has some code to do this. 

Alternatively, a pull request to add this would always be welcome!

**Comment by grburgess** [comment]
@mingjiac there is now the ability to do this in the master branch thanks to @BjoernBiltzinger This will be merged into the next release. You can install this version from GitHub though.
