### ISSUE TITLE
Compatibility with empirical or PCA-based BXA background

### ISSUE THREAD

**Issue by kchoX14** [threeML/threeML#476]
Hi. After going through the threeML webpage, I find that having a joint fit (OGIP-like plugin) with background and source+background spectra is more common because I could not locate empirical models that can be directly constructed for mission-specific data in the X-rays (like XMM Newton, NuSTAR, Suzaku, Swift or Chandra). This is available over BXA, which provides both empirical models [(https://johannesbuchner.github.io/BXA/background-models.html)](https://johannesbuchner.github.io/BXA/background-models.html) and PCA-based background models ([https://johannesbuchner.github.io/BXA/pca-background-models](https://johannesbuchner.github.io/BXA/pca-background-models)). 

The backgrounds computed as such are quite accurate, and allow XSPEC-like _atables_ (in FITS format) to be used for modeling the background separately, while the source spectrum is analyzed independently. Given that threeML requires no assumption of the likelihood (unlike XSPEC or BXA), is empirical modeling still advised? If yes, can BXA empirical/PCA backgrounds be used over threeML? 

NOTE:  BXA recommends AIC for Bayesian model comparison, alongside evidence Z (in logarithm units). How much is the discrepancy if AIC is used, given it has a frequentist base?

**Comment by grburgess** [comment]
In theory yes, there is a way to have background models: https://threeml.readthedocs.io/en/stable/notebooks/Background_modeling.html#Modeling-the-background

If the format for the background can be specified, then we can help you to include these into 3ML (or astromodels.) Please let me know exactly what you would like to do and we can extend the functionality if it is not already there. 


On AIC: The AIC is a very strict form of information criteria that is only applicable for point estimates and should not be used with bayesian posteriors as it makes many assumption about the form on the model and asymptotics. Moreover, AIC is a predictive check for M-open statistics where the marginal likelihood ( or evidence in astronomy) is a tool for M-closed model comparison. Thus, it is not a good idea to use AIC when your fit is estimated in a bayesian framework see: 
https://twitter.com/avehtari/status/1406990096574955526?s=20

for a summary.

When using information criteria, this paper explains a lot about how they are all derived, each with an increasing set of assumptions:

https://link.springer.com/article/10.1007/s11222-013-9416-2

**Comment by kchoX14** [comment]
> In theory yes, there is a way to have background models: https://threeml.readthedocs.io/en/stable/notebooks/Background_modeling.html#Modeling-the-background
> 
> If the format for the background can be specified, then we can help you to include these into 3ML (or astromodels.) Please let me know exactly what you would like to do and we can extend the functionality if it is not already there. 
> 
> 
> On AIC: The AIC is a very strict form of information criteria that is only applicable for point estimates and should not be used with bayesian posteriors as it makes many assumption about the form on the model and asymptotics. Moreover, AIC is a predictive check for M-open statistics where the marginal likelihood ( or evidence in astronomy) is a tool for M-closed model comparison. Thus, it is not a good idea to use AIC when your fit is estimated in a bayesian framework see: 
> https://twitter.com/avehtari/status/1406990096574955526?s=20
> 
> for a summary.
> 
> When using information criteria, this paper explains a lot about how they are all derived, each with an increasing set of assumptions:
> 
> https://link.springer.com/article/10.1007/s11222-013-9416-2
> 
> 
> 
> 
> 
> 
> 
> 
> 

The background modeling over threeML currently treats the background just like any spectrum and required modeling similarly. On the contrary, BXA provides backgrounds (empirical and PCA-based) for specific missions. There are JSON files that take care of the detector information.

I guess my requirement here would depend on whether it is more advisable to have the background modeled separately over threeML or treat it like Wstat (on XSPEC) does with a joint probability. BXA recommends the former, but there are plotting issues there. BXA also isn't catered to multiple instruments/spectra. Either way, I'll be using UltraNest (Bayesian) for the currenr-best optimization, sampling and speed available. So... what'd you recommend on that???

On a separate note, BXA creates MCMC chain FITS files (like those on XSPEC) so that one may feed them back on Xspec and do some simple checks. Does threeML allow that? If corner plots are being made, there should be a chain file somewhere where the samples are being drawn from, right?


**On AIC**:  It then just complicates model selection and comparison, compared to what papers using BXA have recently been doing (using AIC with logZ for the same), doesn't it? PPC will only get crowded in the end for multiple instruments. BIC and DIC are not prudent choices either. What other alternative do we have then???

**Comment by grburgess** [comment]
> > In theory yes, there is a way to have background models: https://threeml.readthedocs.io/en/stable/notebooks/Background_modeling.html#Modeling-the-background
> > If the format for the background can be specified, then we can help you to include these into 3ML (or astromodels.) Please let me know exactly what you would like to do and we can extend the functionality if it is not already there.
> > On AIC: The AIC is a very strict form of information criteria that is only applicable for point estimates and should not be used with bayesian posteriors as it makes many assumption about the form on the model and asymptotics. Moreover, AIC is a predictive check for M-open statistics where the marginal likelihood ( or evidence in astronomy) is a tool for M-closed model comparison. Thus, it is not a good idea to use AIC when your fit is estimated in a bayesian framework see:
> > https://twitter.com/avehtari/status/1406990096574955526?s=20
> > for a summary.
> > When using information criteria, this paper explains a lot about how they are all derived, each with an increasing set of assumptions:
> > https://link.springer.com/article/10.1007/s11222-013-9416-2
> 
> Before I begin commenting, I see you've tagged this post with "Spectrum-like" plugin. But if I have src+bkg spectrum, a bkg spectrum, RMF file and ARF file (all loaded in like in XSPEC), shouldn't that be an "OGIP-like" case instead?

@kchoX14  OGIPLike is a subclass of spectrum like which is just an interface that reads in the observed spectrum, background spectrum,  response and arf files. The underlying likelihood is the same. 


> 
> The background modeling over threeML currently treats the background just like any spectrum and required modeling similarly. On the contrary, BXA provides backgrounds (empirical and PCA-based) for specific missions. There are JSON files that take care of the detector information. This is an ideal environment for background-independent modeling of the source spectrum, where the background is taken care of with precision, it's errors minimized, and the source can be modeled without much fuss.

The background modeling for the OGIP/SpectrumLike plugins depends on the how the input data are distributed. If there is no background model specified, then profile likelihoods are used. If a background model is used, then the full, appropriate likelihood is used. In the case of the empirical (analytically specified models?) that you mention, these would just be treated as spectral models with parameters to be optimized. If I understand correctly, the PCS models are essentially templates with a normalization parameter. These are also spectral models and could be wrapped with astromodels' template model class. 


> 
> I guess my requirement here would depend on whether it is more advisable to have the background modeled separately over threeML or treat it like Wstat (on XSPEC) does with a joint probability. BXA recommends the former amd also allows for the latter case. But there are plotting issues there. BXA also isn't catered to multiple instruments/spectra. Either way, I'll be using UltraNest (Bayesian) for the currenr-best optimization, sampling and speed available. So... what'd you recommend on that???

I think the above should answer the first part of the question. There are several Bayesian posterior samplers available in 3ML including Ultranest. They all provide a common interface with setup functions to specify algorithm dependent parameters. After a fit, the posterior samples are stored in the [AnalysisResults](https://threeml.readthedocs.io/en/stable/notebooks/Analysis_results_showcase.html#Bayesian-Analysis-Results) object which can be saved to disk. This class provides corner plotting etc. There are examples in the documentation that show different ways to interface with this object. 


> 
> On a separate note, BXA creates MCMC chain FITS files (like those on XSPEC) so that one may feed them back on Xspec and do some simple checks. Does threeML allow that? If corner plots are being made, there should be a chain file somewhere where the samples are being drawn from, right?

See above.

> 
> **On AIC**: It then just complicates model selection and comparison, compared to what papers using BXA have recently been doing (using AIC with logZ for the same), doesn't it? PPC will only get crowded in the end for multiple instruments. BIC and DIC are not prudent choices either. What other alternative do we have then???

This is an area of open research in statistics.... its not always an easy topic. The above linked references go deeply into the topic.

**Comment by kchoX14** [comment]
“If I understand correctly, the PCA models are essentially templates with a normalization parameter. These are also spectral models and could be wrapped with astromodels' template model class.”

@grburgess I'd love to understand this part bettwr on how to use that template class. The PCA-based background models are all internally some powerlaw of flatter continuum withultiple Gaussians that are attempted over the background spectrum. The best model is internally stored, and all that appears in the _atable_ FITS model over XSPEC is with two parameters (whether it is a source or not, and the normalization). This is kept fixed in thw modeling with unit norm, while the source+background spectrum is being fit on BXA.

**Comment by kchoX14** [comment]
“This is an area of open research in statistics.... its not always an easy topic. The above linked references go deeply into the topic.”

@grburgess in the meantime then, what is the best practice one should follow in order to ensure model selection and comparison don't get compromised? Without the ∆AIC or a QQ-like (but cleaner) visual process for the goodness-of-fit beyond the MCMC bootsrapping allowed, I'm left with looking at the Bayes factors across models, differences in the log of evidences, and crowded PPC visualizations (with multiple spectra).

**Comment by grburgess** [comment]
For the PCA models, it seems one could create these models in astromodels: https://threeml.readthedocs.io/en/stable/notebooks/spectral_models.html#Building-Custom-Models

fix there parameters to what is required and only free the normalization. 


I believe reading the above references will give you more insight into model selection.
