### ISSUE TITLE
Residual Plots, Local Models, Source Positioning

### ISSUE THREAD

**Issue by kchoX14** [threeML/threeML#477]
**Residuals:**
I can see the residual plots (bottom panels) are unbinned in the plot_counts command in the examples provided. Since threeML does not require specifying the data likelihood, it is not trivial for one to know how the residuals (in terms of sigma) are being calculated. All we've done so far is "_[data - model]/error_" with chisquared as the fit statistic (JointLikelihood). But that isn't correct for other likelihoods. So, kindly assist on drawing that information out over threeML. 

It'd also help to rebin just the residual plot to a certain significance (and print out just that plot information to a file for comparative plots outside threeML) to be able to check the features better. Do kindly mention how that is achieveable on threeML. 

**External Models**
I'd had hoped some feature parity between PyXspec and threeML, given XSPEC models can be used normally with just the "XS_" prefix. Then again, this says nothing about models that can be used on XSPEC with local configurations (e.g., REFLIONX and RELXILL reflection codes). How'd one do that?

**Source Position for _Model()_**
No matter what the analysis type is, a model needs to be specified in a very peculiar manner where the right ascension and declination of the object needs to be specified (presumably) inside the **Model** plugin. At times, this is simply both 0. If the OGIP-like files already contain the nominal, pointed and object locations on the sky, why is ra and dec even needed???

**Comment by grburgess** [comment]
> **Residuals:**
> I can see the residual plots (bottom panels) are unbinned in the plot_counts command in the examples provided. Since threeML does not require specifying the data likelihood, it is not trivial for one to know how the residuals (in terms of sigma) are being calculated. All we've done so far is "_[data - model]/error_" with chisquared as the fit statistic (JointLikelihood). But that isn't correct for other likelihoods. So, kindly assist on drawing that information out over threeML.

What is meant by unbinned? Which plot_counts cmd? 3ML chooses the likelihood based on the distribution of the data. The residuals computed are also based on the likelihood. For Gaussian likelihoods, indeed the residuals are data - model / data_uncertaintiy. But for other likelihoods, it is different and computed correctly for each case. 

> 
> It'd also help to rebin just the residual plot to a certain significance (and print out just that plot information to a file for comparative plots outside threeML) to be able to check the features better. Do kindly mention how that is achieveable on threeML.

Currently, one can specify ```min_rate``` in the residual plots to rebin the data. PRs for other options are welcome. Once a fit is performed, access to various quantities can be obtained through the individual plugins. If you can specify what quantities you need access to, we can provide further documentation / features to help.


> 
> **External Models**
> I'd had hoped some feature parity between PyXspec and threeML, given XSPEC models can be used normally with just the "XS_" prefix. Then again, this says nothing about models that can be used on XSPEC with local configurations (e.g., REFLIONX and RELXILL reflection codes). How'd one do that?

We currently only support the models that ship with XSPEC. One could rewrite local models in astromodel format. We are currently moving to have all XSPEC models rewritten in astromodels.


> 
> **Source Position for _Model()_**
> No matter what the analysis type is, a model needs to be specified in a very peculiar manner where the right ascension and declination of the object needs to be specified (presumably) inside the **Model** plugin. At times, this is simply both 0. If the OGIP-like files already contain the nominal, pointed and object locations on the sky, why is ra and dec even needed???

The position arguments are ignored if they are not required for fitting in a specific model or plugin. They are provided for plugins which depend on position. Thus, they default argument of 0,0 is fine for OGIP plugins.

**Comment by kchoX14** [comment]
“We currently only support the models that ship with XSPEC. One could rewrite local models in astromodel format. We are currently moving to have all XSPEC models rewritten in astromodels.”

@grburgess this'll be a problem for testing fits with standalone models that are still in active phase of development. I'd request a way to have them included over threeML, since they can be read into XSPEC at will. This'll be an essential flexibility added to threeML, which BXA allows by-default. Many of the new, innovative models that come out are more on Github these days than incorporated within XSPEC. Just ensuring an optional wrapping feature over PyXspec could do the trick. It would also enable many PyXspec tasks to be run without hassle, all the while utilizing the finesse over threeML for the analysis amd visualization part.

**Comment by kchoX14** [comment]
“Currently, one can specify min_rate in the residual plots to rebin the data. PRs for other options are welcome. Once a fit is performed, access to various quantities can be obtained through the individual plugins. If you can specify what quantities you need access to, we can provide further documentation / features to help.”


@grburgess  that is much appreciated. I'd request aid on the following quantities:

1. Computing the equivalent width of a model component and the luminosity.
2. How to set the stepping size in the parameter space for a model parameter, between it's boundaries? Current examples deal with just setting the limits.
3. Allowing to use the corner.py module somehow within threeML to modify the beautuful corner plots and required.
4. Going back after the analysis to check false prediction and false selections of models.
5. Some form of Bayesian prior-to-posterior gain check on information, like the Kullback-Leibler divergence? Also, listing how many kinds of priors are allowed currently over threeML.
6. More descriptive examples on the use of certain cases like the Minuit local optimizer over the implementation of a sampler. This is usually unnecessary to undertake if UltrNest is used, given MLFriends is a global optimizing algorithm with nested sampling using sequential Monte Carlo.


(...I do not recall further needs. But I will mention them as the need arises...)

**Comment by kchoX14** [comment]
“But for other likelihoods, it is different and computed correctly for each case.”

@grburgess  I'd request you to pint me to the correct file within the threeML distribution that computes the residuals based on the likelihood approximated on the data within the code. I'd like to see the functional form of the calculation. Thanks!

**Comment by grburgess** [comment]
@kchoX14 re: local models. At the current time there is no plan to implement his feature as it requires work beyond our current scope.  While XSPEC and many of its wrappers such as BXA or emcee-xspec are interfaces to XSPEC, we are focused our own modeling language which can accommodate most if not all of these models forms. We always welcome contributions from the community which could add this functionality. In addition @domeckert has been crucial to interfacing some of XSPEC's model functionality and may have more insight. 

Some of the issues requested above are in the documentation. For specific examples of how to setup optimization algorithms, we refer you to those packages.


The file that computes the Poisson residuals is here: https://github.com/threeML/threeML/blob/master/threeML/utils/statistics/stats_tools.py#L112

**Comment by kchoX14** [comment]
> @kchoX14 re: local models. At the current time there is no plan to implement his feature as it requires work beyond our current scope.  While XSPEC and many of its wrappers such as BXA or emcee-xspec are interfaces to XSPEC, we are focused our own modeling language which can accommodate most if not all of these models forms. We always welcome contributions from the community which could add this functionality. In addition @domeckert has been crucial to interfacing some of XSPEC's model functionality and may have more insight. 
> 
> Some of the issues requested above are in the documentation. For specific examples of how to setup optimization algorithms, we refer you to those packages.
> 
> 
> The file that computes the Poisson residuals is here: https://github.com/threeML/threeML/blob/master/threeML/utils/statistics/stats_tools.py#L112
>  

Ok. I will eagerly wait to hear from @domeckert on how to use local XSPEC models over threeML. 

Thanks for the file. I'll into it. But how do I write off just the residual plot information (not the whole AnalysisResults) into a file to manipulate as needed outside threeML?

**Comment by domeckert** [comment]
@kchoX14 I have never tried to call XSPEC local models from 3ML, however if they are local models then I suppose they can be easily implemented in astromodels directly. I can see several possible cases:

1) Analytical model: this should be trivial to port natively to astromodels 
2) Table model: convert the table into HDF5 format and load it into 3ML as a table model 
3) Numerical model: if the code is in Python it should be easy, if not then you will need to use something like boost  python to compile in its native language and call it from Python. More cumbersome but doable. 

I'm currently on vacation but will be back to work next week, if needed I can send you some examples

**Comment by kchoX14** [comment]
@domeckert Examples would be lovely... thank you! No. 2 will surely be required because we require atable a mtable FITS warm absorbers made over XSTAR quite often. And yes, I'll have to arrange my numerical codes (ray tracing and radiative transfer) there, and they're already in C.
