### ISSUE TITLE
BIC and DIC, which one should I use to judge?

### ISSUE THREAD

**Issue by wangchen66** [threeML/threeML#479]
## Data Analysis Question

The Bayes fitting results of  F model and F + G model are obtained by 3ml xspec. I judge whether there is G model by comparing the BIC or DIC of the two models. I found that in the fitting results of some time intervals, the judgment results of BIC and DIC are inconsistent. Sometimes, BIC increases and DIC decreases, or both declined. However, When using BIC  as the judgment basis is more in line with the expected results in all time slices.  It is not good for us to use DIC  as the basis for judgment, because DIC may still fall when BIC rises, and even abnormal values of DIC (DIC-63065.477534   PDIC-63380.865047)appear. Which one should I use to judge?

**Comment by grburgess** [comment]
Hi,

1) what is meant by 3ML xspec?

2) have a look at the discussion in #472

**Comment by wangchen66** [comment]
My handwriting is wrong. It should be 3ML. I'll check it.

**Comment by wangchen66** [comment]
My handwriting is wrong. It should be 3ML. I'll check it. Thank you.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "threeML/threeML"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月9日(星期一) 凌晨0:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [threeML/threeML] BIC and DIC, which one should I use to judge? (#479)





 
Hi,
  
 
what is meant by 3ML xspec?
 
 
 
have a look at the discussion in #472
 
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
