### ISSUE TITLE
Fermi-LAT plugins failing again

### ISSUE THREAD

**Issue by grburgess** [threeML/threeML#482]
**Describe the bug**
A clear and concise description of what the bug is. What data are you using and how was it obtained? Which plugin(s) are you using?

fermi LAT issues with ROOT

*NOTE:* This is for BUG reports and not questions about generic data analysis.

This is popping up in the doc builds

```
ImportError: dlopen(/usr/local/miniconda/envs/test_env/lib/fermitools/_pyLikelihood.so, 2): Library not loaded: @rpath/libCLHEP-2.4.4.1.dylib
153
  Referenced from: /usr/local/miniconda/envs/test_env/lib/fermitools/_pyLikelihood.so
154
  Reason: image not found
155
ImportError: dlopen(/usr/local/miniconda/envs/test_env/lib/fermitools/_pyLikelihood.so, 2): Library not loaded: @rpath/libCLHEP-2.4.4.1.dylib
156
  Referenced from: /usr/local/miniconda/envs/test_env/lib/fermitools/_pyLikelihood.so
157
  Reason: image not found
158

```

**Additional context**

**Comment by omodei** [comment]
This is related to the following issue: https://github.com/fermi-lat/Fermitools-conda/issues/107

**Comment by omodei** [comment]
This bug is fixed in the master of threeML (https://github.com/threeML/threeML/blob/9ed561cbe857b504a604cbede156cf7145fd9e83/install_3ML.sh#L291)
Can you check that the problem goes away when installing from the master?

**Comment by grburgess** [comment]
Thanks @omodei.  The failing part is in the test workflow which install things from conda. If I manually add the clhep version in the workflow, it seems to fix the issue. We can just set this back when the dev version of fermitools reaches release.
