### ISSUE TITLE
An error occurred while using the xspec model.

### ISSUE THREAD

**Issue by chenjiaming5821** [threeML/threeML#490]
The following error occurs when using the xspec model: 
    AssertionError: Trying to set x-unit with (keV), which is not energy.

**Comment by grburgess** [comment]
@chenjiaming5821 this is due to an update in astropy. It should be fixed in the latest release of astromodels. Please update from either pip or conda and let me know if that fixes the issue.

**Comment by chenjiaming5821** [comment]
> astromodels.

Thanks for your help. After upgrading astromodels, the problem was solved.
