### ISSUE TITLE
Problem with RSP2 files

### ISSUE THREAD

**Issue by wangchen66** [threeML/threeML#491]
Hi ! When I use 3ML  to process GRB 130427324, I encounter the following error. How should I solve them?

```python
_time_resolved_plugins = {}
for k,v in time_series.items():
    v.read_bins(d)
    time_resolved_plugins[k] = v.to_spectrumlike(from_bins=True)_

```
---------------------------------------------------------------------------
```python

RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_667/1566256467.py in <module>
      2 for k,v in time_series.items():
      3     v.read_bins(d)
----> 4     time_resolved_plugins[k] = v.to_spectrumlike(from_bins=True)

~/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/utils/data_builders/time_series_builder.py in to_spectrumlike(self, from_bins, start, stop, interval_name, extract_measured_background)
    818                 for i, interval in enumerate(tqdm(these_bins, desc="Creating plugins")):
    819 
--> 820                     self.set_active_time_interval(interval.to_string())
    821 
    822                     assert isinstance(

~/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/utils/data_builders/time_series_builder.py in set_active_time_interval(self, *intervals, **kwargs)
    255 
    256                 self._response = self._weighted_rsp.weight_by_counts(
--> 257                     *self._time_series.time_intervals.to_string().split(",")
    258                 )
    259 

~/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/utils/OGIP/response.py in weight_by_counts(self, *intervals)
    926     def weight_by_counts(self, *intervals) -> InstrumentResponse:
    927 
--> 928         return self._get_weighted_matrix("counts", *intervals)
    929 
    930     def _get_weighted_matrix(self, switch: str, *intervals) -> InstrumentResponse:

~/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/utils/OGIP/response.py in _get_weighted_matrix(self, switch, *intervals)
    943         for interval in intervals_set:
    944 
--> 945             weights += self._weight_response(interval, switch)
    946 
    947         # Normalize to 1

~/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/utils/OGIP/response.py in _weight_response(self, interval_of_interest, switch)
   1053             log.error("All weights are zero. There must be a bug in the exposure or counts computation")
   1054 
-> 1055             raise RuntimeError()
   1056 
   1057         # Check that the first matrix with weight > 0 has an effective interval starting at the beginning of

RuntimeError: 

```

**Comment by grburgess** [comment]
Hi @wangchen66 can you also include the output from the log? 

My first guess is that you are using a time range that is not covered by the **official** FSSC response or that the response is corrupt. Can you show the time ranges you supplied?

**Comment by wangchen66** [comment]
Yes. I provide you with the time range of GRB130427324.

**Slection: 5 - 30 ; Bkg.Slection: -285.42 - -41.67  and 381.25 - 500 .**

**Comment by grburgess** [comment]
@wangchen66 check the headers of the responses in the RSP2 files. It is possible that they have exposure = 0. This may also be in the spectral files. 

A full working example is needed to understand your problem

**Comment by grburgess** [comment]
BTW @wangchen66 I just released a new version of a tool that will build RSP2s for you. You can see instructions here: 
http://jmichaelburgess.com/gbm_drm_gen/notebooks/drm_gen_doc.html#Creating-RSP2-files

**Comment by wangchen66** [comment]
Thank you.

**Comment by wangchen66** [comment]
Thank you. I'm trying to use it to solve the problem.

**Comment by wangchen66** [comment]
Hi !   When using  **online_response_generator** , I have some questions. when I want to generate RSP2 of GRB151027166. 
Do I have to run both **Trigger data** and **Daily data** ?  Can I only chose **Trigger data** ?
Do I need to modify  **tstart** ,**tstop** and **delta_time** ?

**Comment by grburgess** [comment]
@wangchen66 If it is a GRB, then you only need the triggered data as a GRB produces (in nearly all cases) a trigger. 

The start, stop, and delta time are parameters you can modify for your use cases.
