### ISSUE TITLE
3ML analysis of GBM data

### ISSUE THREAD

**Issue by mingjiac** [threeML/threeML#492]
when I use 3ML to process GBM data, an error occurs at this step:

    ts_tte.set_active_time_interval("350-380")

NoMatrixForInterval                       Traceback (most recent call last)
<ipython-input-22-b3cc5e341085> in <module>
     11     ts_tte.view_lightcurve(300,400)
     12     time_series[det] = ts_tte
---> 13     ts_tte.set_active_time_interval("350-380")
     14 
     15     ts_tte.view_lightcurve(-60,400)

/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/utils/data_builders/time_series_builder.py in set_active_time_interval(self, *intervals, **kwargs)
    255 
    256                 self._response = self._weighted_rsp.weight_by_counts(
--> 257                     *self._time_series.time_intervals.to_string().split(",")
    258                 )
    259 

/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/utils/OGIP/response.py in weight_by_counts(self, *intervals)
    939     def weight_by_counts(self, *intervals) -> InstrumentResponse:
    940 
--> 941         return self._get_weighted_matrix("counts", *intervals)
    942 
    943     def _get_weighted_matrix(self, switch: str, *intervals) -> InstrumentResponse:

/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/utils/OGIP/response.py in _get_weighted_matrix(self, switch, *intervals)
    956         for interval in intervals_set:
    957 
--> 958             weights += self._weight_response(interval, switch)
    959 
    960         # Normalize to 1

/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/utils/OGIP/response.py in _weight_response(self, interval_of_interest, switch)
   1012             )
   1013 
-> 1014             raise NoMatrixForInterval()
   1015 
   1016         # Compute the weights

NoMatrixForInterval:

**Comment by mingjiac** [comment]
> @mingjiac try this: https://github.com/grburgess/gbm_rsp2_generator

"download_GBM_daily_data "and "get_official_location" failed to import.

**Comment by grburgess** [comment]
@mingjiac are you using the notebook locally or on the binder?

**Comment by chenjiaming5821** [comment]
> @mingjiac are you using the notebook locally or on the binder?

I use it locally.

**Comment by grburgess** [comment]
Please use the binder link.
