### ISSUE TITLE
Typo in threeML/plugins/SpectrumLike.py, Line 1105

### ISSUE THREAD

**Issue by rwiller** [threeML/threeML#497]
The line reads 
self._mask = self._observed_spectrum.qaulity.good

when it should be 
self._mask = self._observed_spectrum.quality.good

The typo prevents the quality selection from functioning correctly

**Comment by grburgess** [comment]
Thanks @rwiller for finding this! Would you mind making a pull request off a local branch to fix it?

**Comment by grburgess** [comment]
fixed in #498
