### ISSUE TITLE
unable to analyse LAT data

### ISSUE THREAD

**Issue by amitkumarror** [threeML/threeML#518]
I try to analyse LAT data but there is an issue about module missing name  "pyLikelihood"
I'm using Ubuntu 20.10

########################################################
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_4546/3728426006.py in <module>
----> 1 LAT = FermipyLike("LAT", config)
ModuleNotFoundError: No module named 'pyLikelihood'
########################################################

I've tried to install via pip and conda commands but its having issues like,
$ pip install pyLikelihood
ERROR: Could not find a version that satisfies the requirement pyLikelihood (from versions: none)
ERROR: No matching distribution found for pyLikelihood

**Comment by henrikef** [comment]
Did you install the fermi tools? See https://github.com/fermi-lat/Fermitools-conda/wiki/Installation-Instructions

You probably want to do something like 

```
conda install -c conda-forge -c fermi fermitools clhep=2.4.4.1
```

from inside the same environment you installed threeML (and fermipy) in.

**Comment by AstrophysicsAndPython** [comment]
Is it necessary to have fermitools installed when working with fermipy even if we're not doing likelihood analysis?

For example, I have a PHA, BAK, and RSP file for LAT data from a previous likelihood analysis performed with Fermitools, I would now like to do the spectral fitting for GBM+LAT data in threeML. Is it still mandatory to have fermitools installed along with FermiPy?

**Comment by grburgess** [comment]
@AstrophysicsAndPython You could use the OGIPLike plugin to read those data... but this is not recommended as it can have a significant impact on the sensitivity and ability to resolve the spectral shape at high-energy see: https://iopscience.iop.org/article/10.3847/1538-4357/aad6ea 

In fact, this was the motivating reason to create 3ML. If there are issues with the install, there is also a docker which has the entire environment, but it is also built from the conda distribution.

**Comment by AstrophysicsAndPython** [comment]
If I'm understanding it correctly, it is better to perform the likelihood analysis through threeML itself and then analyze the data on the whole (GBM+LAT) rather than doing the likelihood analysis separately and then importing the data to threeML for analysis?

**Comment by amitkumarror** [comment]
Dear sir,
I have tried this but the kernel is keep dying whenever I import threeML
while working with the Jupiter notebook

without fermitools, it works properly, but I can't import pylikelihood

**Comment by grburgess** [comment]
@amitkumarror Did you follow the instructions posted by @henrikef ?

**Comment by amitkumarror** [comment]
Yes, I did.
whenever I installed fermitools with in threeML environment it creat
problem, i.e I can't import threeML after that.

**Comment by henrikef** [comment]
@amitkumarror What happens when you try to `import threeML`? Please try `python -c "import threeML"` from the command line and paste the output here. 

You do need the fermitools and fermipy installed if you want to use the fermipyLike plugin.

**Comment by omodei** [comment]
Also, did you use the installer script to install all the packages in the same environment? 
`bash install_3ML.sh --with-fermi `
in this way conda will try to create the environment staffing all the decencies at one.

**Comment by AstrophysicsAndPython** [comment]
@omodei I will try this since every time I install threeML with fermitools one of the two breaks down. I got it working somehow after three tries yesterday but it gives off too many warnings in my Spyder outside of 3ML warnings. I will try the script method today.

**Comment by AstrophysicsAndPython** [comment]
@grburgess Thank you, I will try that out as well.

**Comment by grburgess** [comment]
@AstrophysicsAndPython conda has slowed down a lot over the years. It is possible to use mamba which results in some speedups. The Spyder warnings could be from environments. 3ML is really focused on script and the Jupyter environment.

**Comment by omodei** [comment]
Is this issue solved?
