### ISSUE TITLE
Unable to install threeML using the install_3ML.sh script

### ISSUE THREAD

**Issue by ShabnamIyyani** [threeML/threeML#520]
I tried a number of times to install 3ML using the install_3ML.sh script  on MacOS Monterey version 12.0.1. 
I get the following output

Options:
--------
Installing xspec:                              yes
Installing root:                               no
Installing fermi:                              yes
Batch execution (assume yes to all questions): yes
Python version:                                3.7
Conda environment name:                        threeML

Running on osx

###############################################

Installing/checking Conda installation

###############################################

Found an already existing installation of conda in /Users/shabnam/opt/anaconda3

###############################################

Installing 3ML

###############################################

Warning: 'defaults' already in 'channels' list, moving to the top
Warning: 'threeml' already in 'channels' list, moving to the top
Warning: 'conda-forge' already in 'channels' list, moving to the top
Warning: 'xspecmodels' already in 'channels' list, moving to the top
Warning: 'fermi' already in 'channels' list, moving to the top
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.7.6) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

CondaValueError: invalid package specification: astromodels>=2 threeml>=2 iminuit>=2 h5py<=3.1.0 xspec-modelsonly=6.25 fermitools>=2 root=6.22.2 astropy=3.2.3 fermipy>=1 clhep=2.4.4.1

Please let me know how to proceed further.

**Comment by grburgess** [comment]
It is possible that there is a version mismatch with older astropy and the fermi tools. I personally do not like the install script because it can cause issues like this. the best way is to start with a clean environment and install the needed packages manually.

**Comment by ShabnamIyyani** [comment]
I tried installing using conda separately as suggested. 
While I try to install the xspec_models using the command 
conda install -c xspecmodels xspec-modelsonly
I get this warning 

(threeML) shabu@Shabnams-iMac ~ % conda install -c xspecmodels xspec-modelsonly
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for numpy uncertainties pyerfa python-dateutil ipykernel pymultinest


So, for the time being I aborted the installation of xspec_modelsonly. 

However, with the remaining installations done, when I import threeML in a jupyter notebook I get the following error

from threeML import *

[INFO    ] Starting 3ML!
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/var/folders/3f/1zr8mvls6r993_sq2spcy64w0000gp/T/ipykernel_22003/3246869172.py in <module>
----> 1 from threeML import *

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/__init__.py in <module>
     53 
     54 # Import everything from astromodels
---> 55 from astromodels import *
     56 
     57 

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/__init__.py in <module>
     14     from .utils.configuration import astromodels_config
     15     from .core.memoization import use_astromodels_memoization
---> 16     from .core.model import Model
     17     from .core.model_parser import clone_model, load_model
     18     from .core.parameter import (IndependentVariable, Parameter,

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/core/model.py in <module>
     17 from astromodels.core.tree import DuplicatedNode, Node
     18 from astromodels.functions.function import get_function
---> 19 from astromodels.sources import (ExtendedSource, ParticleSource, PointSource,
     20                                  Source, SourceType)
     21 from astromodels.utils.disk_usage import disk_usage

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/sources/__init__.py in <module>
      2 
      3 from .point_source import PointSource
----> 4 from .extended_source import ExtendedSource
      5 from .particle_source import ParticleSource
      6 from .source import Source, SourceType

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/sources/extended_source.py in <module>
      7 from astromodels.core.tree import Node
      8 from astromodels.core.units import get_units
----> 9 from astromodels.functions import Constant
     10 from astromodels.sources.source import Source, SourceType
     11 from astromodels.utils.pretty_list import dict_to_list

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/functions/__init__.py in <module>
     36 from .priors import (Cauchy, Cosine_Prior, Gaussian, Log_normal,
     37                      Log_uniform_prior, Truncated_gaussian, Uniform_prior)
---> 38 from .template_model import (MissingDataFile, TemplateModel,
     39                              TemplateModelFactory, XSPECTableModel)
     40 

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/functions/template_model.py in <module>
     12 import astropy.io.fits as fits
     13 import astropy.units as u
---> 14 import h5py
     15 import numpy as np
     16 import scipy.interpolate

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/h5py/__init__.py in <module>
     31         raise
     32 
---> 33 from . import version
     34 
     35 if version.hdf5_version_tuple != version.hdf5_built_version_tuple:

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/h5py/version.py in <module>
     13 
     14 from collections import namedtuple
---> 15 from . import h5 as _h5
     16 import sys
     17 import numpy

h5py/h5.pyx in init h5py.h5()

ImportError: dlopen(/Users/shabu/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/h5py/defs.cpython-37m-darwin.so, 0x0002): Symbol not found: _H5Pget_fapl_ros3
  Referenced from: /Users/shabu/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/h5py/defs.cpython-37m-darwin.so
  Expected in: /Users/shabu/opt/miniconda3/envs/threeML/lib/libhdf5.103.dylib

**Comment by grburgess** [comment]
Is this is a clean conda environment? It seems there is an issue with h5py. I would try to install all the needed modules in one command so that the environment can solve.

**Comment by ShabnamIyyani** [comment]
I tried installing all the needed modules in one command, however, the solving environment went on for more than 12 hours and remained unsuccessful.  I want to use both xspec models as well as do Fermi LAT data analysis. Can you tell me which are the correct versions of the different packages that are required to be installed for the smooth running of 3ML?

**Comment by grburgess** [comment]
You can try mamba to speed up the solving of the environment. Unfortunately, there are a lot of different packages that must be installed w.r.t. to the Fermi tools. The length of time is specifically related to the difficulties that you experience downstream when installing packages separately. 

Its also good to check the Fermi tools GitHub to see if there are issues currently with installing those tools

**Comment by ShabnamIyyani** [comment]
**I was able to successfully install using mamba in the following steps:**
Last login: Fri Dec 31 15:18:49 on ttys003
(base) shabu@Shabnams-iMac ~ % conda create --name threeML 
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/shabu/opt/miniconda3/envs/threeML



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) shabu@Shabnams-iMac ~ % conda activate threeML 
(threeML) shabu@Shabnams-iMac ~ % mamba install -c conda-forge -c threeml -c xspecmodels -c fermi python=3.7 numpy scipy matplotlib astromodels threeml xspec-modelsonly fermitools=2.0.8 python=3 clhep=2.4.4.1 fermipy astropy root  

**However, on activating threeML environment I first get the following error:** 

(base) shabu@Shabnams-iMac ~ % conda activate threeML 
input_line_1:1:2: error: module 'Darwin' uses additional module map
      '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/uuid.modulemap'
      used when the module was built
#include <new>
 ^
input_line_1:1:2: note: imported by module 'std' in
      '/Users/shabu/opt/miniconda3/envs/threeML/lib/std.pcm'
Warning in cling::IncrementalParser::CheckABICompatibility():
  Failed to extract C++ standard library version.
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with _LIBCPP_ABI_VERSION '1'
  Extraction of runtime standard library version was: ''
input_line_2:1:2: error: module 'Darwin' uses additional module map
      '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/uuid.modulemap'
      used when the module was built
#include "cling/Interpreter/RuntimeUniverse.h"
 ^
input_line_2:1:2: note: imported by module 'std' in
      '/Users/shabu/opt/miniconda3/envs/threeML/lib/std.pcm'
input_line_2:1:2: note: imported by module 'Cling_Runtime' in
      '/Users/shabu/opt/miniconda3/envs/threeML/lib/Cling_Runtime.pcm'
Failed to load module std
Failed to load module std
Failed to load module Cling_Runtime
In file included from input_line_7:36:
In file included from /Users/shabu/opt/miniconda3/envs/threeML/bin/../include/c++/v1/cassert:20:
In file included from /Users/shabu/opt/miniconda3/envs/threeML/etc//cling/lib/clang/5.0.0/include/assert.h:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:69:26: error: expected function body after function declarator
void abort(void) __dead2 __cold;
                         ^
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking function '_GLOBAL__sub_I_cling_module_12'!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?

 *** Break *** segmentation violation
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[<unknown binary>] (no debug info)
[/Users/shabu/opt/miniconda3/envs/threeML/lib/libCling.6.22.08.so] cling::Value::isVoid() const (no debug info)
[/Users/shabu/opt/miniconda3/envs/threeML/lib/libCling.6.22.08.so] TCling::ProcessLine(char const*, TInterpreter::EErrorCode*) (no debug info)
[/Users/shabu/opt/miniconda3/envs/threeML/lib/libRint.6.22.08.so] TRint::ProcessLineNr(char const*, char const*, int*) (no debug info)
[/Users/shabu/opt/miniconda3/envs/threeML/lib/libRint.6.22.08.so] TRint::HandleTermInput() (no debug info)
[/Users/shabu/opt/miniconda3/envs/threeML/lib/libCore.6.22.08.so] TUnixSystem::CheckDescriptors() (no debug info)
[/Users/shabu/opt/miniconda3/envs/threeML/lib/libCore.6.22.08.so] TUnixSystem::DispatchOneEvent(bool) (no debug info)
[/Users/shabu/opt/miniconda3/envs/threeML/lib/libCore.6.22.08.so] TSystem::InnerLoop() (no debug info)
[/Users/shabu/opt/miniconda3/envs/threeML/lib/libCore.6.22.08.so] TSystem::Run() (no debug info)
[/Users/shabu/opt/miniconda3/envs/threeML/lib/libCore.6.22.08.so] TApplication::Run(bool) (no debug info)
[/Users/shabu/opt/miniconda3/envs/threeML/lib/libRint.6.22.08.so] TRint::Run(bool) (no debug info)
[/Users/shabu/opt/miniconda3/envs/threeML/bin/root.exe] main (no debug info)
[/usr/lib/dyld] start (no debug info)
[<unknown binary>] (no debug info)
[<unknown binary>] (no debug info)
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
You have LD_LIBRARY_PATH set. This might interfere with the correct functioning of conda and the Fermi ST
You have PYTHONPATH set. This might interfere with the correct functioning of conda and the Fermi ST


**On opening a jupyter notebook** 

[W 15:51:21.201 NotebookApp] Error loading server extension ipyparallel
    Traceback (most recent call last):
      File "/Users/shabu/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/notebook/notebookapp.py", line 2030, in init_server_extensions
        func(self)
      File "/Users/shabu/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ipyparallel/__init__.py", line 95, in _load_jupyter_server_extension
        from .nbextension.handlers import load_jupyter_server_extension
      File "/Users/shabu/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ipyparallel/nbextension/handlers.py", line 7, in <module>
        from jupyter_server.utils import url_path_join as ujoin
    ModuleNotFoundError: No module named 'jupyter_server'
[I 15:51:21.205 NotebookApp] Serving notebooks from local directory: /Users/shabu
[I 15:51:21.205 NotebookApp] Jupyter Notebook 6.4.6 is running at:
[I 15:51:21.205 NotebookApp] http://localhost:8888/?token=25f0fdc92d19be56a487d2d7e4215d369f7d1d1d4bc16dcb
[I 15:51:21.205 NotebookApp]  or http://127.0.0.1:8888/?token=25f0fdc92d19be56a487d2d7e4215d369f7d1d1d4bc16dcb
[I 15:51:21.205 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:51:21.262 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/shabu/Library/Jupyter/runtime/nbserver-41091-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=25f0fdc92d19be56a487d2d7e4215d369f7d1d1d4bc16dcb
     or http://127.0.0.1:8888/?token=25f0fdc92d19be56a487d2d7e4215d369f7d1d1d4bc16dcb
[W 15:51:23.264 NotebookApp] 404 GET /ipyparallel/clusters?_=1640946082700 (::1) 6.050000ms referer=http://localhost:8888/tree
[I 15:51:31.765 NotebookApp] Kernel started: a20a74e6-89b9-44f4-b96d-24ae4f7b5194, name: python3
input_line_1:1:2: error: module 'Darwin' uses additional module map '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/uuid.modulemap' used when the module was built
#include <new>
 ^
input_line_1:1:2: note: imported by module 'std' in '/Users/shabu/opt/miniconda3/envs/threeML/lib/std.pcm'
Warning in cling::IncrementalParser::CheckABICompatibility():
  Failed to extract C++ standard library version.
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with _LIBCPP_ABI_VERSION '1'
  Extraction of runtime standard library version was: ''
input_line_2:1:2: error: module 'Darwin' uses additional module map '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/uuid.modulemap' used when the module was built
#include "cling/Interpreter/RuntimeUniverse.h"
 ^
input_line_2:1:2: note: imported by module 'std' in '/Users/shabu/opt/miniconda3/envs/threeML/lib/std.pcm'
input_line_2:1:2: note: imported by module 'Cling_Runtime' in '/Users/shabu/opt/miniconda3/envs/threeML/lib/Cling_Runtime.pcm'
Failed to load module std
Failed to load module std
In file included from input_line_7:36:
In file included from /Users/shabu/opt/miniconda3/envs/threeML/bin/../include/c++/v1/cassert:20:
In file included from /Users/shabu/opt/miniconda3/envs/threeML/etc//cling/lib/clang/5.0.0/include/assert.h:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:69:26: error: expected function body after function declarator
void abort(void) __dead2 __cold;
                         ^
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?

WARNING: version mismatch between CFITSIO header (v3.47) and linked library (v3.46).

IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
[I 15:53:31.677 NotebookApp] Saving file at /Untitled.ipynb


**In the jupyter notebook,** 
from threeML import *
**gives the following error** 

input_line_1:1:2: error: module 'Darwin' uses additional module map '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/uuid.modulemap' used when the module was built
#include <new>
 ^
input_line_1:1:2: note: imported by module 'std' in '/Users/shabu/opt/miniconda3/envs/threeML/lib/std.pcm'
Warning in cling::IncrementalParser::CheckABICompatibility():
  Failed to extract C++ standard library version.
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with _LIBCPP_ABI_VERSION '1'
  Extraction of runtime standard library version was: ''
input_line_2:1:2: error: module 'Darwin' uses additional module map '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/uuid.modulemap' used when the module was built
#include "cling/Interpreter/RuntimeUniverse.h"
 ^
input_line_2:1:2: note: imported by module 'std' in '/Users/shabu/opt/miniconda3/envs/threeML/lib/std.pcm'
input_line_2:1:2: note: imported by module 'Cling_Runtime' in '/Users/shabu/opt/miniconda3/envs/threeML/lib/Cling_Runtime.pcm'
Failed to load module std
Failed to load module std
In file included from input_line_7:36:
In file included from /Users/shabu/opt/miniconda3/envs/threeML/bin/../include/c++/v1/cassert:20:
In file included from /Users/shabu/opt/miniconda3/envs/threeML/etc//cling/lib/clang/5.0.0/include/assert.h:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:69:26: error: expected function body after function declarator
void abort(void) __dead2 __cold;
                         ^
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
Welcome to JupyROOT 6.22/08

WARNING: version mismatch between CFITSIO header (v3.47) and linked library (v3.46).

[WARNING ] The naima package is not available. Models that depend on it will not be available
[WARNING ] The GSL library or the pygsl wrapper cannot be loaded. Models that depend on it will not be available.
[WARNING ] The ebltable package is not available. Models that depend on it will not be available
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/var/folders/3f/1zr8mvls6r993_sq2spcy64w0000gp/T/ipykernel_41559/3246869172.py in <module>
----> 1 from threeML import *

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/__init__.py in <module>
     22 from pathlib import Path
     23 
---> 24 from threeML.io.logging import setup_logger
     25 from .config import threeML_config, show_configuration, get_current_configuration_copy
     26 

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ROOT/_facade.py in _importhook(name, *args, **kwds)
    119                 except Exception:
    120                     pass
--> 121             return _orig_ihook(name, *args, **kwds)
    122         __builtin__.__import__ = _importhook
    123 

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/io/__init__.py in <module>
----> 1 from .logging import (activate_logs, activate_progress_bars, activate_warnings,
      2                       debug_mode, loud_mode, quiet_mode, setup_logger,
      3                       silence_logs, silence_progress_bars, silence_warnings,
      4                       toggle_progress_bars, update_logging_level)
      5 from .plotting.get_style import get_threeML_style, set_threeML_style

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ROOT/_facade.py in _importhook(name, *args, **kwds)
    119                 except Exception:
    120                     pass
--> 121             return _orig_ihook(name, *args, **kwds)
    122         __builtin__.__import__ = _importhook
    123 

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/io/logging.py in <module>
      6 from typing import Dict, Optional
      7 
----> 8 from astromodels.utils.logging import (ColoredFormatter, LogFilter,
      9                                        _console_formatter, _dev_formatter,
     10                                        _usr_formatter,

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ROOT/_facade.py in _importhook(name, *args, **kwds)
    119                 except Exception:
    120                     pass
--> 121             return _orig_ihook(name, *args, **kwds)
    122         __builtin__.__import__ = _importhook
    123 

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/__init__.py in <module>
     14     from .utils.configuration import astromodels_config
     15     from .core.memoization import use_astromodels_memoization
---> 16     from .core.model import Model
     17     from .core.model_parser import clone_model, load_model
     18     from .core.parameter import (IndependentVariable, Parameter,

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ROOT/_facade.py in _importhook(name, *args, **kwds)
    119                 except Exception:
    120                     pass
--> 121             return _orig_ihook(name, *args, **kwds)
    122         __builtin__.__import__ = _importhook
    123 

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/core/model.py in <module>
     16 from astromodels.core.parameter import IndependentVariable, Parameter
     17 from astromodels.core.tree import DuplicatedNode, Node
---> 18 from astromodels.functions.function import get_function
     19 from astromodels.sources import (ExtendedSource, ParticleSource, PointSource,
     20                                  Source, SourceType)

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ROOT/_facade.py in _importhook(name, *args, **kwds)
    119                 except Exception:
    120                     pass
--> 121             return _orig_ihook(name, *args, **kwds)
    122         __builtin__.__import__ = _importhook
    123 

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/functions/__init__.py in <module>
     36 from .priors import (Cauchy, Cosine_Prior, Gaussian, Log_normal,
     37                      Log_uniform_prior, Truncated_gaussian, Uniform_prior)
---> 38 from .template_model import (MissingDataFile, TemplateModel,
     39                              TemplateModelFactory, XSPECTableModel)
     40 

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ROOT/_facade.py in _importhook(name, *args, **kwds)
    119                 except Exception:
    120                     pass
--> 121             return _orig_ihook(name, *args, **kwds)
    122         __builtin__.__import__ = _importhook
    123 

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/functions/template_model.py in <module>
     12 import astropy.io.fits as fits
     13 import astropy.units as u
---> 14 import h5py
     15 import numpy as np
     16 import scipy.interpolate

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ROOT/_facade.py in _importhook(name, *args, **kwds)
    119                 except Exception:
    120                     pass
--> 121             return _orig_ihook(name, *args, **kwds)
    122         __builtin__.__import__ = _importhook
    123 

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/h5py/__init__.py in <module>
     31         raise
     32 
---> 33 from . import version
     34 
     35 if version.hdf5_version_tuple != version.hdf5_built_version_tuple:

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ROOT/_facade.py in _importhook(name, *args, **kwds)
    119                 except Exception:
    120                     pass
--> 121             return _orig_ihook(name, *args, **kwds)
    122         __builtin__.__import__ = _importhook
    123 

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/h5py/version.py in <module>
     13 
     14 from collections import namedtuple
---> 15 from . import h5 as _h5
     16 import sys
     17 import numpy

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ROOT/_facade.py in _importhook(name, *args, **kwds)
    119                 except Exception:
    120                     pass
--> 121             return _orig_ihook(name, *args, **kwds)
    122         __builtin__.__import__ = _importhook
    123 

h5py/h5.pyx in init h5py.h5()

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ROOT/_facade.py in _importhook(name, *args, **kwds)
    119                 except Exception:
    120                     pass
--> 121             return _orig_ihook(name, *args, **kwds)
    122         __builtin__.__import__ = _importhook
    123 

ImportError: dlopen(/Users/shabu/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/h5py/defs.cpython-37m-darwin.so, 0x0002): Symbol not found: _H5Pget_fapl_ros3
  Referenced from: /Users/shabu/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/h5py/defs.cpython-37m-darwin.so
  Expected in: /Users/shabu/opt/miniconda3/envs/threeML/lib/libhdf5.103.dylib

IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?
​

**Comment by grburgess** [comment]
I'm not sure what the HDF5 errors are, but this could be due to some of the new stuff in macOS. Some of the errors look related to the fermitools package . Try to install only that package and see if there are still errors. If so, try the fermi tools issues page.

**Comment by omodei** [comment]
Is this issue still existing? Can we close it?

**Comment by ShabnamIyyani** [comment]
Please close the problem.
