### ISSUE TITLE
Getting error while trying to build likelihood using Fermi LAT data

### ISSUE THREAD

**Issue by ShabnamIyyani** [threeML/threeML#529]
## Data Analysis Question

I am trying to analyse Fermi GRB LAT data. I followed the following commands:
While I try to create a likelihood model
data_list = DataList(fermi_lat)
fitfun = Powerlaw()
model = Model(PointSource('fit',ra,dec,spectral_shape=fitfun))
jl = JointLikelihood(model, data_list)

I get the following error:

[INFO    ] Using IRFs P8R3_SOURCE_V3

Found Galactic template for IRF. P8R3_SOURCE_V3: /Users/shabnamiyyani/opt/miniconda3/envs/threeML/share/fermitools/refdata/fermi/galdiffuse/gll_iem_v07.fits

Cutting the template around the ROI: 

Found Isotropic template for irf P8R3_SOURCE_V3: /Users/shabnamiyyani/opt/miniconda3/envs/threeML/share/fermitools/refdata/fermi/galdiffuse/iso_P8R3_SOURCE_V3_v1.txt
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/var/folders/vq/jf14w4_j6n7_60zlyxzzkvg40000gn/T/ipykernel_32634/417642095.py in <module>
      1 #Creating a likelihood model
----> 2 jl = JointLikelihood(model, data_list)
      3 jl.set_minimizer("ROOT")
      4 jl.fit();
      5 best_fit_parameters, likelihood_values = jl.fit()

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/classicMLE/joint_likelihood.py in __init__(self, likelihood_model, data_list, verbose, record)
     76         self._data_list: DataList = data_list
     77 
---> 78         self._assign_model_to_data(self._likelihood_model)
     79 
     80         # This is to keep track of the number of calls to the likelihood

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/classicMLE/joint_likelihood.py in _assign_model_to_data(self, model)
    119         for dataset in list(self._data_list.values()):
    120 
--> 121             dataset.set_model(model)
    122 
    123             # Now get the nuisance parameters from the data and add them to the model

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/plugins/FermipyLike.py in set_model(self, likelihood_model_instance)
    461 
    462         self._gta, self._pts_energies = _get_fermipy_instance(
--> 463             self._configuration, likelihood_model_instance
    464         )
    465         self._update_model_in_fermipy( update_dictionary = True, force_update = True)

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/plugins/FermipyLike.py in _get_fermipy_instance(configuration, likelihood_model)
    171 
    172     # This will take a long time if it's the first time we run with this model
--> 173     gta.setup()
    174 
    175     # Substitute all spectra for point sources with FileSpectrum, so that we will be able to control

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/fermipy/gtanalysis.py in setup(self, init_sources, overwrite, **kwargs)
   1080         # Run setup for each component
   1081         for i, c in enumerate(self.components):
-> 1082             c.setup(overwrite=overwrite)
   1083 
   1084         # Create likelihood

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/fermipy/gtanalysis.py in setup(self, overwrite, **kwargs)
   5119 
   5120         self.logger.debug('Loading LT Cube %s', self.files['ltcube'])
-> 5121         self._ltc = LTCube.create(self.files['ltcube'])
   5122 
   5123         # Extract tmin, tmax from LT cube

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/fermipy/ltcube.py in create(cls, ltfile)
    190             files = glob.glob(ltfile)
    191 
--> 192         ltc = cls.create_from_fits(files[0])
    193         for f in files[1:]:
    194             ltc.load_ltfile(f)

IndexError: list index out of range

usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory

Please advise me how to resolve the above issue.

**Comment by ShabnamIyyani** [comment]
During the respective LAT data download command and generating the respective files 

evfile, scfile = download_LAT_data(ra, dec, 12.0, tstart, tstop, time_type='MET', destination_directory='lat_int08')

# Configuration for Fermipy
config = FermipyLike.get_basic_config(evfile=evfile, scfile=scfile, ra=ra, dec=dec)

config['selection']['emax'] = 500.0 #MeV = 300 GeV
config['selection']['emin'] = 100.0 #MeV = 0.1 GeV
config['gtlike'] = {'edisp': True}

#Let's create an instance of the plugin Note that here no processing is made, because fermipy still doesn't know about the model you want to use
fermi_lat = FermipyLike("LAT", config)

config.display()

This runs without any error. 

 I noted that in the folder '__c792dec2a6ab7fa5e72cab0562d8aeb9' that is created, it contains just .par files but .fits files such as ccube.fits, ltcube_00.fits etc and fermipy.log file etc are not created.

**Comment by omodei** [comment]
Is this issue still existing? Can we close it? If it is still a problem, can you post the full output (also from fermitools and fermipy)?

**Comment by ShabnamIyyani** [comment]
Please close the problem.
