### ISSUE TITLE
Not able to import xspec models

### ISSUE THREAD

**Issue by ShabnamIyyani** [threeML/threeML#534]
**Describe the bug**
While I try the command
import astromodels.xspec

I get the following error message
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/var/folders/vq/jf14w4_j6n7_60zlyxzzkvg40000gn/T/ipykernel_10098/450884429.py in <module>
----> 1 import astromodels.xspec

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ROOT/_facade.py in _importhook(name, *args, **kwds)
    119                 except Exception:
    120                     pass
--> 121             return _orig_ihook(name, *args, **kwds)
    122         __builtin__.__import__ = _importhook
    123 

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/xspec/__init__.py in <module>
----> 1 from .factory import *
      2 #from .xspec_settings import x

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ROOT/_facade.py in _importhook(name, *args, **kwds)
    119                 except Exception:
    120                     pass
--> 121             return _orig_ihook(name, *args, **kwds)
    122         __builtin__.__import__ = _importhook
    123 

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/xspec/factory.py in <module>
     16     pass
     17 
---> 18 from astromodels.xspec import _xspec
     19 
     20 # When running in a Anaconda environment, the package xspec-modelsonly

~/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/ROOT/_facade.py in _importhook(name, *args, **kwds)
    119                 except Exception:
    120                     pass
--> 121             return _orig_ihook(name, *args, **kwds)
    122         __builtin__.__import__ = _importhook
    123 

ImportError: dlopen(/Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/xspec/_xspec.cpython-37m-darwin.so, 2): Symbol not found: __Z6tabintPfiS_iPKciS1_S_S_
  Referenced from: /Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/xspec/_xspec.cpython-37m-darwin.so
  Expected in: /Users/shabnamiyyani/heasoft-6.29/x86_64-apple-darwin19.6.0/lib/libXSFunctions.dylib
 in /Users/shabnamiyyani/opt/miniconda3/envs/threeML/lib/python3.7/site-packages/astromodels/xspec/_xspec.cpython-37m-darwin.so

**Desktop (please complete the following information):**
 - OS: MacOS Catalina version 10.15.7
 - Xcode version 12.4

I have also installed the heasoft package including the xspec models

**Comment by grburgess** [comment]
Have you installed the conda package with XSPEC?

**Comment by ShabnamIyyani** [comment]
Yes, I have xspec-modelsonly          version=6.25

**Comment by grburgess** [comment]
Likely you have both your local installed and the conda installed XSPEC in your paths and they are colliding.

**Comment by ShabnamIyyani** [comment]
Thanks for the reply. The issue has been solved. Before activating the conda environment for 3ML, I did 
unset DYLD_LIBRARY_PATH
unset LD_LIBRARY_PATH

After that, the import of xspec models works fine.
