### ISSUE TITLE
How do I install a stable threeml module?

### ISSUE THREAD

**Issue by Jisan528** [threeML/threeML#544]
Hello,

The `threeml` module is currently latest, causing many modules to fail to install, including the `Xspexc`module. So I want to install a more stable `threeml` module, so how do I do that?

**Comment by grburgess** [comment]
Can you specify the error?

**Comment by mengjian2024** [comment]
A module collision occurred when I entered the threeML environment and ran `conda install -c xspecModels xspec-modelsonly`, as follows:

![image](https://user-images.githubusercontent.com/100666647/174936717-565af682-d632-481b-b722-40c2faa98a5b.png)

**Comment by grburgess** [comment]
Is it possible to past the text as the screen shot is difficult to read.

**Comment by grburgess** [comment]
According to the scheduled CI tests, these modules are installing. Without a more detailed summary of what process was used to create the environment, it is not possible to know how to solve this issue.

**Comment by mengjian2024** [comment]
Ok,sir.The command line prompt is so extensive that I can only break it down into a few comments

**Comment by mengjian2024** [comment]
Collecting package metadata (current_repodata.json): done
Solving environment: -
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/linux-64::astromodels==2.3.2=py37h48bf904_0
  - conda-forge/noarch::astroquery==0.4.6=pyhd8ed1ab_0
  - conda-forge/noarch::corner==2.1.0=pyhd3deb0d_1
  - conda-forge/noarch::dynesty==1.2.3=pyhd8ed1ab_0
  - conda-forge/linux-64::matplotlib==3.3.2=py37h89c1867_1
  - conda-forge/noarch::networkx==2.7.1=pyhd8ed1ab_0
  - conda-forge/linux-64::pygmo==2.18.0=py37h63efc41_1
  - conda-forge/linux-64::pymultinest==2.11=py37h89c1867_1
  - conda-forge/noarch::pyvo==1.2.1=pyhd8ed1ab_0
  - conda-forge/linux-64::speclite==0.14=py37h89c1867_0
  - threeml/linux-64::threeml==2.3.0=py37_0
  - conda-forge/linux-64::ultranest==3.4.4=py37hda87dfa_0
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/linux-64::astromodels==2.3.2=py37h48bf904_0
  - conda-forge/noarch::astroquery==0.4.6=pyhd8ed1ab_0
  - conda-forge/noarch::corner==2.1.0=pyhd3deb0d_1
  - conda-forge/noarch::dynesty==1.2.3=pyhd8ed1ab_0
  - conda-forge/linux-64::matplotlib==3.3.2=py37h89c1867_1
  - conda-forge/noarch::networkx==2.7.1=pyhd8ed1ab_0
  - conda-forge/linux-64::pygmo==2.18.0=py37h63efc41_1
  - conda-forge/linux-64::pymultinest==2.11=py37h89c1867_1
  - conda-forge/noarch::pyvo==1.2.1=pyhd8ed1ab_0
  - conda-forge/linux-64::speclite==0.14=py37h89c1867_0
  - threeml/linux-64::threeml==2.3.0=py37_0
  - conda-forge/linux-64::ultranest==3.4.4=py37hda87dfa_0
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - argon2-cffi -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']
  - bleach -> python[version='>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - html5lib -> python[version='>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - jinja2 -> python[version='>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - packaging -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - pickleshare -> python[version='>=3.10,<3.11.0a0|>=3.9,<3.10.0a0']
  - prometheus_client -> python[version='>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - pygments -> python[version='>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - pyopenssl -> python[version='>=3.10,<3.11.0a0|>=3.9,<3.10.0a0']
  - python-dateutil -> python[version='>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
  - soupsieve -> python[version='>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.5,<3.6.0a0']
  - typing_extensions -> python[version='>=3.10,<3.11.0a0|>=3.9,<3.10.0a0']
  - wheel -> python[version='>=3.10,<3.11.0a0|>=3.9,<3.10.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package ld_impl_linux-64 conflicts for:
nbconvert-pandoc -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
flit-core -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
pytz -> python[version='>=3.10,<3.11.0a0'] -> ld_impl_linux-64[version='>=2.34']
dill -> python[version='>=3.5'] -> ld_impl_linux-64[version='>=2.34']
brotlipy -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
notebook -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
ipython_genutils -> python -> ld_impl_linux-64[version='>=2.34']
networkx -> python[version='>=3.8'] -> ld_impl_linux-64[version='>=2.34']
pyopenssl -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
pexpect -> python -> ld_impl_linux-64[version='>=2.34']
h5py -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
sip -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
bottleneck -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
cython -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
secretstorage -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
cached_property -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
nbconvert-core -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
pygmo -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
importlib_metadata -> python[version='>=3.8,<3.9.0a0'] -> ld_impl_linux-64[version='>=2.34']
numdifftools -> python -> ld_impl_linux-64[version='>=2.34']
py -> python[version='>=3.5'] -> ld_impl_linux-64[version='>=2.34']
pyqt5-sip -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
tqdm -> python[version='>=3.8,<3.9.0a0'] -> ld_impl_linux-64[version='>=2.34']
packaging -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
pytables -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
importlib_resources -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
llvmlite -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
pyerfa -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
python-dateutil -> python -> ld_impl_linux-64[version='>=2.34']
nest-asyncio -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
jsonschema -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
pymultinest -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
numexpr -> python[version='>=3.8,<3.9.0a0'] -> ld_impl_linux-64[version='>=2.34']
pygments -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
future -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
ultranest -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
matplotlib -> python[version='>=3.8,<3.9.0a0'] -> ld_impl_linux-64[version='>=2.34']
astroquery -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
backports.functools_lru_cache -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
corner -> python -> ld_impl_linux-64[version='>=2.34']
traitlets -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
pluggy -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
pyqt -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
omegaconf -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
backports -> python -> ld_impl_linux-64[version='>=2.34']
pandocfilters -> python[version='!=3.0,!=3.1,!=3.2,!=3.3'] -> ld_impl_linux-64[version='>=2.34']
jedi -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
numba -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
tornado -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
kiwisolver -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
entrypoints -> python[version='>=3.8,<3.9.0a0'] -> ld_impl_linux-64[version='>=2.34']
glib -> python= -> ld_impl_linux-64[version='>=2.34']
setuptools -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
argon2-cffi-bindings -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
charset-normalizer -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
pycparser -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
cached-property -> python -> ld_impl_linux-64[version='>=2.34']
iminuit -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
certifi -> python[version='>=3.8,<3.9.0a0'] -> ld_impl_linux-64[version='>=2.34']
defusedxml -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
debugpy -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
pytest -> python[version='>=3.8,<3.9.0a0'] -> ld_impl_linux-64[version='>=2.34']
pickleshare -> python[version='>=3'] -> ld_impl_linux-64[version='>=2.34']
numpy -> python[version='>=3.8,<3.9.0a0'] -> ld_impl_linux-64[version='>=2.34']
tinycss2 -> python[version='>=3.5'] -> ld_impl_linux-64[version='>=2.34']
cffi -> python[version='>=3.10,<3.11.0a0'] -> ld_impl_linux-64[version='>=2.34']
emcee -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
argon2-cffi -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
asciitree -> python -> ld_impl_linux-64[version='>=2.34']
jinja2 -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
interpolation -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
statsmodels -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
pyparsing -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
python=3.7 -> ld_impl_linux-64[version='>=2.34']
ipyparallel -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
prometheus_client -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
pysocks -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
python_abi -> python=3.7 -> ld_impl_linux-64[version='>=2.34']
pyvo -> python[version='>=3.5'] -> ld_impl_linux-64[version='>=2.34']
matplotlib-inline -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
mistune -> python -> ld_impl_linux-64[version='>=2.34']
send2trash -> python -> ld_impl_linux-64[version='>=2.34']
beautifulsoup4 -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
typing_extensions -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
psutil -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
tomli -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
python-mimeparse -> python -> ld_impl_linux-64[version='>=2.34']
pillow -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
decorator -> python[version='>=3.5'] -> ld_impl_linux-64[version='>=2.34']
jupyterlab_pygments -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
ipywidgets -> python[version='>=3.3'] -> ld_impl_linux-64[version='>=2.34']
terminado -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
widgetsnbextension -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
six -> python -> ld_impl_linux-64[version='>=2.34']
nbformat -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
webencodings -> python[version='>=3.10,<3.11.0a0'] -> ld_impl_linux-64[version='>=2.34']
cryptography -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
nlopt -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
ptyprocess -> python -> ld_impl_linux-64[version='>=2.34']
dynesty -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
pyzmq -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
iniconfig -> python -> ld_impl_linux-64[version='>=2.34']
pip -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
idna -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
jupyterlab_widgets -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
wcwidth -> python -> ld_impl_linux-64[version='>=2.34']
jupyter_client -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
astromodels -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
bleach -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
algopy -> python -> ld_impl_linux-64[version='>=2.34']
keyring -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
nbclient -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
cycler -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
zipp -> python[version='>=3.9,<3.10.0a0'] -> ld_impl_linux-64[version='>=2.34']
toml -> python[version='>=2.7'] -> ld_impl_linux-64[version='>=2.34']
wheel -> python -> ld_impl_linux-64[version='>=2.34']
pandas -> python[version='>=3.10,<3.11.0a0'] -> ld_impl_linux-64[version='>=2.34']
jupyter_core -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
pyyaml -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
ipython -> python[version='>=3.10,<3.11.0a0'] -> ld_impl_linux-64[version='>=2.34']
antlr-python-runtime -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
tempita -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
cloudpickle -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
patsy -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
importlib-metadata -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
pyrsistent -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
backcall -> python -> ld_impl_linux-64[version='>=2.34']
speclite -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
prompt-toolkit -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
parso -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
python-fastjsonschema -> python[version='>=3.3'] -> ld_impl_linux-64[version='>=2.34']
scipy -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
uncertainties -> python[version='>=3'] -> ld_impl_linux-64[version='>=2.34']
soupsieve -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
jeepney -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
urllib3 -> python[version='>=3.9,<3.10.0a0'] -> ld_impl_linux-64[version='>=2.34']
attrs -> python -> ld_impl_linux-64[version='>=2.34']
threeml -> python[version='>=3.7,<3.8.0a0'] -> ld_impl_linux-64[version='>=2.34']
html5lib -> python -> ld_impl_linux-64[version='>=2.34']
nbconvert -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']
requests -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
typing-extensions -> python -> ld_impl_linux-64[version='>=2.34']
colorama -> python[version='>=3.6'] -> ld_impl_linux-64[version='>=2.34']
ipykernel -> python[version='>=3.7'] -> ld_impl_linux-64[version='>=2.34']

Package cffi conflicts for:
cryptography -> cffi[version='!=1.11.3,>=1.8|>=1.12|>=1.8|>=1.7']
argon2-cffi -> argon2-cffi-bindings -> cffi[version='>=1.0.1']
argon2-cffi -> cffi[version='>=1.0.0']
argon2-cffi-bindings -> cffi[version='>=1.0.1']
notebook -> argon2-cffi -> cffi[version='>=1.0.0']
urllib3 -> brotlipy[version='>=0.6.0'] -> cffi[version='!=1.11.3,>=1.8|>=1.0.0|>=1.12|>=1.8|>=1.7']
brotlipy -> cffi[version='>=1.0.0']
pyopenssl -> cryptography[version='>=35.0'] -> cffi[version='!=1.11.3,>=1.8|>=1.12|>=1.8|>=1.7']
secretstorage -> cryptography -> cffi[version='!=1.11.3,>=1.8|>=1.12|>=1.8|>=1.7']

Package tzdata conflicts for:
beautifulsoup4 -> python[version='>=3.10,<3.11.0a0'] -> tzdata
typing-extensions -> python -> tzdata
numdifftools -> python -> tzdata
psutil -> python[version='>=3.10,<3.11.0a0'] -> tzdata
argon2-cffi-bindings -> python[version='>=3.9,<3.10.0a0'] -> tzdata
scipy -> python[version='>=3.9,<3.10.0a0'] -> tzdata
mistune -> python -> tzdata
numba -> python[version='>=3.9,<3.10.0a0'] -> tzdata
pytz -> python[version='>=3.10,<3.11.0a0'] -> tzdata
send2trash -> python -> tzdata
ipykernel -> python[version='>=3.7'] -> tzdata
pyyaml -> python[version='>=3.9,<3.10.0a0'] -> tzdata
pyqt -> python[version='>=3.10,<3.11.0a0'] -> tzdata
cryptography -> python[version='>=3.10,<3.11.0a0'] -> tzdata
networkx -> python[version='>=3.8'] -> tzdata
pyopenssl -> python[version='>=3.6'] -> tzdata
pexpect -> python -> tzdata
jupyterlab_pygments -> python[version='>=3.7'] -> tzdata
markupsafe -> python[version='>=3.10,<3.11.0a0'] -> tzdata
widgetsnbextension -> python[version='>=3.10,<3.11.0a0'] -> tzdata
nbclient -> python[version='>=3.7'] -> tzdata
matplotlib -> python[version='>=3.9,<3.10.0a0'] -> tzdata
pytest -> python[version='>=3.10,<3.11.0a0'] -> tzdata
importlib_resources -> python[version='>=3.6'] -> tzdata
charset-normalizer -> python[version='>=3.6'] -> tzdata
sip -> python[version='>=3.9,<3.10.0a0'] -> tzdata
cloudpickle -> python[version='>=3.6'] -> tzdata
webencodings -> python[version='>=3.10,<3.11.0a0'] -> tzdata
jedi -> python[version='>=3.10,<3.11.0a0'] -> tzdata
cython -> python[version='>=3.9,<3.10.0a0'] -> tzdata
backports -> python -> tzdata
pytables -> python[version='>=3.9,<3.10.0a0'] -> tzdata
jsonschema -> python[version='>=3.7'] -> tzdata
llvmlite -> python[version='>=3.9,<3.10.0a0'] -> tzdata
astroquery -> python[version='>=3.7'] -> tzdata
traitlets -> python[version='>=3.7'] -> tzdata
cached-property -> python -> tzdata
debugpy -> python[version='>=3.10,<3.11.0a0'] -> tzdata
jupyter_core -> python[version='>=3.10,<3.11.0a0'] -> tzdata
bleach -> python[version='>=3.6'] -> tzdata
algopy -> python -> tzdata
dill -> python[version='>=3.5'] -> tzdata
tempita -> python[version='>=3.10,<3.11.0a0'] -> tzdata
iminuit -> python[version='>=3.10,<3.11.0a0'] -> tzdata
cffi -> python[version='>=3.10,<3.11.0a0'] -> tzdata
glib -> python= -> tzdata
statsmodels -> python[version='>=3.9,<3.10.0a0'] -> tzdata
pysocks -> python[version='>=3.10,<3.11.0a0'] -> tzdata
pyrsistent -> python[version='>=3.10,<3.11.0a0'] -> tzdata
kiwisolver -> python[version='>=3.9,<3.10.0a0'] -> tzdata
ipyparallel -> python[version='>=3.6'] -> tzdata
soupsieve -> python[version='>=3.6'] -> tzdata
importlib-metadata -> python[version='>=3.10,<3.11.0a0'] -> tzdata
brotlipy -> python[version='>=3.9,<3.10.0a0'] -> tzdata
backports.functools_lru_cache -> python[version='>=3.6'] -> tzdata
argon2-cffi -> python[version='>=3.6'] -> tzdata
asciitree -> python -> tzdata
jinja2 -> python[version='>=3.7'] -> tzdata
interpolation -> python[version='>=3.6'] -> tzdata
terminado -> python[version='>=3.10,<3.11.0a0'] -> tzdata
pyparsing -> python[version='>=3.6'] -> tzdata
python-mimeparse -> python -> tzdata
future -> python[version='>=3.10,<3.11.0a0'] -> tzdata
notebook -> python[version='>=3.7'] -> tzdata
decorator -> python[version='>=3.5'] -> tzdata
cached_property -> python[version='>=3.6'] -> tzdata
nbconvert-core -> python[version='>=3.7'] -> tzdata
pyvo -> python[version='>=3.5'] -> tzdata
matplotlib-inline -> python[version='>=3.6'] -> tzdata
six -> python -> tzdata
py -> python[version='>=3.5'] -> tzdata
bottleneck -> python[version='>=3.9,<3.10.0a0'] -> tzdata
tqdm -> python[version='>=3.9,<3.10.0a0'] -> tzdata
packaging -> python[version='>=3.6'] -> tzdata
patsy -> python[version='>=3.9,<3.10.0a0'] -> tzdata
python-dateutil -> python -> tzdata
typing_extensions -> python[version='>=3.7'] -> tzdata
tomli -> python[version='>=3.7'] -> tzdata
pyerfa -> python[version='>=3.10,<3.11.0a0'] -> tzdata
pillow -> python[version='>=3.10,<3.11.0a0'] -> tzdata
pluggy -> python[version='>=3.10,<3.11.0a0'] -> tzdata
entrypoints -> python[version='>=3.9,<3.10.0a0'] -> tzdata
ptyprocess -> python -> tzdata
dynesty -> python[version='>=3.6'] -> tzdata
certifi -> python[version='>=3.9,<3.10.0a0'] -> tzdata
pygments -> python[version='>=3.6'] -> tzdata
pip -> python[version='>=3.7'] -> tzdata
corner -> python -> tzdata
ipywidgets -> python[version='>=3.3'] -> tzdata
jupyterlab_widgets -> python[version='>=3.6'] -> tzdata
wcwidth -> python -> tzdata
keyring -> python[version='>=3.10,<3.11.0a0'] -> tzdata
nbformat -> python[version='>=3.7'] -> tzdata
nbconvert -> python[version='>=3.7'] -> tzdata
emcee -> python[version='>=3.6'] -> tzdata
jupyter_client -> python[version='>=3.7'] -> tzdata
pandocfilters -> python[version='!=3.0,!=3.1,!=3.2,!=3.3'] -> tzdata
wheel -> python -> tzdata
tornado -> python[version='>=3.10,<3.11.0a0'] -> tzdata
uncertainties -> python[version='>=3'] -> tzdata
iniconfig -> python -> tzdata
pycparser -> python[version='>=3.6'] -> tzdata
idna -> python[version='>=3.6'] -> tzdata
numpy -> python[version='>=3.10,<3.11.0a0'] -> tzdata
nest-asyncio -> python[version='>=3.9,<3.10.0a0'] -> tzdata
defusedxml -> python[version='>=3.6'] -> tzdata
pickleshare -> python[version='>=3'] -> tzdata
urllib3 -> python[version='>=3.9,<3.10.0a0'] -> tzdata
cycler -> python[version='>=3.6'] -> tzdata
zipp -> python[version='>=3.9,<3.10.0a0'] -> tzdata
numexpr -> python[version='>=3.9,<3.10.0a0'] -> tzdata
toml -> python[version='>=2.7'] -> tzdata
colorama -> python[version='>=3.6'] -> tzdata
ipython -> python[version='>=3.10,<3.11.0a0'] -> tzdata
nbconvert-pandoc -> python[version='>=3.7'] -> tzdata
flit-core -> python[version='>=3.6'] -> tzdata
pandas -> python[version='>=3.10,<3.11.0a0'] -> tzdata
antlr-python-runtime -> python[version='>=3.6'] -> tzdata
backcall -> python -> tzdata
prompt-toolkit -> python[version='>=3.6'] -> tzdata
parso -> python[version='>=3.6'] -> tzdata
python-fastjsonschema -> python[version='>=3.3'] -> tzdata
h5py -> python[version='>=3.10,<3.11.0a0'] -> tzdata
secretstorage -> python[version='>=3.10,<3.11.0a0'] -> tzdata
ipython_genutils -> python -> tzdata
jeepney -> python[version='>=3.7'] -> tzdata
attrs -> python -> tzdata
tinycss2 -> python[version='>=3.5'] -> tzdata
html5lib -> python -> tzdata
prometheus_client -> python[version='>=3.6'] -> tzdata
pyzmq -> python[version='>=3.10,<3.11.0a0'] -> tzdata
requests -> python[version='>=3.6'] -> tzdata
setuptools -> python[version='>=3.10,<3.11.0a0'] -> tzdata

Package flit-core conflicts for:
notebook -> argon2-cffi -> flit-core[version='>=3.4,<4']
argon2-cffi -> flit-core[version='>=3.4,<4']

**Comment by grburgess** [comment]
This is not very helpful. Can you simply detail the commands you used to install?

**Comment by mengjian2024** [comment]
I used this command directly in the threeML environment: `conda install -c xspecModels xspec-modelsonly`

**Comment by grburgess** [comment]
Have you installed anything else in the environment before this?

**Comment by grburgess** [comment]
please follow the installation instructions here: https://threeml.readthedocs.io/en/latest/md_docs/fast_execute/installation.html?highlight=install#conda-installation

**Comment by mengjian2024** [comment]
Sir, I followed this tutorial, but when I went to install the `xspec` module, those commands appeared

**Comment by mengjian2024** [comment]
I think the current version of the `threeml` module is so new that it conflicts with other dependencies and cannot be installed

**Comment by grburgess** [comment]
This means that you did have other things installed in the environment

**Comment by mengjian2024** [comment]
Ok, I'll try. Thank you so much for your help! @grburgess

**Comment by mengjian2024** [comment]
Sir, what should I do if I don't want to install the latest threeml?

**Comment by omodei** [comment]
The conflicts was caused by a version of astromodels in Conda-forge. Make sure to use the version in the threeML channel.
