### ISSUE TITLE
collections.Sequence is deprecated in Python 3.7 and removed in python 3.10

### ISSUE THREAD

**Issue by jasonfan1997** [threeML/threeML#555]
In analysis_results.py:1872, the collections.Sequence is deprecated in Python 3.7  no longer supported in python 3.10. It is moved to collections.abc.Sequence.

**Comment by grburgess** [comment]
I think this is fixed in the dev branch. What version are you using?

**Comment by jasonfan1997** [comment]
Sorry, I forgot to reply. I was using the master branch but I can see the dev branch has already fixed the issue, thanks for the help!
