### ISSUE TITLE
OGIPLike plugin cannot find spectra: get_path_of_data_file()

### ISSUE THREAD

**Issue by kchoX14** [threeML/threeML#556]
**Describe the bug**
I am using NuSTAR X-ray data from blazars. My `threeml` is installed and configured within a virtual environment in `/home/kishalay/E/threeML-env/` and my data files are all inside `/home/kishalay/D/`. When I try to load a `.pha` spectrum using the _OGIPLike_ plugin, the `observation=get_path_of_data_file("/absolute/or/relative/path/to/myfile.pha")` command fails to locate the spectrum. Every single time the program tries to find spectral files within the `/home/kishalay/E/threeML-env/lib/python3.9/site-packages/threeML/data/` location instead.

*_NOTE:_* This is for BUG reports and not questions about generic data analysis. I am using the most "conda-stable" Spyder IDE (_v3.2.2_) for Ubuntu 18.04, installed using `pip` inside my environment.

**To Reproduce**
1. Store a FITS standard OGIP Type I spectrum in any place other than the threeML configuration path.
2. Open Python. Then `from threeML import *` and `from threeML.io.package_data import get_path_of_data_file`.
3. Type `ogip_data = OGIPLike("ogip", observation=get_path_of_data_file("/absolute/or/relative/path/to/myfile.pha")`.
4. Print information with `print(ogip_data.display())`.
5. See error in screenshot below.

**Expected behavior**
I expected the spectral information to be printed, as provided on the documentation [here](https://threeml.readthedocs.io/en/latest/notebooks/spectrum_tutorial.html#OGIPLike).

**Screenshots**
Please find the screenshot attached (but ignore the edited path information given inside `get_path_of_data_file()` calls. Look at the error message highlighted on the bottom-right:
![Screenshot from 2022-08-13 00-55-32](https://user-images.githubusercontent.com/87929849/184429383-664f6f79-5049-4d8c-b58a-689867755a95.png)

The function call always tries to look at one place for the data files. I tried changing the working directory to the `/3ML-analysis/` sub-directory, where all my spectra are located. But `os.chdir()`, whether commented or uncommented, does not work. Changing the absolute [ath inside the function call also does not work. The only things that works (redundantly) is what has been mentioned at the end of this report.

**Desktop (please complete the following information):**
 - OS: [Ubuntu Linux]
 - Version [18.04 LTS]
 - Python _v3.9.12_
 - threeML (latest using Git fetch with `pip` as per directions [here](https://threeml.readthedocs.io/en/latest/notebooks/installation.html#Install-from-source-(advanced)))

**Additional context**
I checked the `package_data.py` file inside the  `/home/kishalay/E/threeML-env/lib/python3.9/site-packages/threeML/io` directory (to see why the error comes up with the `get_path_of_data_file()` function call from within it). It seems like the following screenshot of the snippet from within `/home/kishalay/E/threeML-env/lib/python3.9/site-packages/threeML/io/package_data.py` is forcing threeML to always look for data inside `/home/kishalay/E/threeML-env/lib/python3.9/site-packages/threeML/data/`:
![OGIPLike-forcedDataPath](https://user-images.githubusercontent.com/87929849/184427442-90a1775e-ce78-40a9-ac78-404f242b8a1d.png)

The same is true for the `get_path_of_data_dir()` function call. It'd be great to have the call accept any directory with path specified within the system to search for the data. **_Please suggest a flexible alternative_**.

**Currently**
All data files need to be copied to `/home/kishalay/E/threeML-env/lib/python3.9/site-packages/threeML/data/`, which is redundant and messy.

**Comment by grburgess** [comment]
Please input the path to your data only. 

There is no need to tag a specific person in the team of developers. Opening an issue is enough. Please respect community standards.

**Comment by kchoX14** [comment]
> Please input the path to your data only.
> 
> There is no need to tag a specific person in the team of developers. Opening an issue is enough. Please respect community standards.

I tried that too. Same error. Here's the output again, just like in the tutorial:
![Try2](https://user-images.githubusercontent.com/87929849/184430150-92f96aeb-f10d-4359-9bf7-736d2ea5acff.png)

**Comment by kchoX14** [comment]
The call seems to be erroneously searching for the PHA file inside the absolute path provided to the true location, but within `/home/kishalay/E/threeML-env/lib/python3.9/site-packages/threeML/data/`.

**Comment by grburgess** [comment]
Just put the path of the file as the argument.

**Comment by kchoX14** [comment]
> Just put the path of the file as the argument.

You mean simply:
`ogip_data = OGIPLike("ogip", observation=get_path_of_data_file("/home/kishalay/D/Mrk421_NuSTAR_2017/spectra/3ML-analysis/))` ?

**Comment by grburgess** [comment]
That function returns a string. This implies you need a string in the argument of the class.

**Comment by kchoX14** [comment]
It w

> That function returns a string. This implies you need a string in the argument of the class.

It worked without the `get_path_of_data_file()` function call within. Just `OGIPLike()` was enough with the "ogip" string as the first argument. So, I guess you don't really need that particular function, unlike what is stated **[here](https://threeml.readthedocs.io/en/latest/notebooks/spectrum_tutorial.html#OGIPLike)**?

![Worked](https://user-images.githubusercontent.com/87929849/184434144-404c0014-3b07-44e2-8a3b-ea164893293d.png)

**Comment by kchoX14** [comment]
> > That function returns a string. This implies you need a string in the argument of the class.
> 
> It worked without the `get_path_of_data_file()` function call within. Just `OGIPLike()` was enough with the "ogip" string as the first argument. So, I guess you don't really need that particular function, unlike what is stated **[here](https://threeml.readthedocs.io/en/latest/notebooks/spectrum_tutorial.html#OGIPLike)**?
> 
> ![Worked](https://user-images.githubusercontent.com/87929849/184434144-404c0014-3b07-44e2-8a3b-ea164893293d.png)

Besides, **how does one provide the ARF file?** An RSP file is usually the combination of an RMF and ARF. But individual spectra are created with separate RMF and ARF. The _[help documentation](https://threeml.readthedocs.io/en/latest/notebooks/spectrum_tutorial.html#OGIPLike) does not state how to load the ARF but only RMF/RSP_. 

This is what I get from the above loading before useful details are printed (as shown in the screenshot above):
_**WARNING   The response is in an extension called        \response.py\:\451\
                  MATRIX, which usually means you also need an                  
                  ancillary file (ARF) which you didn't provide.                
                  You should refer to the documentation  of the                 
                  instrument and make sure you don't need an                    
                  ARF.**_
