### ISSUE TITLE
plot_spectra() unable to propagate errors and plot

### ISSUE THREAD

**Issue by kchoX14** [threeML/threeML#560]
## Data Analysis Question
The spectrum model counts and corner plots work fine with my script. When plotted after running the Bayesian Analysis, only the spectrum plot fails from the point of error propagation. For ease of troubleshooting, I am attaching:

1. my Python setup file, with comments to help understand the sequence of the computation-  
[python-setup.txt](https://github.com/threeML/threeML/files/9349048/python-setup.txt)

2. screenshot of the error I receive on the console upon execution of the very last line (`plot_spectra()`) in the setup file-  
![RuntimeErr_PlotSpectra](https://user-images.githubusercontent.com/87929849/184830275-1198e8fb-e3d1-422d-a98b-cb9926a39f92.png)
  
3. the location of the error returned on the console, suggesting no free parameters (which I suspect has to do with the FPMB model definition, where all are linked to FPMA and just the one remaining there is fixed)-  
![NoFreePar-buildPropFunc-error_PlotSpectra](https://user-images.githubusercontent.com/87929849/184830310-ca819615-d57a-462a-bc23-feb142ee929c.png)

**Some notes to understand the setup**

- NuSTAR FPMA and FPMB spectra _have to be_ read together, and _the parameters of one linked with the other's (except the cross-calibration constant)_. So, like in my case, if I keep the FPMA constant (`factor_1` in the setup, starting at 1.0) and the required model parameters free (+ redshift being the nuisance parameter), the FPMB constant needs to be fixed/frozen at 1.0 and all its other model parameters (including normalization) linked with the corresponding parameters of the FPMA model.
- Not only did I set the priors, but also the bounds manually before linking them. I know my parameters have to lie within those ranges.
- I'm not sure if it was redundant to set the bounds and parameter values manually before defining the priors. But it should not affect the analysis or the results.
- I've assigned each source data to it's model name properly with the `assign_to_source()` method.

### What is going wrong here?

**Comment by grburgess** [comment]
I'm not exactly sure why this is occurring. It is much easier to read the code here than downloading a file. E.g.
```python
import os
import warnings
warnings.simplefilter("ignore")

import numpy as np
np.seterr(all="ignore")

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

from matplotlib.ticker import FuncFormatter
plt.rcParams["font.family"] = "serif"

import astropy.units as u
import astropy.io.fits as fits
from threeML import *
#from threeML.io.package_data import get_path_of_data_file
#import ultranest
silence_logs()
from tqdm.auto import tqdm
from jupyterthemes import jtplot

#matplotlib inline
jtplot.style(context="talk", fscale=1, ticks=True, grid=False)
set_threeML_style()
silence_warnings()

#-----------------------------------------------------------------------------------------------------------------------------#

### Setting up the models for FPMA and FPMB spectra ###
from astromodels.xspec.factory import *
from astromodels.xspec.xspec_settings import *
from astromodels.functions.priors import *
xspec_cosmo(H0=73.0)
xspec_abund("wilm")
xspec_xsect("vern")

m1_A = XS_constant()*XS_zlogpar()

m1_A.factor_1.bounds = (0.9,1.1)		    # FPMA cross-calibration constant kept free at value 1.
m1_A.alpha_2.value = 2.0
# "beta_2" kept default #
m1_A.pivote_2.value = 6.4
m1_A.pivote_2.fix = True
m1_A.redshift_2.value = 0.0308
m1_A.redshift_2.fix = True
m1_A.norm_2.bounds = (0.0,10.0)
m1_A.norm_2.delta = 0.01

m1_B = XS_constant()*XS_zlogpar()
m1_B.factor_1.fix = True

m2_B = XS_constant()*(XS_zlogpar() + XS_zgauss())
m2_B.factor_1.fix = True			    # FPMB parameters are supposed to be linked with FPMA's for a single 
						    # model simultaneous fit. Only the FPMB constant unlinked, fixed at 1.
						    # Hence, it is redundant to define them here separately but link below.


# Defining priors for UltraNest #
m1_A.factor_1.prior = Uniform_prior(lower_bound=0.9, upper_bound=1.1)
m1_A.alpha_2.prior = Uniform_prior(lower_bound=0.0, upper_bound=4.0)
m1_A.beta_2.prior = Uniform_prior(lower_bound=0.0, upper_bound=4.0)
m1_A.norm_2.prior = Log_uniform_prior(lower_bound=1.e-10, upper_bound=10.0)


# Define point-source models for fitting #
A1 = PointSource("srcA", 0, 0, spectral_shape=m1_A)
B1 = PointSource("srcB", 0, 0, spectral_shape=m1_B)

model1 = Model(A1,B1)


#-----------------------------------------------------------------------------------------------------------------------------#


### Linking FPMB pars with corresponding FPMA pars, except "factor_1" for cross-calibration ###
model1.link(model1.srcB.spectrum.main.composite.alpha_2, model1.srcA.spectrum.main.composite.alpha_2)
model1.link(model1.srcB.spectrum.main.composite.beta_2, model1.srcA.spectrum.main.composite.beta_2)
model1.link(model1.srcB.spectrum.main.composite.norm_2, model1.srcA.spectrum.main.composite.norm_2)
model1.link(model1.srcB.spectrum.main.composite.redshift_2, model1.srcA.spectrum.main.composite.redshift_2)
model1.link(model1.srcB.spectrum.main.composite.pivote_2, model1.srcA.spectrum.main.composite.pivote_2)

###print(model1.display(complete=True))
###print(model1.srcB.spectrum.main.composite.beta_2.display())


#-----------------------------------------------------------------------------------------------------------------------------#


### The data ###
fpma = OGIPLike("FPMA", observation="/path/to/my/FPMA_src.pha")
fpma.set_active_measurements("3-50")

fpmb = OGIPLike("FPMB", observation="/path/to/my/FPMB_src.pha")
fpmb.set_active_measurements("3-50")

fpma.assign_to_source("srcA")
fpmb.assign_to_source("srcB")

data = DataList(fpma,fpmb)


#-----------------------------------------------------------------------------------------------------------------------------#


### BAYESIAN ANALYSIS ###
ba = BayesianAnalysis(model1, data)
ba.set_sampler("ultranest")
ba.sampler.setup(min_num_live_points=500, frac_remain=0.5, use_mlfriends=True, chain_name="/path/to/my/fpm/data/output_ultranest_500lp")
_ = ba.sample()
ar_ba = ba.results

# Writing Analysis Results to a file for later #
ar_ba.write_to("Model1_AR_500lp.fits",overwrite=True)    # Stores in the current directory "/path/to/my/fpm/data"

fig = display_spectrum_model_counts(ba)
plot_spectra(ar_ba, ene_min=3.0, ene_max=50.0, num_ene=300, use_components=True, equal_tailed=False, confidence_level=0.90)


### Reloading AR for analysis ###
#ar_ba_re = load_analysis_results("Model1_AR.fits")
#print(ar_ba_re.get_data_frame("equal tail",cl=0.9973))
#print(ar_ba_re.get_data_frame("hpd"))
#print(ar_ba_re.display())
#fig = ar_ba.corner_plot()
#fig.savefig("/path/to/my/fpm/data/output_ultranest_500lp/plots/Model1_corner_500lp.pdf")

```
There are a few things. First, bounds are only used in MLE fits for certain optimizers. They will interfere with priors if the bounds do not coincide with the range of the prior. You can simply remove the bounds with 

```python
param.bounds = (None, None)
```

or in at least the dev branch you can turn them off with the astromodels configuration:

```yaml

modeling:
  use_parameter_transforms: false
  ignore_parameter_bounds: true

```

The workflow you have designed is not really needed in this case. The sharing of the model between datasets is built in and the calibration constant is included in the SpectrumLike plugins. You can simplify this code in this way:

```python 
### Setting up the models for FPMA and FPMB spectra ###
from astromodels.xspec.factory import *
from astromodels.xspec.xspec_settings import *
from astromodels.functions.priors import *
xspec_cosmo(H0=73.0)
xspec_abund("wilm")
xspec_xsect("vern")

m1_A = XS_zlogpar()


m1_A.alpha.value = 2.0
m1_A.pivote.value = 6.4
m1_A.pivote.fix = True
m1_A.redshift.value = 0.0308
m1_A.redshift.fix = True


# Defining priors for UltraNest #

m1_A.alpha.prior = Uniform_prior(lower_bound=0.0, upper_bound=4.0)
m1_A.beta.prior = Uniform_prior(lower_bound=0.0, upper_bound=4.0)
m1_A.norm.prior = Log_uniform_prior(lower_bound=1.e-10, upper_bound=10.0)


# Define point-source models for fitting #
A1 = PointSource("srcA", 0, 0, spectral_shape=m1_A)

model1 = Model(A1)

### The data ###
fpma = OGIPLike("FPMA", observation="/path/to/my/FPMA_src.pha")
fpma.set_active_measurements("3-50")

fpmb = OGIPLike("FPMB", observation="/path/to/my/FPMB_src.pha")
fpmb.set_active_measurements("3-50")

fpm.use_effective_area_correction(0.9,1.1)

data = DataList(fpma,fpmb)

ba = BayesianAnalysis(model1, data)

```

and so forth.

**Comment by kchoX14** [comment]
> I'm not exactly sure why this is occurring. It is much easier to read the code here than downloading a file. E.g.

Yes, I uploaded a text file because my original question became longer since the screenshots took a lot of space.


> The workflow you have designed is not really needed in this case. The sharing of the model between datasets is built in and the calibration constant is included in the SpectrumLike plugins. You can simplify this code in this way:
> 
> ```python
> ### Setting up the models for FPMA and FPMB spectra ###
> from astromodels.xspec.factory import *
> from astromodels.xspec.xspec_settings import *
> from astromodels.functions.priors import *
> xspec_cosmo(H0=73.0)
> xspec_abund("wilm")
> xspec_xsect("vern")
> 
> m1_A = XS_zlogpar()
> 
> 
> m1_A.alpha.value = 2.0
> m1_A.pivote.value = 6.4
> m1_A.pivote.fix = True
> m1_A.redshift.value = 0.0308
> m1_A.redshift.fix = True
> 
> 
> # Defining priors for UltraNest #
> 
> m1_A.alpha.prior = Uniform_prior(lower_bound=0.0, upper_bound=4.0)
> m1_A.beta.prior = Uniform_prior(lower_bound=0.0, upper_bound=4.0)
> m1_A.norm.prior = Log_uniform_prior(lower_bound=1.e-10, upper_bound=10.0)
> 
> 
> # Define point-source models for fitting #
> A1 = PointSource("srcA", 0, 0, spectral_shape=m1_A)
> 
> model1 = Model(A1)
> 
> ### The data ###
> fpma = OGIPLike("FPMA", observation="/path/to/my/FPMA_src.pha")
> fpma.set_active_measurements("3-50")
> 
> fpmb = OGIPLike("FPMB", observation="/path/to/my/FPMB_src.pha")
> fpmb.set_active_measurements("3-50")
> 
> fpm.use_effective_area_correction(0.9,1.1)
> 
> data = DataList(fpma,fpmb)
> 
> ba = BayesianAnalysis(model1, data)
> ```
> 
> and so forth.

Ok. I set `fpma.use_effective_area_correction(0.9,1.1)` up there to adjust against the FPMB casae. And now it works. Thanks! 

But is there a way to see what value the posterior chose (HPD or median/mode) for this effective area correction? We set bounds for it. But what if this becomes unreal for cross-mission model fitting? At times an estimate for the cross-calibration constant has helped us in the X-ray community to figure out if there is a problem with the data or the instrument environment during exposure. The MCMC run over Xspec also takes this constant into consideration for the posterior sampling from flat priors.

**Comment by kchoX14** [comment]
**Other Questions parallel to the same needs**
1. Can similar adjustments be made with the `view_count_spectrum()` methods like it is possible for `display_spectrum_model_counts()`? 
2. Additionally, it'd be great if one could rebin ONLY the plot data (with both methods) up to a "min_significance" in terms of sigma, like Xspec does.
3. Which is the chain file than can be imported outside the threeML environment for external processing from the Monte Carlo samples? _There are three available after the sampling:_ `equal_weighted_post.txt`, `weighted_post.txt`, and `weighted_post_untransformed.txt`. The other file is the run.txt, which I'm aware what it is. The last is the AR container itself (a FITS file). I can then import this chain on Xspec to compute the equivalent width of my line later, as inquired in #558

**Comment by grburgess** [comment]
There are examples with effective area corrections in the documentation

**Comment by kchoX14** [comment]
> There are examples with effective area corrections in the documentation 

Yes, the GBM-BAT example worked.

**Comment by kchoX14** [comment]
> **Other Questions parallel to the same needs**
> 1. Can similar adjustments be made with the `view_count_spectrum()` methods like it is possible for `display_spectrum_model_counts()`? 
> 2. Additionally, it'd be great if one could rebin ONLY the plot data (with both methods) up to a "min_significance" in terms of sigma, like Xspec does.
> 3. Which is the chain file than can be imported outside the threeML environment for external processing from the Monte Carlo samples? _There are three available after the sampling:_ `equal_weighted_post.txt`, `weighted_post.txt`, and `weighted_post_untransformed.txt`. The other file is the run.txt, which I'm aware what it is. The last is the AR container itself (a FITS file). I can then import this chain on Xspec to compute the equivalent width of my line later, as inquired in #558 

It'd be very kind of you to also address these queries, if you may?
