### ISSUE TITLE
Importing chain file from the threeML BayesianAnalysis results over to Xspec

### ISSUE THREAD

**Issue by kchoX14** [threeML/threeML#562]
### Question:
After an _Ultranest_ `BayesianAnalysis()` run, which is the chain file than can be imported outside the threeML environment for external processing from the Monte Carlo samples? If I'm not wrong, it should be the same file that `corner_plot()` calls.

There are three text (not FITS) files available with parameter samples inside, after the BayesianAnalysis sampling with _UltraNest_:
-  `equal_weighted_post.txt`
-  `weighted_post.txt`
-  `weighted_post_untransformed.txt`. 

The other file is the `run.txt`, which contains the statistical bits. 
The last is the AR container itself (a FITS file). But it has a key issue that does not allow importing over Xspec. This is the error I get if I try to load it on Xspec with the `chain load myARfile.fits`:
`***XSPEC Error: Chain IO Error: while attempting to read CHAIN extension in myARfile.fits` 
I changed the EXTNAME keyword from "ANALYSIS_RESULTS" to "CHAIN" in the header file of a copy of the AR container. But the chain load after that returns an error I could not fix:
`***XSPEC Error: At least 1 pair of TEMPR and STROW keywords are required in file`

**Requirement:** 
Knowing which file is the correct one is essential, since I could then try to sample on Xspec to _compute the equivalent width of my line model component_. The `eqwidth` command on Xspec allows that from MCMC chain samples.

**Comment by grburgess** [comment]
This is a question about ultranest and should be directed there.

**Comment by kchoX14** [comment]
> This is a question about ultranest and should be directed there.

Understood. Thank you.

**Comment by kchoX14** [comment]
I shall provide an update here on the solution, if I find one over the _Ultranest_ repository. It may help someone else later. So, I request to keep this open until then.

**Comment by kchoX14** [comment]
> ### Question:
> After an _Ultranest_ `BayesianAnalysis()` run, which is the chain file than can be imported outside the threeML environment for external processing from the Monte Carlo samples? If I'm not wrong, it should be the same file that `corner_plot()` calls.
> 
> There are three text (not FITS) files available with parameter samples inside, after the BayesianAnalysis sampling with _UltraNest_:
> 
> * `equal_weighted_post.txt`
> * `weighted_post.txt`
> * `weighted_post_untransformed.txt`.
> 
> The other file is the `run.txt`, which contains the statistical bits. The last is the AR container itself (a FITS file). But it has a key issue that does not allow importing over Xspec. This is the error I get if I try to load it on Xspec with the `chain load myARfile.fits`: `***XSPEC Error: Chain IO Error: while attempting to read CHAIN extension in myARfile.fits` I changed the EXTNAME keyword from "ANALYSIS_RESULTS" to "CHAIN" in the header file of a copy of the AR container. But the chain load after that returns an error I could not fix: `***XSPEC Error: At least 1 pair of TEMPR and STROW keywords are required in file`
> 
> **Requirement:** Knowing which file is the correct one is essential, since I could then try to sample on Xspec to _compute the equivalent width of my line model component_. The `eqwidth` command on Xspec allows that from MCMC chain samples.


### Solution:
It's the `equal_weighted_post.txt` file.
[https://johannesbuchner.github.io/UltraNest/performance.html#output-files](https://johannesbuchner.github.io/UltraNest/performance.html#output-files)
