### ISSUE TITLE
fit Fermi GBM data?

### ISSUE THREAD

**Issue by Burdw** [threeML/threeML#565]
Hello all, I would like to ask if you have used 3ML+ multi model (CPL, BB, Syn, SBPL and the combination of the two) to fit Fermi GBM data. Is there a similar example?

**Comment by grburgess** [comment]
Please consult the documentation: https://threeml.readthedocs.io/en/latest/notebooks/flux_examples.html

**Comment by Hank-Grurdw** [comment]
@grburgess Thank you for your quick reply！
