### ISSUE TITLE
Install threeml, fermitools and fermipy 

### ISSUE THREAD

**Issue by Jisans** [threeML/threeML#566]

**Comment by grburgess** [comment]
https://threeml.readthedocs.io/en/stable/notebooks/installation.html

**Comment by Jisans** [comment]
@grburgess Sir, the installation instructions do not install threeml, fermitools and fermipy in the same environment, so I'm sorry to ask. Thank you!

**Comment by grburgess** [comment]
Consult the fermi tools documentation on how to install fermi tools. Installation of conda packages in general can be found in the conda documentation

**Comment by Jisans** [comment]
ok,thanks
