### ISSUE TITLE
MLE minimization algorithms: an appropriate choice

### ISSUE THREAD

**Issue by kchoX14** [threeML/threeML#567]
## Data Analysis Question

Having been accustomed to only the `Levenberg-Marquardt` (local) gradient descent algorithm over Xspec, my range of applications for model fitting in the MLE framework is very limited. I would request the community here to provide help regarding the following queries:

1. Which combination of global (assuming only grid and pagmo have been adopted yet) and local algorithm, from the experience of the community, would be recommended for the least arduous but the most accurate minimization en route to the global minimum in a complex parameter space? There seem to be quite a few local ones (TNC. SLSQS, L-BFGS-B, Migrad, Minimize).

2. **Specific to _pygmo_:**  Has anyone found any backward compatibility issues if their GCC version was < 9 before installing [`pagmo2` from source](https://esa.github.io/pagmo2/install.html#installation-from-source)? [Pagmo documentation](https://esa.github.io/pagmo2/install.html#dependencies) recommends `gcc-9` on Linux. I'm using Ubuntu 18.04 LTS. I do not wish to upgrade from my `gcc-7.5` because my Xspec/Heasoft is configured with it.

**Comment by omodei** [comment]
Dear Kishalay, I marked this issue as non relevant because there are really no "issues" with our code reported here. For the 1st point, I don't really know the answer. I guess it's really problem specific. For the second point, you should follow-up with pygmo developers.

**Comment by kchoX14** [comment]
> Dear Kishalay, I marked this issue as non relevant because there are really no "issues" with our code reported here. For the 1st point, I don't really know the answer. I guess it's really problem specific. For the second point, you should follow-up with pygmo developers.

I'll take care further. Thank you @omodei
