### ISSUE TITLE
twopc PPC plots don't work

### ISSUE THREAD

**Issue by kchoX14** [threeML/threeML#568]
**Describe the bug**
As per [twopc documentation homepage](https://jmichaelburgess.com/twopc/index.html#welcome-to-twopc-s-documentation), the library helps to "_generate posterior predictive checks from 3ML bayesian fits to spectra_". I tired the plotting after defining the `BayesianAnalysis()` instance. These are the issues faced:

- First, I followed the instructions to simply plot the prior predictive check on my `OGIPLike` data, [as mentioned here](https://jmichaelburgess.com/twopc/notebooks/docs.html#Compute-the-prior-predictive-checks). The error returned: `AttributeError: 'PPC' object has no attribute 'fake'`. Similar error if I omit the `fake` part: `AttributeError: 'PPC' object has no attribute 'plot'`.
- Second, I looked into the [`twopc.ppc` module description](https://jmichaelburgess.com/twopc/notebooks/api/twopc.html#module-twopc.ppc) and instead tried to load the created HDF5 file (above using `compute_priorpc()`) with the [`twopc.ppc.PPC()`](https://jmichaelburgess.com/twopc/notebooks/api/twopc.html#twopc.ppc.PPC) class's `file_name` object. I then called `plot()` as `twopc.ppc.PPC.plot()`. Result same: `AttributeError: 'PPC' object has no attribute 'plot'`. 
- Lastly, I see the `plot()` instance seems to be applicable only under the class [`twopc.ppc.PPCDetector`](https://jmichaelburgess.com/twopc/notebooks/api/twopc.html#twopc.ppc.PPCDetector), not `twopc.ppc.PPC`. But there's not much description on parameters there and on how to directly feed the HDF5 file with ease at the same time for quick computation. To be able to call `plot` as a `PPCDetector` class instance, if I use the `name` argument of the class to input the HDF5 filename as a string, it returns the error:  `TypeError: __init__() missing 8 required positional arguments: 'obs_counts', 'obs_background', 'mask', 'ebounds', 'exposure', 'scale_factor', 'ppc_counts', and 'ppc_background'`. It's perhaps this part that is the key to understand how to use `plot()` inside the `PPCDetector` class, after which I'd like to use `plot_qq()` for Quantile-Quantile plots (another instance, it seems, under `PPCDetector` exclusively).

(P.S. the same is true for the posterior predictive check plots with `compute_postpc()`)

*NOTE:* This is for BUG reports and not questions about generic data analysis.

**Desktop:**
 - OS: Linux
 - Version: Ubuntu 18.04 LTS

**Comment by grburgess** [comment]
Is this an issue with 3ML?

**Comment by kchoX14** [comment]
> Is this an issue with 3ML?

Since `twopc` is stated to be a library in order to carry out PPC after 3ML bayesian runs, I presumed it'd be better to ask here instead of the Twopc git page because it goes parallel with the other plots within 3ML. 

I'll redirect this question there, if that works better?
