### ISSUE TITLE
3ML data progress bar

### ISSUE THREAD

**Issue by Jisans** [threeML/threeML#569]
Hello to all,
Has the progress bar of threeml download data been changed ?

Now that my has become like this, are you all the same?

![image](https://user-images.githubusercontent.com/110452095/186599014-46a3b385-35e9-4ed4-bf34-7883ce72ce44.png)

 System: Linux DESKTOP-10UCA6U 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

environment：conda ENV
library version
`python 3.7.12，pip  22.2.2, threeml 2.2.3, astromodels  2.3.9, xspec-modelsonly 6.30.1`

**Comment by grburgess** [comment]
This appears to be a general issue with tqdm for what I can tell. The behavior started yesterday.

**Comment by Jisans** [comment]
ok,thank very much!

**Comment by grburgess** [comment]
https://github.com/tqdm/tqdm/issues/1359

**Comment by Jisans** [comment]
Problem solving
`pip install -U "git+https://github.com/tqdm/tqdm.git@fix-jupyterlab#egg=tqdm"`
