### ISSUE TITLE
Combined LAT and GBM Analysis

### ISSUE THREAD

**Issue by jmchen5821** [threeML/threeML#570]
Hello! Can 3ML combine LAT and GBM data analysis?

**Comment by grburgess** [comment]
Yes

**Comment by grburgess** [comment]
Please consult the fermitools issue tracker for issues with fermitools.

**Comment by omodei** [comment]
We are in the process of releasing new version of astromodels and threeML to anaconda. Those version will be compatible with the new version of fermitools and python 3.9.
