### ISSUE TITLE
threeml, astromodels, fermitools, fermipy can be used together?

### ISSUE THREAD

**Issue by Burdw** [threeML/threeML#574]
Hello,

Can the current versions of threeML v2.3.2 and astromodels v2.3.9 be used together with fermitools v2.2.0 and fermipy v1.0.1?

**Comment by henrikef** [comment]
@Burdw  fermipy 1.0.1 is not compatible with fermitools 2.2.0. The most recent version is fermipy 1.1.6 and you will need to [install it](https://fermipy.readthedocs.io/en/latest/install.html) from pypi. 

Additionally, I believe the latest threeML release on conda is only provided for python 3.7 (which will change in the next releases). So for now, I would recommend installing fermitools via conda, then fermipy, threeML, and astromodels via pip.

**Comment by Burdw** [comment]
@henrikef Have you tried?

**Comment by henrikef** [comment]
I've installed it that way, except I'm using the dev versions of threeML and astromodels (from github).

**Comment by Burdw** [comment]
I once installed it, but when I import threeml library, I will kill my jupyter lab kernel

**Comment by henrikef** [comment]
I'm sorry. I cannot help unless you can provide an actual error message or stack trace or something. I use jupyter notebooks without issues.

**Comment by Burdw** [comment]
Can I use scripts to install now?

**Comment by grburgess** [comment]
Likely if the are version mismatches with he python requirements, this will cause a crash.

**Comment by Burdw** [comment]
@grburgess But sir, now fermitools, fermipy (not in conda-forge channel), astromodels, these libraries all have python3.9 version, will threeml be compatible with python3.9 version?

**Comment by grburgess** [comment]
First, I've never been knighted, so there is no reason to use **sir***. 

I'm not sure I understand the question. If they are all 3.9 then they are all compatible
