### ISSUE TITLE
Installation with Fermitools

### ISSUE THREAD

**Issue by grburgess** [threeML/threeML#577]
### Discussed in https://github.com/threeML/threeML/discussions/576

<div type='discussions-op-text'>

<sup>Originally posted by **PepeJoseHU** September 11, 2022</sup>
Hello, I plan to install 3ML for Fermi data with CONDA, but looks 3ML have dependence with fermitools. But when I install 'fermitools', it also make an environment with CONDA, so how to fix this problem or if there have way to make connection between different CONDA environments?

Thanks!</div>

**Comment by henrikef** [comment]
@PepeJoseHU 

Please install fermitools (version 2.2.0 or newer) via conda or mamba as described here: 

https://fermipy.readthedocs.io/en/latest/install.html

Then use `pip` to install fermipy into the same environment (as shown there as well). Then use `pip install threML` to install threeML into the same environment as well.

**Comment by PepeJoseHU** [comment]
Thanks henrikef,

I try to install fermitools with 'conda install fermitools/ conda install -c conda-forge fermitools' 
But it have an error said : 'PackagesNotFoundError: The following packages are not available from current channels:"
Do you know how to fix that? I used ubuntu 16.04 and this environment is python3.7.
BTW, if fermipy can be used with python 3.7?

Thank you very much!

**Comment by Jisans** [comment]
your conda channel has not added Fermi channel, because fermitools are stored in fermi channel.

**Comment by PepeJoseHU** [comment]
Thanks Jisans,
Yes, even I add the channel, but it still not working. 
So finally, I make a new environment to install, looks working now. still test. Thanks

**Comment by Jisans** [comment]
@PepeJoseHU Very good. I want to know if you install `threeML`, `fermitools` and `fermipy` in the same environment, and whether the kernel will be killed when you `from threeML import *`.this situation puzzled me for a long time.

**Comment by Jisans** [comment]
@PepeJoseHU Now I have successfully installed threeml, fermitools, fermipy in the same environment,and threeml works well.

**Comment by PepeJoseHU** [comment]
@Jisans Hello, glad to hear that, it is also my first time to use it. So, how to check if the kernel kill that? 
I tried with from 3ml import and looks  just have several warnings, not sure if that is that means killed.
Yes, 3ml fermitool fermipy together in one environment.

**Comment by Jisans** [comment]
@PepeJoseHU This is normal,If you don't want to have these warnings, you can set them in .bashrc if your shell is bash, 
```
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
```

**Comment by PepeJoseHU** [comment]
@Jisans Thanks, Yes, I used ubuntu 16.04. But those export not work for me, still have those warnings appear.
Not sure if that is the problem of a old ubuntu.

**Comment by Jisans** [comment]
@PepeJoseHU Some warnings may pop up because some of your modules are not installed.These modules need to be installed additionally, such as ROOT, PyGMO, cthreeML, etc

**Comment by PepeJoseHU** [comment]
@Jisans OMG, Do you know if these modules not installed,  is the 3ml will still works properly? Otherwise, I think I need to install them also. Thanks!

**Comment by Jisans** [comment]
@PepeJoseHU It does not affect the 3ml work. These additional 3ml libraries are used in specific 3ml tutorials, such as PAGMO minimizer. At the same time, the 3ml development team members have also attached links to open source projects.

**Comment by PepeJoseHU** [comment]
@Jisans Thanks a lot! I got it. Then I will only install them when it is needed. Thank you very much!^_^

**Comment by Jisans** [comment]
@PepeJoseHU You are welcome！！！

**Comment by henrikef** [comment]
@PepeJoseHU It looks like you were able to install everything together now. I'm going to close this issue. Please re-open if you still have installation issues, and open a new one for any new error.

**Comment by PepeJoseHU** [comment]
Ok, Thanks!
