### ISSUE TITLE
Error occurs when running threeML examples

### ISSUE THREAD

**Issue by Jisans** [threeML/threeML#580]
Hello,all
When I run the `FermiLATLike_example.ipynb` code in 3ML examples, an error is reported
```
#Relevant GRB data, sourced from the GRB catalog
trigger_id = 'bn080916009'
ra, dec, redshift, index, tstart, tstop = 119.889999, -56.700001, 4.350, -2.072603, 3.03, 1531.780029

#Create the source model
source_1 = createSrcModel(trigger_id, ra, dec, redshift, index)

#Calls doTimeResolvedLike helper function, creating a directory from which we can sift the appropriate fit files
doLAT(trigger_id, ra, dec, [tstart], [tstop])

#The files retrieved by the doLAT step:
ft2File = os.path.expandvars('${HOME}/FermiData') + '/%s/gll_ft2_tr_%s_v00.fit'%(trigger_id,trigger_id)
directory= '%s/interval%s-%s/' % ('.', tstart, tstop)
eventFile = glob.glob("%s/*_filt.fit" % directory)[0]
expomap = glob.glob("%s/*_filt_expomap.fit" % directory)[0] 
ltcube = glob.glob("%s/*_filt_ltcube.fit" % directory)[0]


#create LAT plugin using this data -- importantly, passing the source name:
lat_plugin_1 = FermiLATLike(trigger_id, eventFile, ft2File, ltcube, 'unbinned', expomap, source_name = trigger_id)
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In [2], line 6
      3 ra, dec, redshift, index, tstart, tstop = 119.889999, -56.700001, 4.350, -2.072603, 3.03, 1531.780029
      5 #Create the source model
----> 6 source_1 = createSrcModel(trigger_id, ra, dec, redshift, index)
      8 #Calls doTimeResolvedLike helper function, creating a directory from which we can sift the appropriate fit files
      9 doLAT(trigger_id, ra, dec, [tstart], [tstop])

Cell In [1], line 67, in createSrcModel(src_name, ra, dec, redshift, index)
     64 powerlaw.index   = index
     65 powerlaw.index.free = False
---> 67 ebl = EBLattenuation()
     68 #This attenuation parameter is what we want to link across multiple source models.
     69 ebl.attenuation.prior = Uniform_prior(lower_bound = 0.0, upper_bound = 2.0)

NameError: name 'EBLattenuation' is not defined

ENV: conda v 4.14.0
Python v3.9.13 ,pip v 22.2.2
fermitools v2.2.0
fermipy v1.1.6

**Comment by grburgess** [comment]
I believe the ebl models depend on an external package. You should get a warning that says it's not installed.

**Comment by Jisans** [comment]
The warning I received was that,·NameError: name 'EBLattenuation' is not defined·

**Comment by grburgess** [comment]
That's an error and not a warning.

**Comment by xboluna** [comment]
@Jisans You need [ebltable](https://github.com/me-manu/ebltable). 
`pip install ebltable`

**Comment by Jisans** [comment]
@xboluna thanks!

**Comment by Jisans** [comment]
I'm sorry to bother you again,I didn't find the installation page of how to install ROOT: in the 3ml tutorial. I hope someone can share this installation method . Thank you!

**Comment by xboluna** [comment]
In the past I have just used the [install_3ML.sh](https://github.com/threeML/threeML/blob/master/install_3ML.sh) script on a fresh environment. With an existing environment, you would need to just collect all the packages for the ROOT flag. In this case, line 295 has `root=6.22` so perhaps `conda install root=6.22`. Conda will probably take a while to solve.

**Comment by Jisans** [comment]
@xboluna thanks!

**Comment by Jisans** [comment]
How to solve this problem
```
lat_obs = analysis_builder.run(recompute_intervals=False)[0]
```
```
15:38:29 INFO      About to run the following command:                                 [lat_transient_builder.py](file:///home/jisans/miniconda3/envs/fermi3ml/lib/python3.9/site-packages/threeML/utils/data_builders/fermi/lat_transient_builder.py):[622](file:///home/jisans/miniconda3/envs/fermi3ml/lib/python3.9/site-packages/threeML/utils/data_builders/fermi/lat_transient_builder.py#622)
                  /home/jisans/miniconda3/envs/fermi3ml/lib/python3.9/site-packages/ferm                             
                  itools/GtBurst/scripts/doTimeResolvedLike.py 080916009 --outfile                                 
                  'test' --roi 5.000000 --tstarts '3.6' --tstops '7.7' --zmax                                      
                  100.000000 --emin 100.000000 --emax 100000.000000 --irf 'p8_source'                              
                  --galactic_model 'template' --particle_model 'isotr template'                                    
                  --source_model 'PowerLaw2' --tsmin 20.000000 --strategy 'time'                                   
                  --thetamax 180.000000 --spectralfiles 'no' --liketype 'unbinned'                                 
                  --optimizeposition 'no' --datarepository '/home/jian/FermiData'                                  
                  --ltcube '' --expomap '' --ulphindex -2.000000 --flemin 100.000000                               
                  --flemax 10000.000000 --fgl_mode 'fast'
```
/bin/sh: 1: /home/jisans/miniconda3/envs/fermi3ml/lib/python3.9/site-packages/fermitools/GtBurst/scripts/doTimeResolvedLike.py: Permission denied
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In [11], line 1
----> 1 lat_obs = analysis_builder.run(recompute_intervals=False)[0]

IndexError: list index out of range

**Comment by Jisans** [comment]
@xboluna  Excuse me, when I can't use `conda install root=6.22` to install
Note: 
conda ENV,Python 3.9.13,pip 22.2.2,threeml 2.3.2,astromodels  2.3.9.dev3,fermitools 2.2.0,fermitools-data v0.18,fermipy v1.1.6

**Comment by xboluna** [comment]
I'm confused. Is this what you get when you run the `conda install root=6.22` line?

If so, looks like conda can't solve the package conflicts. It might be easier to do a fresh install with all your packages in one line. You aren't trying to install this on base, are you?

**Comment by Jisans** [comment]
Yes, I created a new virtual environment with conda, and then installed the required packages in this environment.

**Comment by henrikef** [comment]
@Jisans the "permissions denied" is an issue in gtburst. I think you can just `chmod u+x` the affected files. @omodei might have another idea.

Can't help with the `root` issue but I would recommend to not use it unless it's really necessary.

**Comment by Jisans** [comment]
@henrikef Thank you. I'm a beginner of `threeml`, `fermitools`, `fermipy`, so I think the tutorial examples are very important to me. However, the `threeml` tutorial has examples that use `ROOT`, which leads me to want to install it

**Comment by henrikef** [comment]
@Jisans We're in the process of updating the tutorials. If this is about the ROOT minimizer, you can change it to `jl.set_minimizer("minuit")` .

hawc_hal also doesn't require root anymore, the tutorial needs to be updated accordingly.

**Comment by Jisans** [comment]
@henrikef Thank you. I have a small request. I hope that Threeml can add more courses to analyze some astronomical events.

**Comment by omodei** [comment]
@Jisans , the documentation will be updated to the most current version and we will make sure the tutorials work. Sorry, but we are very few to contribute to ThreeML. In fact, we really hope other people (like you) could start contributing with examples so that the documentation becomes more complete.

**Comment by Jisans** [comment]
@omodei Ok, I'll try some things, after all I'm not yet familiar enough with 3ML and my abilities are limited.
