### ISSUE TITLE
Error getting install_3ML.sh script to install

### ISSUE THREAD

**Issue by ghost** [threeML/threeML#584]
Hello all, I tried to use the `install_3ML.sh` script to install threeML and Fermitools at the same time, but the following error occurred, Why is this?
```
install_3ML.sh --with-xspec --with-root --with-fermi --python 3.9 --env-name fermi3ml

```
err:
➜ bash install_3ML.sh --with-xspec --with-root --with-fermi --python 3.9 --env-name fermi3ML

Options:
--------
Installing xspec:                              yes
Installing root:                               yes
Installing fermi:                              yes
Batch execution (assume yes to all questions): yes
Python version:                                3.9
Conda environment name:                        fermi3ML

Running on linux

###############################################

Installing/checking Conda installation

###############################################

Found an already existing installation of conda in /home/Walker/miniconda3

###############################################

Installing 3ML

###############################################

Warning: 'defaults' already in 'channels' list, moving to the top
Warning: 'conda-forge' already in 'channels' list, moving to the top
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/Walker/miniconda3

  added / updated specs:
    - mamba

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _openmp_mutex-4.5          |       2_kmp_llvm           6 KB  conda-forge
    ca-certificates-2022.9.24  |       ha878542_0         150 KB  conda-forge
    certifi-2022.9.24          |     pyhd8ed1ab_0         155 KB  conda-forge
    conda-4.14.0               |   py39hf3d152e_0        1011 KB  conda-forge
    libarchive-3.5.2           |       hb890918_3         1.6 MB  conda-forge
    libiconv-1.17              |       h166bdaf_0         1.4 MB  conda-forge
    libmamba-0.25.0            |       hd8a31e3_2         1.5 MB  conda-forge
    libmambapy-0.25.0          |   py39hd55135b_2         296 KB  conda-forge
    libsolv-0.7.22             |       h6239696_0         443 KB  conda-forge
    llvm-openmp-14.0.4         |       he0ac6c6_0         5.8 MB  conda-forge
    mamba-0.25.0               |   py39hfa8f2c8_2          46 KB  conda-forge
    reproc-14.2.3              |       h7f98852_0          28 KB  conda-forge
    reproc-cpp-14.2.3          |       h9c3ff4c_0          20 KB  conda-forge
    yaml-cpp-0.7.0             |       h27087fc_1         214 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        12.6 MB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/linux-64::bzip2-1.0.8-h7f98852_4
  c-ares             conda-forge/linux-64::c-ares-1.18.1-h7f98852_0
  icu                conda-forge/linux-64::icu-70.1-h27087fc_0
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0
  krb5               conda-forge/linux-64::krb5-1.19.3-h3790be6_0
  libarchive         conda-forge/linux-64::libarchive-3.5.2-hb890918_3
  libcurl            conda-forge/linux-64::libcurl-7.83.1-h7bff187_0
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2
  libev              conda-forge/linux-64::libev-4.33-h516909a_1
  libiconv           conda-forge/linux-64::libiconv-1.17-h166bdaf_0
  libmamba           conda-forge/linux-64::libmamba-0.25.0-hd8a31e3_2
  libmambapy         conda-forge/linux-64::libmambapy-0.25.0-py39hd55135b_2
  libnghttp2         conda-forge/linux-64::libnghttp2-1.47.0-hdcd2b5c_1
  libsolv            conda-forge/linux-64::libsolv-0.7.22-h6239696_0
  libssh2            conda-forge/linux-64::libssh2-1.10.0-haa6b8db_3
  libxml2            conda-forge/linux-64::libxml2-2.9.14-h22db469_4
  libzlib            conda-forge/linux-64::libzlib-1.2.12-h166bdaf_3
  llvm-openmp        conda-forge/linux-64::llvm-openmp-14.0.4-he0ac6c6_0
  lz4-c              conda-forge/linux-64::lz4-c-1.9.3-h9c3ff4c_1
  lzo                conda-forge/linux-64::lzo-2.10-h516909a_1000
  mamba              conda-forge/linux-64::mamba-0.25.0-py39hfa8f2c8_2
  pybind11-abi       conda-forge/noarch::pybind11-abi-4-hd8ed1ab_3
  python_abi         conda-forge/linux-64::python_abi-3.9-2_cp39
  reproc             conda-forge/linux-64::reproc-14.2.3-h7f98852_0
  reproc-cpp         conda-forge/linux-64::reproc-cpp-14.2.3-h9c3ff4c_0
  yaml-cpp           conda-forge/linux-64::yaml-cpp-0.7.0-h27087fc_1
  zstd               conda-forge/linux-64::zstd-1.5.2-h6239696_4

The following packages will be REMOVED:

  libgomp-11.2.0-h1234567_1

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2022.07.19~ --> conda-forge::ca-certificates-2022.9.24-ha878542_0
  certifi            pkgs/main/linux-64::certifi-2022.9.14~ --> conda-forge/noarch::certifi-2022.9.24-pyhd8ed1ab_0
  libgcc-ng          pkgs/main::libgcc-ng-11.2.0-h1234567_1 --> conda-forge::libgcc-ng-12.1.0-h8d9b700_16
  libstdcxx-ng       pkgs/main::libstdcxx-ng-11.2.0-h12345~ --> conda-forge::libstdcxx-ng-12.1.0-ha89aaad_16

The following packages will be SUPERSEDED by a higher-priority channel:

  _libgcc_mutex           pkgs/main::_libgcc_mutex-0.1-main --> conda-forge::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex          pkgs/main::_openmp_mutex-5.1-1_gnu --> conda-forge::_openmp_mutex-4.5-2_kmp_llvm
  conda              pkgs/main::conda-4.14.0-py39h06a4308_0 --> conda-forge::conda-4.14.0-py39hf3d152e_0
  openssl              pkgs/main::openssl-1.1.1q-h7f8727e_0 --> conda-forge::openssl-1.1.1q-h166bdaf_0

Downloading and Extracting Packages
conda-4.14.0         | 1011 KB   | ############################################################################# | 100%
libsolv-0.7.22       | 443 KB    | ############################################################################# | 100%
libarchive-3.5.2     | 1.6 MB    | ############################################################################# | 100%
reproc-cpp-14.2.3    | 20 KB     | ############################################################################# | 100%
libmambapy-0.25.0    | 296 KB    | ############################################################################# | 100%
ca-certificates-2022 | 150 KB    | ############################################################################# | 100%
mamba-0.25.0         | 46 KB     | ############################################################################# | 100%
libiconv-1.17        | 1.4 MB    | ############################################################################# | 100%
libmamba-0.25.0      | 1.5 MB    | ############################################################################# | 100%
_openmp_mutex-4.5    | 6 KB      | ############################################################################# | 100%
certifi-2022.9.24    | 155 KB    | ############################################################################# | 100%
reproc-14.2.3        | 28 KB     | ############################################################################# | 100%
llvm-openmp-14.0.4   | 5.8 MB    | ############################################################################# | 100%
yaml-cpp-0.7.0       | 214 KB    | ############################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.25.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Looking for: ['python=3.9', "astromodels[version='>=2']", "threeml[version='>=2']", 'xspec-modelsonly', 'root=6.22', 'fermitools', 'fermipy']

xspecmodels/linux-64                                          No change
xspecmodels/noarch                                            No change
threeml/noarch                                                No change
astropy/linux-64                                              No change
conda-forge/noarch                                            No change
threeml/linux-64                                              No change
astropy/noarch                                                No change
fermi/noarch                                                  No change
pkgs/main/linux-64                                            No change
pkgs/r/noarch                                                 No change
fermi/linux-64                                                No change
pkgs/main/noarch                                              No change
pkgs/r/linux-64                                               No change
conda-forge/linux-64                                25.6MB @   1.1MB/s 23.5s
Encountered problems while solving:
  - package root-6.22.2-py39hcf6bf92_2 requires root_base 6.22.2 py39h3ed7f5f_2, but none of the providers can be installed

**Comment by omodei** [comment]
Thanks for reporting this. root 6.22 is not supported in py3.9, and the new version of fermitools don't support root. You should not use --use-root option in the installer.

**Comment by AstrWalker** [comment]
I changed the install command to `bash install_3ML.sh --with-fermi --with-xspec --with-root --python 3.7 --env-name fermi3ML` .Although the installation was successful, I tried to `python -c from threeML import *` but it looks a little weird, I don't know why?
```
➜ python -c "from threeML import*"

WARNING: version mismatch between CFITSIO header (v3.47) and linked library (v3.46).

12:44:49 WARNING   The naima package is not available. Models that depend on it will not be available    functions.py:51
         WARNING   The GSL library or the pygsl wrapper cannot be loaded. Models that depend on it will  functions.py:72
                  not be available.
         WARNING   The ebltable package is not available. Models that depend on it will not be          absorption.py:37
                  available
12:44:50 INFO      Starting 3ML!                                                                          __init__.py:31
12:44:50 WARNING   The cthreeML package is not installed. You will not be able to use plugins which       __init__.py:80
                  require the C/C++ interface (currently HAWC)                                                          
WARNING RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


WARNING RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


WARNING RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

         WARNING   Could not import plugin HAWCLike.py. Do you have the relative instrument software     __init__.py:130
                  installed and configured?
WARNING: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed [astropy.extern.six]
```
And when I use `python -c "from astromodels.xspec import *"` is able to load the XSPEC model.but there was a warning！！！
```
➜ python -c "from astromodels.xspec import *"

WARNING: version mismatch between CFITSIO header (v3.47) and linked library (v3.46).

12:48:32 WARNING   The naima package is not available. Models that depend on it will not be available    functions.py:51
         WARNING   The GSL library or the pygsl wrapper cannot be loaded. Models that depend on it will  functions.py:72
                  not be available.
         WARNING   The ebltable package is not available. Models that depend on it will not be          absorption.py:37
                  available
Loading xspec models...Generating code for Xspec model bkn2pow...
Generating code for Xspec model bmc...
Generating code for Xspec model bremss...
Generating code for Xspec model brnei...
Generating code for Xspec model bvapec...
Generating code for Xspec model bvrnei...
Generating code for Xspec model bvtapec...
Generating code for Xspec model bvvapec...
Generating code for Xspec model bvvrnei...
Generating code for Xspec model bvvtapec...
Generating code for Xspec model c6mekl...
Generating code for Xspec model c6pmekl...
Generating code for Xspec model c6pvmkl...
Generating code for Xspec model c6vmekl...
Generating code for Xspec model carbatm...
Generating code for Xspec model cemekl...
Generating code for Xspec model cevmkl...
Generating code for Xspec model cflow...
Generating code for Xspec model compbb...
Generating code for Xspec model compLS...
Generating code for Xspec model compPS...
Generating code for Xspec model compST...
Generating code for Xspec model compth...
Generating code for Xspec model compTT...
Generating code for Xspec model cph...
Generating code for Xspec model cplinear...
Generating code for Xspec model cutoffpl...
Generating code for Xspec model disk...
Generating code for Xspec model diskir...
Generating code for Xspec model diskbb...
Generating code for Xspec model diskline...
Generating code for Xspec model diskm...
Generating code for Xspec model disko...
Generating code for Xspec model diskpbb...
Generating code for Xspec model diskpn...
Generating code for Xspec model eplogpar...
Generating code for Xspec model eqpair...
Generating code for Xspec model eqtherm...
Generating code for Xspec model equil...
Generating code for Xspec model expdec...
Generating code for Xspec model ezdiskbb...
Generating code for Xspec model gaussian...
Generating code for Xspec model gadem...
Generating code for Xspec model gnei...
Generating code for Xspec model grad...
Generating code for Xspec model grbm...
Generating code for Xspec model hatm...
Generating code for Xspec model jet...
Generating code for Xspec model kerrbb...
Generating code for Xspec model kerrdisk...
Generating code for Xspec model kyrline...
Generating code for Xspec model laor...
Generating code for Xspec model laor2...
Generating code for Xspec model logpar...
Generating code for Xspec model lorentz...
Generating code for Xspec model meka...
Generating code for Xspec model mekal...
Generating code for Xspec model mkcflow...
Generating code for Xspec model nei...
Generating code for Xspec model nlapec...
Generating code for Xspec model npshock...
Generating code for Xspec model nsa...
Generating code for Xspec model nsagrav...
Generating code for Xspec model nsatmos...
Generating code for Xspec model nsmax...
Generating code for Xspec model nsmaxg...
Generating code for Xspec model nsx...
Generating code for Xspec model nteea...
Generating code for Xspec model nthComp...
Generating code for Xspec model optxagn...
Generating code for Xspec model optxagnf...
Generating code for Xspec model pegpwrlw...
Generating code for Xspec model pexmon...
Generating code for Xspec model pexrav...
Generating code for Xspec model pexriv...
Generating code for Xspec model plcabs...
Generating code for Xspec model powerlaw...
Generating code for Xspec model posm...
Generating code for Xspec model pshock...
Generating code for Xspec model qsosed...
Generating code for Xspec model raymond...
Generating code for Xspec model redge...
Generating code for Xspec model refsch...
Generating code for Xspec model rnei...
Generating code for Xspec model sedov...
Generating code for Xspec model sirf...
Generating code for Xspec model snapec...
Generating code for Xspec model srcut...
Generating code for Xspec model sresc...
Generating code for Xspec model ssa...
Generating code for Xspec model step...
Generating code for Xspec model tapec...
Generating code for Xspec model vapec...
Generating code for Xspec model vbremss...
Generating code for Xspec model vcph...
Generating code for Xspec model vequil...
Generating code for Xspec model vgadem...
Generating code for Xspec model vgnei...
Generating code for Xspec model vmeka...
Generating code for Xspec model vmekal...
Generating code for Xspec model vmcflow...
Generating code for Xspec model vnei...
Generating code for Xspec model vnpshock...
Generating code for Xspec model voigt...
Generating code for Xspec model vpshock...
Generating code for Xspec model vraymond...
Generating code for Xspec model vrnei...
Generating code for Xspec model vsedov...
Generating code for Xspec model vtapec...
Generating code for Xspec model vvapec...
Generating code for Xspec model vvgnei...
Generating code for Xspec model vvnei...
Generating code for Xspec model vvnpshock...
Generating code for Xspec model vvpshock...
Generating code for Xspec model vvrnei...
Generating code for Xspec model vvsedov...
Generating code for Xspec model vvtapec...
Generating code for Xspec model zagauss...
Generating code for Xspec model zbbody...
Generating code for Xspec model zbknpower...
Generating code for Xspec model zbremss...
Generating code for Xspec model zcutoffpl...
Generating code for Xspec model zgauss...
Generating code for Xspec model zlogpar...
Generating code for Xspec model zpowerlw...
Generating code for Xspec model absori...
Generating code for Xspec model acisabs...
Generating code for Xspec model constant...
Generating code for Xspec model cabs...
Generating code for Xspec model cyclabs...
Generating code for Xspec model dust...
Generating code for Xspec model edge...
Generating code for Xspec model expabs...
Generating code for Xspec model expfac...
Generating code for Xspec model gabs...
Generating code for Xspec model heilin...
Generating code for Xspec model highecut...
Generating code for Xspec model hrefl...
Generating code for Xspec model ismabs...
Generating code for Xspec model lyman...
Generating code for Xspec model notch...
```

**Comment by omodei** [comment]
We are working on a new version of the installer script that will make the installation easier (py3.9 and root 6.26). Everything should be compatible, since fermitools actually don't require root anymore. For the warming, they are ok (ignore them).

**Comment by AstrWalker** [comment]
thank you very much！

**Comment by grburgess** [comment]
Cthreeml is not really needed anymore unless you have a plug-in written in C

**Comment by Echaquan** [comment]
Thank you for your answer, if I want to install it, can I install it?I can't install it according to the tutorial！

**Comment by Jisans** [comment]
Thanks for your answers！！！

**Comment by Echaquan** [comment]
Thanks for your answers！
