### ISSUE TITLE
Will 3ML be combined for analysis?

### ISSUE THREAD

**Issue by Echaquan** [threeML/threeML#590]
Hello all,
Can `threeML` analyze BAT, XRT, GBM, LAT data at the same time? Or if I want to do analysis like this, how can I use `threeML`?

**Comment by grburgess** [comment]
Yes. Please read the documentation. There are multiple examples.

**Comment by Echaquan** [comment]
But I didn't find an example of analyzing LAT data in the documentation?

**Comment by grburgess** [comment]
https://threeml.readthedocs.io/en/stable/notebooks/Fermipy_LAT.html

**Comment by Echaquan** [comment]
thanks,I have seen this example, but it seems that there is no example of using 3ML to analyze LAT GRB in the document, so I take the liberty to speak here.

**Comment by grburgess** [comment]
There is. Please see the documentation.

**Comment by Echaquan** [comment]
ok goodbye
