### ISSUE TITLE
 use 3ML to analyze Fermi GRB problem?

### ISSUE THREAD

**Issue by Echaquan** [threeML/threeML#591]
Hello all, 
When I use 3ML to analyze Fermi GRB, I see that the 3ML 080916C example has the best model, while some outbreaks do not have the best model. Is this model from the fermi GRB official website? How do we analyze without the best model? And how do we judge who is the best model? Is the value of BIC, DIC and AIC passed?

**Comment by grburgess** [comment]
Please use the templates when creating issues so that we can better track them
