### ISSUE TITLE
FermiGBMLike can't be used, can use that plugin instead

### ISSUE THREAD

**Issue by Jisans** [threeML/threeML#594]
Hello everyone, I am trying to use 3ML to analyze the data of fermi LAT GRB combined with the bn090217206 example in the GitHub source code. I would like to ask you how to solve the following errors, thank you!
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In [14], line 12
      9 rspFile     = os.path.join( datadir, "bn090217206_n6_weightedrsp.rsp{1}" )
     11 #Plugin instance
---> 12 NaI6 = FermiGBMLik( "NaI6", obsSpectrum, bakSpectrum, rspFile )
     14 #Choose energies to use (in this case, I exclude the energy
     15 #range from 30 to 40 keV to avoid the k-edge, as well as anything above
     16 #950 keV, where the calibration is uncertain)
     17 NaI6.setActiveMeasurements( "10.0-30.0", "40.0-950.0" )

NameError: name 'FermiGBMLik' is not defined
```
I double checked that the plugin I installed does not have **FermiGBMlike**

Available plugins
```
In [2]: get_available_plugins()
Available plugins:

FermiLATLike for Fermi LAT (standard classes)
XYLike for n.a.
OGIPLike for All OGIP-compliant instruments
SwiftXRTLike for Swift XRT
DispersionSpectrumLike for General binned spectral data with energy dispersion
PhotometryLike for Generic photometric data
SpectrumLike for General binned spectral data
FermipyLike for Fermi LAT (with fermipy)
```
I tried to install using pip without success
```
pip install FermiGBMLike
ERROR: Could not find a version that satisfies the requirement FermiGBMLike (from versions: none)
ERROR: No matching distribution found for FermiGBMLike
```
**Note:**

OS: Linux DESKTOP-10UCA6U 5.15.68.1-microsoft-standard-WSL2 #1 SMP Mon Sep 19 19:14:52 UTC 2022 x86_64 GNU/Linux
Python V 3.9.13
pip V 22.2.2
threeml V 2.4.0    
astromodels V  2.4.0

**Comment by grburgess** [comment]
Please follow the documented examples in the documentation for the analysis of fermi GBM data

**Comment by grburgess** [comment]
I think it will also be useful to review some basics on python modules and software installation. It is not possible to simply install a sub module of a python package with pip.

**Comment by Jisans** [comment]
OK, thanks

**Comment by grburgess** [comment]
@Leonard-25 please refrain from editing the issues and changing usernames. This behavior is indicative of bots.

**Comment by Leonard-25** [comment]
I just don't think the question I'm asking has much value, it's unnecessary to put it here, that's all! Sorry for any offense!
