### ISSUE TITLE
Help analyze Fermi GBM and Fermi LAT standard data

### ISSUE THREAD

**Issue by Liaomao123** [threeML/threeML#597]
Hello all, I am currently using threeML to analyze the Fermi GBM and Fermi LAT standard data and have encountered a problem. Could you please help me to find out what is wrong with this problem? Thanks!

**I've looked through the threeML tutorial documentation and still can't find a solution!**

```
bayes = BayesianAnalysis(band_model, datalist);
```

Found Isotropic template for irf P7REP_SOURCE_V15: 
/home/Liaomao/miniconda3/envs/fermi/share/fermitools/refdata/fermi/galdiffuse/iso_source_v05_rev1.txt

I was looking for gll_iem_v05_rev1.fit,gll_iem_v05_rev1.fits,gll_iem_v05.fits,gll_iem_v05.fit,template_4years_P7_v15_repro_v2_trim.fits into /home/Liaomao/miniconda3/envs/fermi3ML/share/fermitools/refdata/fermi/galdiffuse

---------------------------------------------------------------------------
GtBurstException                          Traceback (most recent call last)
Cell In [13], line 1
----> 1 bayes = BayesianAnalysis(band_model, datalist)

File ~/miniconda3/envs/fermi/lib/python3.9/site-packages/threeML/bayesian/bayesian_analysis.py:97, in BayesianAnalysis.__init__(self, likelihood_model, data_list, **kwargs)
     93 self._analysis_type: str = "bayesian"
     95 self._is_registered: bool = False
---> 97 self._register_model_and_data(likelihood_model, data_list)
     99 self._sampler: Optional[SamplerBase] = None

File ~/miniconda3/envs/fermi/lib/python3.9/site-packages/threeML/bayesian/bayesian_analysis.py:140, in BayesianAnalysis._register_model_and_data(self, likelihood_model, data_list)
    136 self._data_list = data_list
    138 for dataset in list(self._data_list.values()):
--> 140     dataset.set_model(self._likelihood_model)
    142     # Now get the nuisance parameters from the data and add them to the model
    143     # NOTE: it is important that this is *after* the setting of the model, as some
    144     # plugins might need to adjust the number of nuisance parameters depending on the
    145     # likelihood model
    147     for parameter_name, parameter in list(
    148         dataset.nuisance_parameters.items()
    149     ):
    150         # Enforce that the nuisance parameter contains the instance name, because otherwise multiple instance
    151         # of the same plugin will overwrite each other's nuisance parameters

File ~/miniconda3/envs/fermi/lib/python3.9/site-packages/threeML/plugins/FermiLATLike.py:410, in FermiLATLike.set_model(self, likelihood_model, source_name)
    407 self._lmc.set_file_spectrum_energies(self.emin, self.emax, self.n_energies)
    409 xml_file = str("%s.xml" % get_random_unique_name())
--> 410 temp_files = self._lmc.write_xml(xml_file, self.ra, self.dec, self.rad)
    412 if self.kind == "BINNED":
    413     self.like = BinnedAnalysis.BinnedAnalysis(
    414         self.obs, xml_file, optimizer="DRMNFB"
    415     )

File ~/miniconda3/envs/fermi/lib/python3.9/site-packages/threeML/plugins/FermiLATLike.py:140, in LikelihoodModelConverter.write_xml(self, xmlfile, ra, dec, roi)
    137 # Get a temporary filename which is guaranteed to be unique
    138 self._unique_filename = get_random_unique_name()
--> 140 gal = LikelihoodComponent.GalaxyAndExtragalacticDiffuse(
    141     self.irfs, ra, dec, 2.5 * roi, cutout_name=self._unique_filename
    142 )
    143 gal.source.spectrum.Value.max = 1.5
    144 gal.source.spectrum.Value.min = 0.5

File ~/miniconda3/envs/fermi/lib/python3.9/site-packages/fermitools/GtBurst/LikelihoodComponent.py:394, in GalaxyAndExtragalacticDiffuse.__init__(self, irf, ra, dec, rad, cutout_name)
    393 def __init__(self, irf, ra, dec, rad, cutout_name=None):
--> 394     TemplateFile.__init__(self, "GalacticTemplate", irf,
    395                           lambda irf: DiffuseSrcTemplateFunc(irf, ra, dec, rad, cutout_name=cutout_name))

File ~/miniconda3/envs/fermi/lib/python3.9/site-packages/fermitools/GtBurst/LikelihoodComponent.py:364, in TemplateFile.__init__(self, name, irf, constructorFunction, sysError, statError)
    363 def __init__(self, name, irf, constructorFunction, sysError=0.15, statError=0):
--> 364     self.source = constructorFunction(irf)
    365     self.source.name = name
    366     self.source.sysErr = '%s' % sysError

File ~/miniconda3/envs/fermi/lib/python3.9/site-packages/fermitools/GtBurst/LikelihoodComponent.py:395, in GalaxyAndExtragalacticDiffuse.__init__.<locals>.<lambda>(irf)
    393 def __init__(self, irf, ra, dec, rad, cutout_name=None):
    394     TemplateFile.__init__(self, "GalacticTemplate", irf,
--> 395                           lambda irf: DiffuseSrcTemplateFunc(irf, ra, dec, rad, cutout_name=cutout_name))

File ~/miniconda3/envs/fermi/lib/python3.9/site-packages/fermitools/GtBurst/LikelihoodComponent.py:150, in DiffuseSrcTemplateFunc(irf, ra, dec, rad, cutout_name)
    145 def DiffuseSrcTemplateFunc(irf, ra, dec, rad, cutout_name=None):
    146     diffuse = '''
    147    <spatialModel file="%s" type="MapCubeFunction">
    148      <parameter free="0" max="1000.0" min="0.001" name="Normalization" scale= "1.0" value="1.0"/>
    149    </spatialModel>
--> 150     ''' % (findGalacticTemplate(irf, ra, dec, rad, cutout_name=cutout_name))
    152     spectrum = '''
    153    <spectrum type="ConstantValue">
    154      <parameter free="1" max="1.3" min="0.7" name="Value" scale="1.0" value= "1.0"/>
    155    </spectrum>
    156     '''
    157     completeExpression = '<source name="diffuse source template" type="DiffuseSource">%s\n%s\n</source>' % (
    158     diffuse, spectrum)

File ~/miniconda3/envs/fermi/lib/python3.9/site-packages/fermitools/GtBurst/LikelihoodComponent.py:39, in findGalacticTemplate(irfname, ra, dec, rad, cutout_name)
     37 templ = findTemplate(irf.galacticTemplate)
     38 if (templ  is None):
---> 39     raise GtBurstException.GtBurstException(61,
     40                                             "You don't have a Galactic template for IRF %s. Cannot continue." % (
     41                                             irfname))
     42 else:
     43     print(("\nFound Galactic template for IRF. %s: %s" % (irfname, templ)))

**GtBurstException: You don't have a Galactic template for IRF P7REP_SOURCE_V15. Cannot continue.**

```
OS: Ubuntu20.04 LTS
Dependency package：
fermitools                2.2.0            py39h93a0a19_0    fermi
fermitools-data           0.18                          0    fermi
fermipy                   1.2                      pypi_0    pypi
threeml                   2.4.0              pyhd8ed1ab_0    conda-forge
astromodels               2.4.0+37.g1ffa3f8          pypi_0    pyp
```

**Comment by omodei** [comment]
Hi! From your log it is impossible to know what you are doing, but make sure to use Fermi LAT P8 IRFs. P7 are not supported anymore.

**Comment by Liaomao123** [comment]
I'm sorry, I may not have made it clear. I have a request, that is, I want to use 3ML to perform a joint analysis of the data of Fermi GBM and Fermi LAT. I carefully checked that the data types of Fermi LAT are two, one is LLE and the other is standard, standard LAT Data analysis can be done using Gtburst, a graphical interface tool, but this analysis only analyzes standard data, and does not perform joint likelihood analysis with Fermi GBM data, which I want to do. I noticed that to analyze the Fermi LAT standard data requires Fermipylike for likelihood analysis, but I got the above error when building the data_list object.

**Comment by omodei** [comment]
You don't need fermipylike plug in to analyze GRBs. You should use the FermiLATLike plug via the TransientLATDataBuilder. It internally uses gtburst. You can follow this example:
https://threeml.readthedocs.io/en/stable/md_docs/slow_execute/LAT_Transient_Builder_Example.html#the-lat-transient-builder

**Comment by Liaomao123** [comment]
Thank you for your help！
