### ISSUE TITLE
Corrupted Double Linked List Error when using the ROOT minimizer

### ISSUE THREAD

**Issue by SamGroetsch** [threeML/threeML#605]
**Describe the bug**
The bug was reported in the output files as "Error in `python': corrupted double-linked list:" at the end of the analysis procedure using the 3ML jointlikelihood module and the ROOT minimizer. 

**To Reproduce**

The bug does not always occur after each call of the python file (fitModelROOT.py) but occurs very frequently. Most of the time the error simply prints and then the program moves on but sometimes the error ends in  "*** Break *** abort" and then the program never moves past this error. This causes the program to hang and eventually time out. When using slurm this can be multiple days unless you check the output file to see if the fatal version of the error has occurred. 

Since the error occurs while analyzing non-public data and code I have provided 10 attempts to analyze the same data map using the same procedure that calls the fitModelROOT.py file. The python fitModel file is similar to the example code given on the hawc_hal github https://github.com/threeML/hawc_hal. You can see that some exit successfully even if the bug occurs while some error out and hang at the break abort line. It seems from a quick google that this may be a memory allocation issue but I am far from an expert on this.  This issue was not encountered when the minimizer is set to minuit instead of ROOT but other migrad errors occur when using minuit so we would like to not switch back if this issue can be resolved. Additionally,
 the error appears before any code after the fitModelROOT.py call in the bash script can run so I believe it is an issue when the python file is attempting to close and switch back to the bash script.

**Expected behavior**
There are some examples of the expected behavior in the log files from the fit where the fit ends and immediately moves to the next step without giving the corrupted double-linked list error. 

**Additional context**
In the output files searching "pixels in fit" will bring you near the end of any successful fits so you can check if the error occurred below. Searching "corrupted" leads to each occurrence of the error. Searching "curstep" will bring you to the lines right after the error has occurred if the fit failed due to migrad or "does not correspond" errors discussed in earlier issues. Since the output files are quite large I hope this speeds up any searching you do in them. A somewhat similar issue was encountered earlier and was opened as an issue in the hawc_hal github but was never addressed https://github.com/threeML/hawc_hal/issues/41.

[Outputs.zip](https://github.com/threeML/threeML/files/10342588/Outputs.zip)

**Comment by grburgess** [comment]
Uff. So is this an issue only when running things in parallel? The ROOT link is very old code. Maybe something has changed. But it's sad that there are still issues with iminuit vs standard ROOT Minuit.

**Comment by grburgess** [comment]
Oh these output files are way too large... they are crashing. Can you paste (in a proper formatting) the relevant lines that indicate the error?

**Comment by SamGroetsch** [comment]
Hi, thanks for taking a look the code was run 10 times separately so there shouldn't be any issues with parallelization.  I snipped 3 of the possible errors that occur from some of the log files and put them in their own text files. I'm not sure if that's what you mean by the proper format. The error backtrace is quite long but the file is only a few hundred KB so they shouldn't crash. The most troublesome is the Hang since it makes it almost impossible to recover from at least at my skill level. The other two are acceptable since they don't seem to change the results of the fit and allow the code to continue after a relatively short time.
[Corrupted Double Linked List Error No Crash.txt](https://github.com/threeML/threeML/files/10351584/Corrupted.Double.Linked.List.Error.No.Crash.txt)
[Corrupted Double Linked List Error Break Abort No Hang.txt](https://github.com/threeML/threeML/files/10351585/Corrupted.Double.Linked.List.Error.Break.Abort.No.Hang.txt)
[Corrupted Double Linked List Error Break Abort Hang.txt](https://github.com/threeML/threeML/files/10351586/Corrupted.Double.Linked.List.Error.Break.Abort.Hang.txt)

**Comment by grburgess** [comment]
I'm not deep enough into ROOT to know what could be causing this. Maybe @omodei would have a better idea. 

But just to be sure, iminuit is not giving a good result?

**Comment by SamGroetsch** [comment]
When I try to use jl.set_minimizer("minuit") instead of jl.set_minimizer("ROOT") the fit runs into fatal errors much more often. The error usually occurs when the model gets more complex than 2 or 3 sources. The text file attached includes the most common error when using that minimizer. For the source fitting script I am currently using the ROOT minimizer will have a fatal error about 50% of the time while the minuit minimizer has yet to complete without error. 
[Minuit Error.txt](https://github.com/threeML/threeML/files/10359211/Minuit.Error.txt)

**Comment by grburgess** [comment]
Hmm... how many parameters are you trying to fit?

**Comment by SamGroetsch** [comment]
In the case of that fit 6 total parameters with 4 being fit. It's two point source models but one has fixed spatial parameters. However, by the end of the fitting script, I could be fitting 20+ parameters.

**Comment by grburgess** [comment]
I do not think either of those optimizers are going to be able to handle that. Have you tried fitting with one of the samplers? I would do a dry run with emcee as it will immediately tell you if things are going well.

**Comment by SamGroetsch** [comment]
I'm a little surprised as other than the corrupted double-linked list error I've been getting with ROOT it has been able to complete the fits even with 20+ parameters. From what I see in the logs it seems like the fits with the ROOT minimizer complete successfully but when exiting the error occurs. I can try using the samplers but I haven't done any fits with them before so it may take me a bit to get it working.

**Comment by grburgess** [comment]
There are some good examples in the docs.

**Comment by SamGroetsch** [comment]
Thanks for the help with this issue. While attempting to implement the pygmo fitting I updated many packages and that seems to have resolved the issue. I'm not sure which package was the issue as I did not expect it to do anything.
